### ISSUE TITLE
Need Nvim 0.9.0:)

### ISSUE THREAD

**Issue by qianwch** [qvacua/vimr#1007]
Hi, Nvim 0.9.0 was released. There is an important fix about vim.lsp.buf.definition() crash....
So we are still waiting for vimr to enroll in.

**Comment by ThSGM** [comment]
Chiming in as well with the same issues. I'm unable to run vimr due to the telescope plugin requiring 0.9.

**Comment by ChrisGitIt** [comment]
Yeah, chiming in with everybody ... Telescope Support would be nice again ...

**Comment by georgeharker** [comment]
A new build which will allow pointing at external neovim is in the works.

**Comment by qvacua** [comment]
As @georgeharker mentioned, the new release uses 0.10.0-dev.
