### ISSUE TITLE
Distinguish VimR and MacVim

### ISSUE THREAD

**Issue by RobertAudi** [qvacua/vimr#101]
First of all, Thank you for this awesome project :+1:

I installed the latest bleeding edge build yesterday, and I discovered that all my `(g)vimrc` configs were applied. This is awesome, but it is also a bit annoying.

I use MacVim primarily, and terminal vim for fast edits. When launching VimR, my `gvimrc` settings are loaded even though I have `if has("gui_macvim")` at the top.

What I would like is to have VimR specific settings, and MacVim specific settings, which is not possible out of the box at the moment.

So I imagine that to make this possible, something like `has("gui_vimr")` needs to be implemented.

**Comment by james2doyle** [comment]
Can `gui_vimr` be added back? Seems like it is gone since the move to nvim.

Thanks!

**Comment by qvacua** [comment]
Will be done in GH-241
