### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by EdgeJ** [qvacua/vimr#1011]
It's been ~6 months since the last commit and a number of issues have piled up. Meanwhile, NeoVim v0.9 was released back in April. I'm hoping the answer is that @qvacua  is busy (maintaining open source is certainly a labor of love) but I'm a little worried that its abandoned and I'll end up needing to jump ship to another frontend to ever get the features in v0.9. VimR is by far the best GUI for MacOS. If it is the case that he is just totally swamped with the rest of his life, I would be curious if there was any community support for making this a project underneath an organization of some sort, rather than a personal project. I'm afraid I don't know enough Swift to be of much assistance on that front, but it's an interesting thought.

**Comment by smathy** [comment]
I just switched to https://github.com/equalsraf/neovim-qt because of some showstopper bugs for me. Thanks @qvacua - love your work. Sad to leave 😭

**Comment by georgeharker** [comment]
I'm working on a fork of this which I have (barely just) working. But the idea is to remove the uibridge layer and ideally talk to an externally installed nvim if so desired. 

I have stuff rendering and selection and interaction etc functional. It needs some tidy up before it would be ready for public consumption. 

But I hope to be able to resurrect this and allow newer versions of neovim. It's looking hopeful.

**Comment by georgeharker** [comment]
Please see #1015 for the modifications needed to get this back up and running on new neovim versions.

**Comment by qvacua** [comment]
I've been inactive for quite some time due to some private reasons. I'll be restarting slowly. @georgeharker created a PR which will let VimR use a stock binary of Neovim which I wanted to do. This would enable faster (or instant) adoption of newer Neovim versions. I'll work with @georgeharker in the next days to merge his PR and release a new version.

**Comment by EdgeJ** [comment]
Thanks for the update @qvacua. I certainly understand that FOSS is a labor of love. Greatly appreciate all your work!
