### ISSUE TITLE
Nread command is not available. 

### ISSUE THREAD

**Issue by TomSchimana** [qvacua/vimr#1021]
Updated to the new VimR (Version 0.45.0 (20231122.130444), which is based on neovim v0.10.0-dev.

Apparently, there's an issue with Nread?!?

:verbose set spell
spellfile#LoadFile(): Nread command is not available.
Warning: Cannot find word list 'de.utf-8.spl' or 'de.ascii.spl'"

Before this, it always worked.

**Comment by georgeharker** [comment]
I think Nread comes from netrw is that installed?

**Comment by TomSchimana** [comment]
Yes, thank you. That was it. Apparently, new VimR with 0.10 neovim reacts differently here. I have NVChat as a base, and there Netrw is disabled at startup for performance reasons, as far as I can see.
