### ISSUE TITLE
 has("gui_vimr")  Failed

### ISSUE THREAD

**Issue by charlestang** [qvacua/vimr#1023]
has("gui_vimr") in my config file return 0.

Version 0.45.0 (20231122.130444)

I used has("gui_running") instead.

**Comment by georgeharker** [comment]
This is expected. g:gui_come should however be set to 1

**Comment by wookayin** [comment]
Since the awesome work #1015 by @georgeharker `has("gui_running")` seems no longer possible because Vimr no longer ships a patched neovim.

I think we can `g:gui_vimr` use instead. Documentations https://github.com/qvacua/vimr/wiki#initvim
 and previous configs need an update.

**Comment by qvacua** [comment]
One better uses `if exists("g:gui_vimr")`
