### ISSUE TITLE
Code view is using 'natural' trackpad scroll even when its turned off system wide

### ISSUE THREAD

**Issue by Nekuromento** [qvacua/vimr#1026]
Latest build always uses 'natural' trackpad scroll for main window code view ignoring system settings. Other views like filesystem tree-view or buffer view are not affected and react to trackpad scroll correctly according to system settings.

I'm on MacOS `13.6.1` w/ build `v0.45.0-20231122.130444`

**Comment by georgeharker** [comment]
That’s odd. I thought I added code specifically to detect that and flip. Is this on the latest version - will investigate.

**Comment by qvacua** [comment]
One more data point: The scrolling with mouse wheel respects the system setting, however, trackpad scrolling does not.

**Comment by georgeharker** [comment]
Ah, it turns out the event gets the flipped direction automatically and was further being flipped - this will be fixed in the next release

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/v0.45.1-20231211.195158 contains the fix.
