### ISSUE TITLE
Solarized colorscheme rendering glitch

### ISSUE THREAD

**Issue by p3palazzo** [qvacua/vimr#1028]
When opening Vimr 0.45 or the snapshot (could not make the nightly build open here), there is a visual glitch where the Solarized colorscheme gives way to the default colors (white background) as soon as I move the cursor for the first time. Manually resizing the VimR window makes the glitch go away until quit and relaunch.

**Comment by qvacua** [comment]
What version of solarized colorscheme are you using? There seems to be multiple versions of solarized. Does it happen for dark and/or light scheme?

**Comment by p3palazzo** [comment]
I’m using the altercation/vim-colors-solarized plugin. Yest, it happens on both the light and dark modes, and on both 16 and 256 color mode.

**Comment by p3palazzo** [comment]
I’m happy to report that with the latest updates, this glitch went away.
