### ISSUE TITLE
`:language` command is not available

### ISSUE THREAD

**Issue by dyng** [qvacua/vimr#1033]
After upgrading to the latest version (`0.45.1,20231211.195158`), the `:language` command is found unavailable.

Error message:
```
E319: The command is not available in this version
```

I strongly suspect it's an issue with Neovim, but same issue **can't** be reproduced in Neovim v0.9.4.

**Comment by qvacua** [comment]
Please try the [newest release](https://github.com/qvacua/vimr/releases/tag/v0.46.1-20240114.181346). If the issue persists, please re-open the issue.

**Comment by dyng** [comment]
The new version works fine, thank you!
