### ISSUE TITLE
E1502: Lua failed to grow stack to 4001

### ISSUE THREAD

**Issue by kiryph** [qvacua/vimr#1044]
When I open a larger tex file in **VimR (version 4.46.0)**, I get following error:

```
E1502: Lua failed to grow stack to 4001
E1502: Lua failed to grow stack to 4001
...
```
**I do not get the error in VimR version 0.44.0 with neovim 0.8.2 from January 2023.**

I use the ftplugin [VimTeX](https://github.com/lervag/vimtex).

I raise this issue in the repository of VimR since I do not get the error on the command line or with other neovim guis such as [neovim-qt](https://github.com/equalsraf/neovim-qt) or [neovide](https://github.com/neovide/neovide).

Steps to reproduce:

1. Install VimTeX, e.g. with [lazy.nvim](https://github.com/folke/lazy.nvim) (My config started from [kickstart-modular.nvim](https://github.com/dam9000/kickstart-modular.nvim))
2. Open following tex file from the test folder of VimTeX:

[`~/.local/share/nvim/lazy/vimtex/test/test-toc-speed/main.tex`](https://github.com/lervag/vimtex/blob/master/test/test-toc-speed/main.tex)

![Screenshot 2024-01-04 at 09 54 21](https://github.com/qvacua/vimr/assets/371756/3d886ad4-16cc-4170-a7ed-a5ff3592c73f)

**VimR version: 0.46.0 (20240102.233758)**

**Comment by georgeharker** [comment]
It’s probably a neovim issue but you can point your vimr at the command line version you’re using in advanced prefs to check if that’s the case.

**Comment by kiryph** [comment]
@georgeharker Thanks for chiming in.

However, I have installed the same neovim version on cli 0.9.5 where I cannot reproduce the issue

```
❯ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
(base)
```

Opening the tex file is fine:
```
❯ nvim  ~/.local/share/nvim/lazy/vimtex/test/test-toc-speed/main.tex
```

**Comment by georgeharker** [comment]
Ah that is interesting will take a look

**Comment by kiryph** [comment]
@georgeharker Thanks for taking a look. Could you at least reproduce it?

When I install VimR version v0.44.0 with neovim 0.8.2 from January 2023, I do not get the error:
![Screenshot 2024-01-10 at 15 11 54](https://github.com/qvacua/vimr/assets/371756/7e08ab47-84d2-4325-98d1-fa17700294c3)

**Comment by georgeharker** [comment]
I don't use Lazy.nvim but installed via packer and see the same thing.

I also see the same with an external nvim but have zero idea why.  Tried TSUpdate, Packerupdate to see if something was out of sync.  I don't have an earlier neovim to hand to test if it's a neovim issue - but strongly suspect it's that or an incompatibility with vimtex and neovim version.

I also saw errors saying tree sitter was doing the highlighting - perhaps worth asking over at vimtex, or seeing if you can try a local neovim at an earlier version to validate if if's neovim at issue (we just invoke a neovim binary that we bundle, so I'm doubtful anything in the vimR code base would be causing this, it's probably just something in neovim / vimtex compatibility which I don't understand).

**Comment by kiryph** [comment]
> I don't use Lazy.nvim but installed via packer and see the same thing.

I do not think this issue is related to the used package manager (packer or lazy).

> I also see the same with an external nvim but have zero idea why. 

Thanks for the confirmation.

> Tried TSUpdate, Packerupdate to see if something was out of sync.

I do not think that an outdated package or tree-sitter grammar is the reason.

> but strongly suspect it's that or an incompatibility with vimtex and neovim version.

This is what I cannot confirm. I am using vimtex for several years and neovim for about 2 years as my daily editor.

This issue only occurs in the new VimR  release with any neovim version. I have tried so far neovim versions 0.9.5, 0.9.0, 0.8.3, 0.8.2:

```
❯ bob list
┌───────────┬─────────────┐
│  Version  │  Status     │
├───────────┼─────────────┤
│  v0.9.0   │  Installed  │
│  v0.8.2   │  Installed  │
│  v0.8.3   │  Used       │
│  v0.9.5   │  Installed  │
└───────────┴─────────────┘
```

> I don't have an earlier neovim to hand to test if it's a neovim issue

One can install diferrent neovim versions with [`bob`](https://github.com/MordechaiHadad/bob). 

> perhaps worth asking over at vimtex,

Maybe I do this. The author of vimtex is always very helpful even though he is on Linux and not macOS.

> I also saw errors saying tree sitter was doing the highlighting 

VimTeX defines classic syntax highlighting groups and is vital for some of its functionality and recommends to disable treesitter for tex files.

> Thus, for people who use Tree-sitter, it is strongly advised to disable
   Tree-sitter highlighting for LaTeX buffers. This can be done with the
   `ignore_install` option for the setup part of `nvim-treesitter`, e.g.: >lua

Full FAQ entry can be found [here](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L6598-L6645).

> or seeing if you can try a local neovim at an earlier version to validate if if's neovim at issue (we just invoke a neovim binary that we bundle, so I'm doubtful anything in the vimR code base would be causing this, it's probably just something in neovim / vimtex compatibility which I don't understand).

I guess I have to debug it better to see from where these errors come.

**Comment by kiryph** [comment]
Sorry, no I do not get the error when pointing to a 0.8.2. The error starts to occur with version 0.8.3.

I will head over to neovim to raise an issue there. But it is still weird that I can only get it when using VimR 0.46.0 with a neovim version larger than 0.8.2. Using any version on the cli does not throw the error.

**Comment by kiryph** [comment]
Sorry for the noise and confusion in this issue.

1. Version 0.8.x are not compatible with the new VimR release. So I could not test them at all.

I did not first notice that in VimR configuration dialog tilde expansion for home directory does not work.

2. I could resolve the issue by **correctly** pointing to a manual installation of neovim 0.9.5

/Users/kiryph/.local/share/bob/v0.9.5/nvim-macos/bin/nvim

![Screenshot 2024-01-11 at 09 08 49](https://github.com/qvacua/vimr/assets/371756/29820a6e-60ae-485c-bee3-11cd914353b0)


So the issue might be related to the nvim binary included in VimR.

Nevertheless I close this issue since I have a solution for me.

**Comment by georgeharker** [comment]
Ok great. I’m so glad there’s a workaround. We can grab a new neovim version when we next release.

**Comment by kiryph** [comment]
I tried it on a fresh new day and unfortunately, the issue persists. I am not sure what was different to the last time I tried it.

I guess it has to be figured out what the error actually throws.

**Comment by p3palazzo** [comment]
I get this warning every time I navigate to a memory-intensive buffer such as a large file or the NERDTree split, both when using the builtin neovim and the Homebrew neovim binary.

**Comment by georgeharker** [comment]
It was my understanding that our build is now vanilla neovim but perhaps we should explicitly set a larger stack size if it is not.

**Comment by chrisfosterelli** [comment]
Stumbled across here from Google. I also seem to get this error a ton if NERDTree is open. I don't use VimTeX.

**Comment by mmerickel** [comment]
I'm running into this regularly. I do use NERDTree and always have it open. I tried using the CLI version of VIM instead of the version shipped with vimR but same issue regardless (albeit seems to take more minutes before it shows up whereas it's usually within a minute with the builtin nvim).

Using system NVIM (`/opt/homebrew/bin/nvim`):
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"
```

Using builtin NVIM:
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by MikaAK** [comment]
I'm also getting this regularly, it's getting quite frustrating as I have to restart my editor randomly or this makes me basically unable to work. Any ideas on how we can set the stack size higher? To confirm what @mmerickel  is saying I do not get this is normal neovim only vimr

**Comment by nclark** [comment]
Has anyone found a combination of older versions of nvim or vimr that stops this? I can't take it anymore. I'd love to keep using vimr but I am going to switch editors soon.

**Comment by mmerickel** [comment]
Anecdotally the error has disappeared for me since I switched to nvim-tree so in my little world of plugins nerdtree feels like it was the primary culprit. Would love to see whatever setting vimr is using be configurable or higher or whatever is required to avoid it occurring though since obviously it never occurred for me via the cli.

**Comment by nclark** [comment]
I went to the [releases](https://github.com/qvacua/vimr/releases) page, scrolled down a bit, landed on VimR-v0.43.0.tar.bz2 for no reason in particular, and switched to that. Things seem to be working for me now (fingers crossed), nerdtree and all. I'll try @mmerickel's approach at some point.

**Comment by nclark** [comment]
> I went to the [releases](https://github.com/qvacua/vimr/releases) page, scrolled down a bit, landed on VimR-v0.43.0.tar.bz2 for no reason in particular, and switched to that. Things seem to be working for me now (fingers crossed), nerdtree and all. I'll try @mmerickel's approach at some point.

Nevermind, that stopped it for like one day.

**Comment by nashalex** [comment]
i've found that downgrading to version 0.44.0 stops this problem. although, it seems that sometimes the `VimR.app` file automatically updates itself after the app is closed and reopened. but reinstalling version 0.44.0 before opening the app seems to "stop" this problem. (although it does get a bit tedious.) 

at this point i just have an unzipped version of `v0.44.0` that i drag into my applications directory before i open the app.

**Comment by lukeasrodgers** [comment]
As others have mentioned in this thread, the problem goes away when I either
- downgrade to v0.44.0; or
- switch NERDtree to nvim-tree
