### ISSUE TITLE
Crash: newest version crash when use cd or lcd

### ISSUE THREAD

**Issue by SolaWing** [qvacua/vimr#1080]
from the crash report, seems there has thread safety issue
[crash.txt](https://github.com/user-attachments/files/16053210/crash.txt)

**Comment by jasonm** [comment]
I see the same / similar issue, consistently reproducible by running `vimr .` and then `:cd .`

[crash2.txt](https://github.com/user-attachments/files/16734150/crash2.txt)

```
$ uname -a
Darwin JasonMorrisonMacbookPro.local 22.6.0 Darwin Kernel Version 22.6.0: Thu Nov  2 07:43:25 PDT 2023; root:xnu-8796.141.3.701.17~6/RELEASE_ARM64_T6020 arm64
```

VimR version: Version 0.48.0 (20240727.082947)

**Comment by jasonm** [comment]
Not sure if related to #1078 but this issue is fixed for me in https://github.com/qvacua/vimr/releases/tag/v0.48.1-20240928.193147 - I think this can be closed @SolaWing @qvacua
