### ISSUE TITLE
Vimr keeps crashing with YouCompleteMe

### ISSUE THREAD

**Issue by gglanzani** [qvacua/vimr#123]
Using YouCompleteMe, Vimr keeps crashing on the .dot completion (typing . after a name, YouCompleteMe begins a lookup of the available attributes).

**Comment by watsnow** [comment]
+1

**Comment by jasonkuhrt** [comment]
I am also having this problem.

**Comment by vfasky** [comment]
+1

**Comment by ldong** [comment]
+1
