### ISSUE TITLE
E117: Unknown function: htmlcomplete#DetectOmniFlavor when opening html files

### ISSUE THREAD

**Issue by pengux** [qvacua/vimr#134]
The problem is in

/Applications/VimR.app/Contents/Frameworks/MacVimFramework.framework/Versions/A/Resources/vim/runtime/ftplugin/html.vim
line 25

**Comment by Krajsnick** [comment]
also getting this error

**Comment by Arthaey** [comment]
same issue

**Comment by ohcibi** [comment]
Have you guys been using the html5.vim from github? The one on vim.org seems to be outdated

**Comment by qvacua** [comment]
I'll have a look into this.

**Comment by kendagriff** [comment]
Also getting this error, even after updating html5.vim.

**Comment by Kermit95** [comment]
When I open the *.md file,  getting this error.

```
Error detected while processing /usr/local/Cellar/vim/7.4.1655/share/vim/vim74/f
tplugin/html.vim:
line   25:
E117: Unknown function: htmlcomplete#DetectOmniFlavor
E117: Unknown function: htmlcomplete#DetectOmniFlavor
```

**Comment by ohcibi** [comment]
@kendagriff @kermit95 you must use the html5.vim from GitHub and not from vim.org

**Comment by ohcibi** [comment]
@qvacua you should close this issue. This isn't a problem of vimr

**Comment by 92hackers** [comment]
@ohcibi 's advice solve my problem,   replace  'html5.vim'  with 'othree/html5.vim' in your .vimrc, and  run :PluginInstall in an opening vim to install the plugin.
