### ISSUE TITLE
open quickly weird behavior 

### ISSUE THREAD

**Issue by jyxt** [qvacua/vimr#136]
Open Quickly doesn't list the file as first even if I typed the full name

see here

https://dl.dropboxusercontent.com/u/69184008/Screen%20Shot%202014-09-19%20at%2012.20.52%20AM.png

**Comment by qvacua** [comment]
The version [0.5.2](https://github.com/qvacua/vimr/releases/download/v0.5.2-26/VimR-0.5.2.tar.bz2) hopefully fixes it.
