### ISSUE TITLE
CTRL-O in insert mode inserts new line

### ISSUE THREAD

**Issue by gibwar** [qvacua/vimr#150]
I'm really liking the direction that VimR is going, but I think I've managed to run in to a bug. When in insert mode, [pressing <kbd>CTRL</kbd>+<kbd>O</kbd>](http://vimdoc.sourceforge.net/htmldoc/insert.html#i_CTRL-O) should allow you to execute one command as normal mode and then return you back to insert mode. Instead, when pressing <kbd>CTRL</kbd>+<kbd>O</kbd> when in insert mode instead inserts a new line where the cursor is and then enters the insert mode.

I confirmed this issue with having no `~/.vim*` files and no plugins being loaded from `~/.vim/`. I also confirmed that the version of Vim bundled with OS X 10.10 does not exhibit this issue. I have included a GIF below demonstrating the issue. You can see the change to the special mode when the bottom line changes from `-- INSERT --` to `-- (insert) --`. I then press <kbd>ESC</kbd> twice to return to normal mode and then <kbd>u</kbd> to undo the change.

![vvvayb](https://cloud.githubusercontent.com/assets/1493527/5425108/482572dc-82c6-11e4-9ebb-c1752ea88cd8.gif)

**Comment by firedev** [comment]
Hmm I wanted to report that `Ctrl-w-o` doesn't work and I have to use `Ctrl-w o` instead, but now I see that it's `Ctrl-o` bug in fact.
