### ISSUE TITLE
Open Quickly Blacklist

### ISSUE THREAD

**Issue by jpotterm** [qvacua/vimr#151]
Open Quickly has tons of potential but is a lot less useful without being able to ignore files. For example, if a project is under version with mercurial, there will be a lot of files under the .hg directory that have the same name as the ones you're searching for. Or if it's a python project there will be a .pyc file that shows up for every python file you're looking for. I imagine this is on your todo list but I didn't see an issue tracking the progress.

It could probably use the `wildignore` setting like the file browser does.

**Comment by qvacua** [comment]
Try http://taewon.de/snapshots/VimR-20150116-2052.tar.bz2

**Comment by jpotterm** [comment]
:+1: That's perfect, thanks!
