### ISSUE TITLE
Neovim

### ISSUE THREAD

**Issue by danielepolencic** [qvacua/vimr#16]
Hi,

I really like the idea behind vimr. I was wondering if it wouldn't be easier to play with [`neovim`](https://github.com/neovim/neovim) and [create an UI on top of it](https://github.com/neovim/neovim/wiki/Introduction#gui), rather than fiddling with MacVim.

I'm not an expert, so I don't know if this is feasible/convenient. What do you think?

**Comment by Stiivi** [comment]
There is a new OS X UI project that uses neovim: [NeoVim.app](https://github.com/rogual/neovim-dot-app). If the projects have similar goals in mind, it might be worth considering to merge the effort and experience.

**Comment by gglanzani** [comment]
I would personally love and welcome a merge with Neovim-dot-app. It is really becoming stable as to "a geek can use it everyday".
