### ISSUE TITLE
Improve open quickly blacklist

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#165]
enable shell pattern

**Comment by subwindow** [comment]
How do you get Open Quickly to blacklist anything? It currently doesn't abide by wildginore, afaict. This is blocking me from using VimR, currently- Open Quickly indexes tens of thousands of files in wildignore, including git branches and tmp files.

**Comment by qvacua** [comment]
Hi, look at <https://github.com/qvacua/vimr/wiki/Open-Quickly-Behavior#ignore-pattern>. :)

**Comment by subwindow** [comment]
Unfortunately this does not really work. It prevents the files from
being selected, but it does not prevent the files from being indexed.
There are 63,000+ files in my working directory, the vast majority of
which are ignorable. Therefore, when doing "Open Quickly" a search takes
4-5 seconds to filter out the files that match the ignore pattern (every
time Open Quickly is used).

Tae Won Ha wrote:

**Comment by qvacua** [comment]
I use `fnmatch` function to filter the ignorables and as I applied this function to every file in the folder, it took longer than just to scan everything and filter when the user starts to type. I can probably make it faster when I restrict the usable patterns. Let me think about this...
