### ISSUE TITLE
Font size default?

### ISSUE THREAD

**Issue by bortels** [qvacua/vimr#166]
I don't see any way to set a default font size. On my 5k iMac, the font in the editing window is uncomfortably small. I can increase it with Apple-+ (which increases the window font size, but not the sidebar font size), but when I quit and restart, it remembers the window size, but not the font size.

**Comment by qvacua** [comment]
Well, there's no GUI way of setting the default font size. You should do it in `.vimrc`, cf for example this [page](http://stackoverflow.com/questions/17508542/how-to-set-the-default-font-size-on-vim)

**Comment by bortels** [comment]
Ah - that works. I didn't even realize it was an option - I've always set the terminal font size and vim just followed that.

**Comment by qvacua** [comment]
Yes, in the terminal Vim does not have a choice, but to follow the rules of the outer universe. :smile:
