### ISSUE TITLE
Building vimr

### ISSUE THREAD

**Issue by kasajian** [qvacua/vimr#171]
I am curious if it's desirable for the project to get feedback related building the code.   For example, if I run into questions about building vimr, is that the kind of thing that's worth bringing up somewhere?  If so, what's a good place to have that discussion?  I ask because it's not related to using vimr, but building it from source.

Thank you.

**Comment by qvacua** [comment]
You can create an issue or post to the [mailing list](https://groups.google.com/forum/#!forum/vim-refined).

**Comment by ashkanr** [comment]
Same here. Unfortunately there is no activation applescript for file browser so I could not hack it by:

```
osascript -e '
tell application id "com.qvacua.VimR"
    activate
    reloadFileBrowser # This DOES NOT exist.
end tell
'
```
