### ISSUE TITLE
Would like the ability to set the root for the folder tree

### ISSUE THREAD

**Issue by kasajian** [qvacua/vimr#172]
If I want to use vimr in a presentation or a screencast, I wouldn't be able to because i wanted to show the directory structure of my code, but I don't want everyone to see the other folders on my hard disk.

It would be useful to have a way to set the root of the folder tree.  One way to do it is how Text Wrangler does it, via a drop-down list at the top of the directory tree.   Brackets and Atom have various different ways to do the same.

**Comment by ptrin** [comment]
+1. I installed VimR and was excited to use it but I find it odd that I can't navigate into a folder so that I'm only looking at the files for a particular project.

**Comment by ptrin** [comment]
@kasajian Actually it looks like you can just use the :cd command and the folder tree will update to that dir.

**Comment by Sh4pe** [comment]
@ptrin is right, you can use `:cd` for that. I think this issue can be closed.
