### ISSUE TITLE
Shift-Cmd-L changes window width

### ISSUE THREAD

**Issue by jcw** [qvacua/vimr#174]
When typing shift-cmd-L several times in a row, the width of the entire window decreases further and further. When doing this is rapid succession, the width sometimes increases or decreases very erratically.

-jcw

**Comment by jcw** [comment]
May be related to #167 which also happens (Mac OSX 10.10.2).

**Comment by stephanedemotte** [comment]
+1

**Comment by jmlacroix** [comment]
This also happens to me with vimr 0.8.0 (32) on OS X Yosemite 10.10.4.
