### ISSUE TITLE
Short-cut like ⌘V with CJK input method crashes VimR

### ISSUE THREAD

**Issue by kennytm** [qvacua/vimr#176]
Reproduction steps:

1. Add and switch to the Japanese Input Method (in  → System Preferences → Keyboard → Input Sources)
2. Start VimR
3. Press <kbd>⌘</kbd>+<kbd>V</kbd>

Problem:

* VimR crashes instead of pasting the text at step 3.

Crash log:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff90977ce9 CFDataGetBytePtr + 25
1   com.qvacua.VimR               	0x00000001094a6d66 -[VRApplication charsStrippingModifiers:] + 105
2   com.qvacua.VimR               	0x00000001094a6b60 -[VRApplication sendEvent:] + 172
3   com.apple.AppKit              	0x00007fff8ebcc608 -[NSApplication run] + 711
4   com.apple.AppKit              	0x00007fff8ebb7a14 NSApplicationMain + 1832
5   libdyld.dylib                 	0x00007fff920265c9 start + 1
```

(Crash on [this line](https://github.com/qvacua/vimr/blob/9021c0e5e8fe3cb5b6ace7cc6d080ac06e1475cc/VimR/VRApplication.m#L114). The `kTISPropertyUnicodeKeyLayoutData` property returns NULL.)

The same happens with Korean and Chinese input methods.

**Comment by qvacua** [comment]
Oh, that's not good... I'll try to fix it asap (probably next week, since this week is too crowded..)

**Comment by qvacua** [comment]
will be released today or tomorrow :smile:
