### ISSUE TITLE
Cant type curly brackets nor the at symbol

### ISSUE THREAD

**Issue by lmartins** [qvacua/vimr#179]
Let me say upfront this isn't a VimR issue, it happens also on MacVim but not on shell vim. 
I am however hoping that someone here who has experience with Vim could help me solve this problem, since it prevents me from using Vim altogether.

Im using a Portuguese layout keyboard and when I type ALT+2 (in my keyboard it's how I type @) i get the 2 exponent symbol. For curly brackets I usually type ALT+Shift+8 / 9, giving me { and }, in VIM instead I get small quote like symbol and the © symbol.

Can any anyone help me out this please.
Thanks.

**Comment by qvacua** [comment]
I'll look into it.

**Comment by lmartins** [comment]
Today on my work machine, with a similar setup, i've confirmed this doesn't happen, so I don't think it's worth your time checking this, but thanks for step up for this.
Cheers.
