### ISSUE TITLE
Indent mappings work everywhere except VimR

### ISSUE THREAD

**Issue by lmartins** [qvacua/vimr#181]
Hi,

I have the following mappings for indentation configured and working everywhere but for some reason they don't work with VimR:

```
"-----------------------------------------------------------------------------
" INDENTATION
"-----------------------------------------------------------------------------

nnoremap <D-[> <<
nnoremap <D-]> >>
inoremap <D-[> <esc><<A
inoremap <D-]> <esc>>>A
xnoremap <D-[> <gv
xnoremap <D-]> >gv

```

Any ideia on why this is happening?

**Comment by qvacua** [comment]
It's due to [this](http://stackoverflow.com/questions/9450905/how-to-bind-vim-through-tmux-to-cmd-key/9451636#9451636). Currently, I don't have a good idea to fix this. Let me think about it.
