### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by kzahedi** [qvacua/vimr#182]
First of all, thanks for the great work!

I used NERDTree quite heavily in MacVim. There is one feature that I use frequently in NERDTree that is missing in the FileBrower, which is the m r command to open Finder. Finder is opened such that the file under the cursor (in NERDTree) is selected. This is quite handy, if you quickly want to open a file with e.g. Preview.

Cheers,
Keyan

**Comment by qvacua** [comment]
Yes, that's one of the basic features file browsers in editors or IDEs have and which is missing in VimR. It'll find its way to VimR. :)

**Comment by lsd** [comment]
Thanks for the excellent work @qvacua 

I use `m r` and `m o` in NERDTree as well. Maybe I'll try to write and contribute this feature in a few days if I get a chance. Also being able to make the current dir under cursor the new cwd/root (`C` in NERDTree) Is this currently possible in VimR?
