### ISSUE TITLE
Loading VIMRC from ~/.config/vim/vimrc

### ISSUE THREAD

**Issue by nfarrar** [qvacua/vimr#184]
I wrote up a plugin (works with vim) this morning to make my vim respect the XDG defaults (https://github.com/nfarrar/xdg.vim).  In my shell config, I set `export VIMINIT='let $MYVIMRC="~/.config/vim/vimrc" | source $MYVIMRC'` to bootstrap my vimrc from `/.config/vim/vimrc`.

Unfortunately (should have thought of this sooner), vimr obviously doesn't respect my shell config. I looked through the preferences but didn't see a way to to set `$VIMINIT` or an alternate location to read `vimrc` from. Any suggestions?

**Comment by qvacua** [comment]
Hm... I think you could set the environment variables, cf. http://www.dowdandassociates.com/blog/content/howto-set-an-environment-variable-in-mac-os-x-launchd-plist/
