### ISSUE TITLE
Cannot change default opening behavior

### ISSUE THREAD

**Issue by alexbepple** [qvacua/vimr#189]
I cannot change the default opening behavior. In the Preferences dialog, I cannot select any other option:
<img width="406" alt="screen shot 2015-07-30 at 20 54 09" src="https://cloud.githubusercontent.com/assets/159355/8992217/b59fe40a-36fd-11e5-85ab-30e4b279245a.png">
<img width="425" alt="screen shot 2015-07-30 at 20 54 14" src="https://cloud.githubusercontent.com/assets/159355/8992225/b953c076-36fd-11e5-9acd-0ba490c4e105.png">

I also tried changing the value to "in-current-tab" (found in `VRUserDefaults.m`) directly in `~/Library/Preferences/com.qvacua.VimR.plist`. But to no avail. VimR ignored this and reset it to "in-new-tab".

VimR Version 0.7.1 (29)
OS X Version 10.10.4

**Comment by qvacua** [comment]
I'll have a look.

**Comment by qvacua** [comment]
This should fix it. I'll build a release as soon as I have set up the build virtual machine (it got screwed up...)

**Comment by alexbepple** [comment]
Thanks.
