### ISSUE TITLE
New Tab (+) button does not work

### ISSUE THREAD

**Issue by bambu** [qvacua/vimr#193]
Normally I do `Cmd-T` for a new tab. I noticed the (+) tab button and decided to click it.  It does not open a new tab and outputs the error: `E16: Invalid Range: 999tabnew`. 

Tried it in MacVim and a new tab opens as would be expected.

**Comment by juicejuice** [comment]
Yes, instead of :999tabnew the Ex command to use is :$tabnew. I wonder if qvacua is open to pull requests :)

**Comment by qvacua** [comment]
PRs are welcome :smile:
