### ISSUE TITLE
Feature request: dark mode

### ISSUE THREAD

**Issue by juicejuice** [qvacua/vimr#194]
With Yosemite, Mac OS now offers a dark mode. In addition, my Vim config (and many others I believe) will use a dark background. It would be great if there was a configuration option to allow the bits of UI "chrome" added by VimR to be dark coloured. I'm thinking mainly of the file browser.

**Comment by lsd** [comment]
If somebody wants to take this on, .. `NSString *mode = [[NSUserDefaults standardUserDefaults] stringForKey:@"AppleInterfaceStyle"];` mode would be `nil` or `@"Dark"` if dark is enabled in user prefs.
