### ISSUE TITLE
opening remote files 

### ISSUE THREAD

**Issue by palominogallo** [qvacua/vimr#196]
I tried to open remote files using vimr
1) vimr scp://user@server//path 
it is not opening the file or tree, it believes is a local directory ( no remote)

2) Open vimr, then using  :e scp://user@server//path, opens the netrw directory list, but when I tried to open a specific file from that list, it opens the file but the file is empty .

**Comment by xamoc** [comment]
+1 with vimR 0.8 on El Capitan
