### ISSUE TITLE
R-programming language?

### ISSUE THREAD

**Issue by jubilatious1** [qvacua/vimr#200]
Hello, does this repository bear any relationship to the R-programming language (www.r-project.org) ?

Specifically trying to find out if this repo is related at all to the "vim-r" project done by Dr. Thomas Girke at UCRiverside integrating the R-programming language with Vim and Tmux:

http://manuals.bioinformatics.ucr.edu/home/programming-in-r/vim-r

**Comment by ldong** [comment]
@jubilatious1 I dont think so,Vim`R`  r stands for  Vim **Refined**

**Comment by lsd** [comment]
@jubilatious1 VimR has nothing to do with R lang.

**Comment by jubilatious1** [comment]
Vim is (of course) a well-known offshoot of the Vi editor, originally written by Bill Joy. 
R is a well-known programming language for data manipulation as well as graphical and statistical analysis. R was written by Ross Ihaka and Robert Gentleman, inspired by the IBM "S" language written by John Chambers. R in its earlier incarnations was often referred to as "GNU-S".  

So, if I understand correctly, this repository has **nothing** to do with the R-programming language, and **nothing** to do with the following links:

https://www.r-project.org
http://blog.revolutionanalytics.com/2015/03/some-thoughts-on-vim.html
http://manuals.bioinformatics.ucr.edu/home/programming-in-r/vim-r
https://github.com/vsbuffalo/devnotes/wiki/Vim,-R,-and-Tmux:-Minimal-Configuration
http://blog.jom.link/install-last-version-of-vim-r-plugin-for-macvim.html
https://dzone.com/articles/working-r-and-vim
http://www.lornajane.net/posts/2013/working-with-r-and-vim
http://stackoverflow.com/questions/9549005/vim-for-python-and-r-scripting-in-screen-or-not
http://jeromyanglim.blogspot.com/2011/01/reasons-for-transitioning-to-vim.html
https://brokeringclosure.wordpress.com/2010/12/02/r-with-vim/
http://www.compmath.com/blog/2010/12/r-with-vim-on-mac-os-x/
https://www.reddit.com/r/vim/comments/2n93ee/vim_as_an_r_ide_is_it_possible/
http://vim.wikia.com/wiki/Script:List_of_R_Project_scripts
http://www.vim.org/scripts/script.php?script_id=1048
http://www.vim.org/scripts/script.php?script_id=2163
http://www.vim.org/scripts/script.php?script_id=2628
http://www.vim.org/scripts/script.php?script_id=2991
http://www.vim.org/scripts/script.php?script_id=1741
http://www.vim.org/scripts/script.php?script_id=2104
http://www.vim.org/scripts/script.php?script_id=2177
https://github.com/vim-scripts/Vim-R-plugin
https://github.com/jcfaria/Vim-R-plugin
https://github.com/jalvesaq/VimCom
http://binfalse.de/assets/media/wp-content/uploads/2010/12/vim-r-plugin-101217.html
https://cran.r-project.org/web/packages/lintr/README.html
http://yihui.name/knitr/demo/editors/

Just clarifying for other Github users who might stumble onto this repo (like I did). Thanks.
