### ISSUE TITLE
Disable spell checking

### ISSUE THREAD

**Issue by ngocphamm** [qvacua/vimr#203]
Just want to know how to disable spell checking for text inside VimR. Normally we have a sub menu "Spelling and Grammar" under Edit, but not with VimR.

Thanks, everyone :smile: 

![screenshot 2015-12-13 10 06 27](https://cloud.githubusercontent.com/assets/395123/11767598/7a59a5fe-a181-11e5-9c8d-727ae3a5ced1.png)

**Comment by lsd** [comment]
In vim, use `:set nospell` or `:set spell!` to toggle it on/off

In my `~/.vimrc` I have `nnoremap \ts :set spell!<CR>` which allows me to quickly toggle spell check on/off in NORMAL mode by hitting the keystrokes `\ts` in succession.

Another example: Map `F6` to toggle spell check: `nnoremap <F6> :set spell!<CR>`

**Comment by ngocphamm** [comment]
Sweet! So noob that I didn't realize there's option in Vim itself. Thank you!
