### ISSUE TITLE
Full screen rvim fails to open new files

### ISSUE THREAD

**Issue by pqnet** [qvacua/vimr#209]
### Step to reproduce:

 - open rvim
 - make it fullscreen by clicking on the green button
 - press cmd-o or select the "open" menu item from the "file" menu
 - select a different folder than the one currently opened
 - click "open" button

### What was expected:

A new screen should be opened with a window relative to the new directory

### What happened:

The new directory's window is opened in the same screen as the previously opened window.
The window partly covers the old one, both are unresponsive to user input (the app must be quit using cmd-Q or menu).

Pressing cmd-O or the corresponding "open" menu item does not show the "open" dialog again.
The problem can always be reproduced with the above steps on my machine.

### Version information:

- rvim v0.8.0
- OS X El Capitan 10.11.5

**Comment by lsd** [comment]
I can't replicate this on `VimR version 0.8.0 (32)` & `El Capitan 10.11.5`

After steps to reproduce as stated above I get the expected result as stated above.
