### ISSUE TITLE
Improve cursor rendering

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#214]
Our current cursor rendering is very rudimentary. It renders too often and too ugly.

* Minimize `setNeedsDisplayInRect()`-calls for the cursor
* Try not to use `NSRectFillUsingOperation()` with `.CompositeDifference`, then we can get rid of `NSRectFill()`s for the background.

A good test would be to go fullscreen, let `top` run in a split and see whether the cursor flickers.

**Comment by qvacua** [comment]
Using the foreground color to draw the cursor with `.CompositeDifference`. We now only draw the background when the background color differs from the default background color.

**Comment by sfcgeorge** [comment]
When pressing down key to move the cursor down, when it reaches the bottom of the buffer the buffer starts to scroll as expected, but the cursor displays flickering to the top.
