### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by weaksauce** [qvacua/vimr#219]
It would be nice to have a roadmap of features that you'd like to see implemented to encourage outside contributors. Basically a "vision" of where the project should go. As an aside, I like the decision to use neovim as the backing vim engine.

**Comment by qvacua** [comment]
Will do 😄. I'll first sketch the rough roadmap of features in the README and add detailed tasks (issues) bit by bit.

**Comment by qvacua** [comment]
@weaksauce RFC: I've updated the README. If ok, please close the issue :D

**Comment by weaksauce** [comment]
looks like a good start... thanks! I'll close this now.
