### ISSUE TITLE
Implement Cmd+N where N = 1,...,9 to select N-th tab in the current window

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#230]

**Comment by qvacua** [comment]
not doing it (or change the shortcut to sth else...)

**Comment by kyleholzinger** [comment]
Question about this, there's currently a [section in the wiki](https://github.com/qvacua/vimr/wiki/VimR-MacVim#select-n-th-tab-key-bindings) that suggests the exact opposite of this, however I'm unable to use the cmd+n shortcut to select a tab. Is this implemented or is the documentation wrong? In any case, awesome job on vimr! I'm loving it so far.
