### ISSUE TITLE
Failed to open document in command line -- vimr

### ISSUE THREAD

**Issue by ray-x** [qvacua/vimr#231]
I built  latest version from master today.  but I do not know how to open a document with command line. I tried to use "open -a VimR.app test.py" but the vimr complain about could not open python script type. I tried other types all end the same error message : The document xxxx could not be opened, VimR cannot open file in the xxx format.
I try to use /Applications/VimR.app/Contents/MacOS/VimR but I could not pass the filename to vimR. So I had to use nerd tree to open files. 
I did not see documents regarding the vimr usage. :-(

**Comment by qvacua** [comment]
The `master` version of VimR is in a very early stage; we just got started 😄. For example it does not _yet_ have the correct entry in `Info.plist` file such that OSX thinks it can handle various file types. To be able to open files from command line we have to write a separate command line tool as we did for VimR-MacVim. I'll create an issue to implement this command line tool and close this issue.

**Comment by qvacua** [comment]
Will be fixed with GH-232.
