### ISSUE TITLE
Create a command line tool `vimr` to open files from command line.

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#232]
Find out the easiest way to do this; otherwise we have to use AppleScript as we did for VimR-MacVim...

* Probably we can just pass through the arguments to neovim: see `run_neovim()` in `server_ui.m`. However, then, we probably should filter out some of neovim's command line options.
* Probably we should write the command line tool in a scripting language bundled by default by OSX (or bash).

Abusing the custom URL scheme, eg `vimr://open?files=[abc,def]&arg1=value1&arg2=value2`, is probably the simplest way to do it.

**Comment by romaninsh** [comment]
Please include option to always open in new window as well as pass current working directory. This makes it super-easy to integrate with "Alfred"

```
query="{query}"
cd $query
/usr/local/bin/gnvim
```

**Comment by romaninsh** [comment]
It appears what I want can be easily achieved with `open -n`, so no issue.

**Comment by romaninsh** [comment]
Related: https://github.com/qvacua/vimr/wiki/Command-Line-Tool (probably outdated).

If it's ok, once I get vimr to build, i'd like to contribute a command-line launcher.

**Comment by fiveNinePlusR** [comment]
Have you looked at the way macvim does it?

**Comment by Snazzyham** [comment]
works in mac os by adding `alias vi="open -a 'VimR'" ` to your `.bash_profile`. Then you can use `vi .` to open your whole dir in VimR or `vi filename.js` to open an individual file

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160825.1016-61 and https://github.com/qvacua/vimr/wiki#command-line-tool
