### ISSUE TITLE
VimR conflict with plugins (airline, FZF)

### ISSUE THREAD

**Issue by unrealhoang** [qvacua/vimr#235]
I just downloaded VimR Version 0.9.0-SNAPSHOT-20160804.2342 (45) and try to make it run with my current neovim configuration. Below are some errors that I spotted.

On Startup, It shows that there is problem with airline.
<img width="1118" alt="screen shot 2016-08-08 at 1 25 05 am" src="https://cloud.githubusercontent.com/assets/1218094/17464393/79206ffa-5d07-11e6-8aff-63da98ca0e40.png">

When I try to use `:FZF` the following error throws up.
<img width="1114" alt="screen shot 2016-08-08 at 1 25 30 am" src="https://cloud.githubusercontent.com/assets/1218094/17464382/1a8f8c78-5d07-11e6-8e6a-c0dc7de54a10.png">

I suspect that VimR may run neovim with some specific parameters that cause conflict with the plugins.

**Comment by qvacua** [comment]
Oh, I did not know that some plugins like `airline` rely on `lines` option. I disabled `lines`, `column`, etc. since I want to prevent resizing via command line... Well, OK, I'll have to find another way...

**Comment by qvacua** [comment]
I re-enabled the `lines` and `columns` option: [new snapshot](https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160808.1925-48).

I checked that `fzf` works. `airline`, however, does not completely work, the colors of the arrows (`<`) are wrong. I don't know yet why and I've created GH-236 (thus closing this issue). At least now VimR launches with `airline`...

**Comment by unrealhoang** [comment]
Thank you for very fast resolving, mine works perfectly fine now.
