### ISSUE TITLE
Scroll sensitivity for mouse scroll wheel too low

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#237]
Trying to scroll using the hardware mouse scrollbar, content is moving too slow compared to other apps.

![vim-scroll](https://cloud.githubusercontent.com/assets/453929/18955103/d68331fe-864d-11e6-8429-b44440a6f136.gif)

**Comment by qvacua** [comment]
Since I do not use mouse, but only trackpads, I have not tested this with a mouse. Let me see what I can do... 😄

**Comment by romaninsh** [comment]
Thanks! Really appreciate your commitment.

**Comment by romaninsh** [comment]
If you need me to build and tweak a value then submit a PR, I can do that.

**Comment by qvacua** [comment]
The code for scrolling is yet kinda (very) messy... You could have a look at `scrollWheel(event: NSEvent)` in `NeoVimView.swift`. There, I use some heuristics to tune the scrolling kinda OK on my Mac and trackpads... 😳 It could get messier when we have to tweak for two different devices w/o using gesture related events. `NSEvent.phase` could be sufficient for this, but I haven't looked into that.

**Comment by romaninsh** [comment]
Update: I did try to mess with the file you specified, but it didn't affect the sensitivity.

**Comment by romaninsh** [comment]
![vim-scroll](https://cloud.githubusercontent.com/assets/453929/18955070/bb0cb3b4-864d-11e6-8c88-420823c68df9.gif)

**Comment by romaninsh** [comment]
VS vim in terminal.

![vim-scroll](https://cloud.githubusercontent.com/assets/453929/18955192/3ebae528-864e-11e6-849e-04d85dd5455b.gif)

**Comment by qvacua** [comment]
Could you please try the [issue/237-scroll](https://github.com/qvacua/vimr/tree/issue/237-scroll) branch? If ok, I'll build a snapshot.

**Comment by qvacua** [comment]
I built it anyway 😃. Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161112.1708-125

**Comment by qvacua** [comment]
Please re-open if not ok 😉

**Comment by apazzolini** [comment]
Hi @qvacua, I'm not the original issue submitter, but I can confirm it now scrolls 3 lines per wheel click with the new snapshot.

However, this is still not ideal. In terminal neovim, I can [map the scroll wheel](https://github.com/neovim/neovim/blob/master/runtime/doc/scroll.txt#L255-L258). Would it be possible to keep this feature in VimR? Or perhaps allow picking the number of lines via a GUI config variable?

**Comment by qvacua** [comment]
@apazzolini probably making it configurable is the best option for VimR... See GH-344.

**Comment by romaninsh** [comment]
With snapshot 196 mouse scrolling now is too fast. Perhaps some earlier hot-fix should be reversed now?

**Comment by romaninsh** [comment]
https://github.com/qvacua/vimr/blob/747c7ba6b58f98752fe95b5e841fcfd8ce29e780/SwiftNeoVim/NeoVimView%2BMouse.swift#L39
