### ISSUE TITLE
Mac+P re-binding

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#238]
I'm using Ctrl+P. Reaching fro Ctrl puts a lot of stretch of left thumb, so my binding is changed:

```
nmap <D-p> :CtrlP<cr>
```

On VimR - this defaults to Print. Is there any way to avoid that?

(p.s. great job on NeoVim integration! Almost ready to drop neovim-dot-app)

**Comment by qvacua** [comment]
Oh, yes, that should be easily possible (I think..). I'll just have to remove the print menu item from the main menu. Will do.

**Comment by qvacua** [comment]
It works with [0.9.0-SNAPSHOT-20160809.1910-49](https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160809.1911-49).
