### ISSUE TITLE
The font rendering seems to be thinner than other apps

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#239]
Currently only family and "size" can be selected. I'm using DejaVu Sans Mono for Powerline and default typeface looks rather "thin". Here is screenshot from neovim-dot-app:

![screen shot 2016-08-09 at 16 18 23](https://cloud.githubusercontent.com/assets/453929/17521902/ff1b3e14-5e4c-11e6-8159-762b04956a69.png)

Next screenshot from Vim-R

![screen shot 2016-08-09 at 16 20 20](https://cloud.githubusercontent.com/assets/453929/17521974/3bfa5fea-5e4d-11e6-84c5-9fadef3c0d0a.png)

(compare in 100% zoom)

**Comment by qvacua** [comment]
The typeface should be selectable when present, eg for InputMonoCompressed-* see

![untitled](https://cloud.githubusercontent.com/assets/460034/17524453/fbdd9a1e-5e5e-11e6-97c9-f10ab2237e79.png)

We're using MacVim's string drawing code using CoreText which could render things slightly differently from its Cocoa counterpart...

**Comment by romaninsh** [comment]
![screen shot 2016-08-10 at 11 19 55](https://cloud.githubusercontent.com/assets/453929/17550334/6255bdd4-5eec-11e6-860f-52a2e1cbc3cf.png)

I compared with the terminal too:

![screen shot 2016-08-10 at 11 23 56](https://cloud.githubusercontent.com/assets/453929/17550457/fe133e90-5eec-11e6-97df-8ae8feb5c414.png)

font does seem a bit lighter. 

Here is a font link: https://github.com/powerline/fonts/tree/master/DejaVuSansMono

**Comment by telemachus** [comment]
I just came to open the same issue. I'm not yet sure that I dislike the effect, but I've tried a handful of fonts, and all of them look thinner and "lighter" in vimR than in, say, Terminal.app (with all the same settings).

E.g., here's vimR:

![screen shot 2016-09-16 at 9 11 47 am](https://cloud.githubusercontent.com/assets/62958/18587008/d46dfb5c-7bed-11e6-9add-3e670684dfd0.jpg)

And here's neovim in Terminal.app:

![screen shot 2016-09-16 at 9 11 52 am](https://cloud.githubusercontent.com/assets/62958/18587004/c3cb7630-7bed-11e6-8433-d3200a1c84b9.jpg)

**Comment by rolandcrosby** [comment]
Not sure if this should be a separate issue - but on a non-Retina display connected to my Retina MacBook Pro, VimR appears to not use subpixel font smoothing, which makes text look very muddy.

**Comment by qvacua** [comment]
Could you guys please try https://github.com/qvacua/vimr/releases/tag/snapshot/v0.10.0-SNAPSHOT-20161024.2203-114 and give me feedback?

**Comment by rolandcrosby** [comment]
This build looks better (and appears to be using subpixel rendering) -- thanks!

**Comment by qvacua** [comment]
Try the latest snapshot which uses font smoothing on both retina and non-retina displays.
