### ISSUE TITLE
Option to use system-wide nvim

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#240]
Vim-R currently bundles NeoVim. How about option to use 'nvim' that is already installed?

(i'm not sure if that's good or will cause more harm instead, with older nvim versions)

**Comment by qvacua** [comment]
I'm afraid that this is not possible since we include NeoVim as static library. Additionally, we [patched](https://github.com/qvacua/neovim/commits/master) NeoVim such that certain things work in VimR.

I'll close this issue.

**Comment by romaninsh** [comment]
That's fine. Thanks!
