### ISSUE TITLE
Add an option `gui_vimr` to use in `init.vim`

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#241]
* Like in GH-101

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160818.2038-57

**Comment by mfojtik** [comment]
@qvacua this seems to be broken in the latest snapshot, having:

```
if has("gui_vimr")
  colorscheme foo
endif
```

seems to be ignored during startup.
