### ISSUE TITLE
Set `$PATH` correctly if possible

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#243]
When executing commands, the $PATH variable is not set correctly.

```
!echo $PATH
```

I have "brew" installed and it adds /usr/local/bin into PATH, but VIM-R does not look there.

---

* Set `PATH` correctly when starting NeoVimServer
* Use for instance `MMAppController.executeInLoginShell:arguments:` of MacVim.

**Comment by qvacua** [comment]
Released in https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160818.1757-56
