### ISSUE TITLE
Click dock icon to open new window

### ISSUE THREAD

**Issue by satyapr93** [qvacua/vimr#244]
> When there is no VimR window open,, clicking on dock icon doesn't open new window.

* Add a preferences entry (General -> ...) to enable or disable this.
    - Turn on/off when launching
    - Turn on/off on reactivation
* Turn both on by default.

**Comment by romaninsh** [comment]
That would be very counterintuitive. If you click safari, MacVim none of them open a new window.

**Comment by vol0da** [comment]
Actually Safari does that, also Atom, Sublime and many others.
I would say it's a pretty common behaviour across mac apps.

**Comment by qvacua** [comment]
By default clicking the dock icon of a document based App should open a new document window when there's no open (document) window. However, most of the time, I use a text editor to edit existing files, therefore, I also want to be able to turn it off. 😀

**Comment by qvacua** [comment]
I wish Swift had generics convariance...

**Comment by romaninsh** [comment]
Oh i didn't notice "when no windows present" , my apologies. yes i agree.
