### ISSUE TITLE
Handle unknown options in `init.vim` gracefully

### ISSUE THREAD

**Issue by satyapr93** [qvacua/vimr#245]
`set antialias     " set antialising on`

<img width="690" alt="screen shot 2016-08-11 at 10 49 43 am" src="https://cloud.githubusercontent.com/assets/3058630/17579391/760922c8-5fb2-11e6-8c5a-0da396071d79.png">

**Comment by qvacua** [comment]
`antialias` is not available in NeoVim. However, VimR does not handle an unknown option in `init.vim` gracefully. This should be improved.

**Comment by satyapr93** [comment]
didn't know about that.

**Comment by qvacua** [comment]
With 832b05f the errors during the sourcing of `init.vim` will be ignored by VimR. Think about a nice way to show the user in GH-251.
