### ISSUE TITLE
Open file with VimR

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#250]
It should be possible to right-click a file and select it to be opened with VimR

![screen shot 2016-08-13 at 15 12 04](https://cloud.githubusercontent.com/assets/453929/17643645/4fc2058c-6168-11e6-87b0-1699bf8a32a7.png)

Errors with: `The document “Async.swift” could not be opened. VimR cannot open files in the “Swift Source Code” format.`

![screen shot 2016-08-13 at 15 12 17](https://cloud.githubusercontent.com/assets/453929/17643648/59d3ffa8-6168-11e6-80e7-d0287f0679e6.png)

**Comment by qvacua** [comment]
From 0.9.0-SNAPSHOT-20160812.1638-50 (GH-228) on VimR registers as an editor for the UTI `public.data` which includes almost everything. I could open Swift files using "Open With... -> Other...".

**Comment by qvacua** [comment]
Does it work with the new snapshots? If yes, please close the issue 😄.

**Comment by krid78** [comment]
I was about opening the same issue. But with latest snapshot (VimR-0.9.0-SNAPSHOT-20160819.0745-58) it works.
I tested it with .markdown files, for wich it did not work in earlier versions.

**Comment by qvacua** [comment]
> Actually, it opens two windows. Could it open two buffers instead?

See GH-254.

Otherwise closing this issue.
