### ISSUE TITLE
Cursor drawing is broken

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#252]
* culprit: feef6091d9f441537ad9b340cc05ad7db8eeed0c

**Comment by romaninsh** [comment]
Not sure if related or worth reopening, but cursor is hardly visible now:

![screen shot 2016-08-22 at 06 28 33](https://cloud.githubusercontent.com/assets/453929/17844452/b4a9d496-6831-11e6-9aaa-ce6372f462f2.png)

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160825.1535-62 ... May be better..

**Comment by qvacua** [comment]
Seems to be fixed... Please reopen if not fixed.

**Comment by mgee** [comment]
My cursor is also black and slightly translucent. It seems VimR is ignoring the `Cursor` highlight group from the colorscheme. Is there a way to change that?

**Comment by qvacua** [comment]
No, not yet. I'm afraid that the current cursor drawing is very rudimentary and buggy. It should be completely overhauled. Created GH-275.
