### ISSUE TITLE
Initialise screen size incorrect

### ISSUE THREAD

**Issue by ray-x** [qvacua/vimr#258]
The text field area only occupied a small portion of the VimR window.  After resize the windows, text field will fill the entire window.

<img width="551" alt="screen shot 2016-08-22 at 10 30 43 am" src="https://cloud.githubusercontent.com/assets/1681295/17840867/1640eb64-6854-11e6-9665-8e55dc5bdb88.png">

**Comment by qvacua** [comment]
Which version of VimR are you using?

**Comment by qvacua** [comment]
This is probably due to invalid options set in `init.vim`. Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160825.2258-64

**Comment by ray-x** [comment]
The release version works well, thanks!
