### ISSUE TITLE
guifont setting is being ignored in VimR-MacVim

### ISSUE THREAD

**Issue by TravisDart** [qvacua/vimr#259]
I'm using VimR 0.8.0. My ~/.vimrc is:

    set guifont=Menlo\ Regular:h12

When I completely quit VimR, then start it again, then issue the command

    :set guifont?

The output is:

    guifont=Menlo Regular:h14

That is, the guifont setting seems to be ignored. The same thing happens if I set the font to Monaco.

How do I get VimR to not ignore guifont?

Thanks.

**Comment by qvacua** [comment]
If I use `set guifont=Menlo\ Regular:h12`, launch VimR and issue `:set guifont?`, I get `guifont=Menlo Regular:h12`. Even if this is a bug, I'm afraid that it won't be fixed since I am concentrating my (open-source) efforts into the rewrite of VimR with NeoVim backend.

**Comment by joaoponceleao** [comment]
Perhaps the bug also exists in nVimR?
I get `E518: unknown option guifont?` on the latest nightly

**Comment by qvacua** [comment]
I explicitly removed `guifont` option in the fork of NeoVim I use to compile VimR. In my opinion the GUI related settings should be also set in the GUI, which is also the philosophy of NeoVim: decouple (G)UI from the core. I also wanted to disable `lines`, but many plugins use it, so I could not...

**Comment by joaoponceleao** [comment]
Ah! It makes sense now. Transparency seems to also be disabled.
Still a few issues in the latest nightly though (especially with full screen mode), but I realise that hangul handling has to take top priority at the moment.

**Comment by qvacua** [comment]
Well, the input handling is resting for now... 😶 Transparency is not yet implemented. Can you create an issue with the fullscreen mode? Thanks!

**Comment by qvacua** [comment]
Closing...

**Comment by krlvi** [comment]
> I explicitly removed guifont option in the fork of NeoVim I use to compile VimR. In my opinion the GUI related settings should be also set in the GUI, which is also the philosophy of NeoVim: decouple (G)UI from the core.

I have been using the following configuration with macvim:

if has("gui_running")
  if system("osascript -e 'tell application \"Finder\" to get bounds of window of desktop' | cut -d ' ' -f 4") > 900
    set guifont=Source\ Code\ Pro:h23
  else
    set guifont=Source\ Code\ Pro:h14
  endif
endif

Is there a way to achieve this effect with vimr?
