### ISSUE TITLE
Wrong cell click

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#261]
In console/nvim you can drag vertical split if you manage to hit it visually. In VimR, you must target top-side of the bar, because bottom half does not register as a separator. 

Here is gif

![dragging-vertical-split](https://cloud.githubusercontent.com/assets/453929/17964751/8e780756-6ab2-11e6-9673-528e7a219f7d.gif)

**Comment by qvacua** [comment]
Thanks for the bug report! 😀

https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160825.1622-63
