### ISSUE TITLE
`$PATH` sometimes not set correctly

### ISSUE THREAD

**Issue by phuna** [qvacua/vimr#262]
> YouCompleteMe doesn't work in VimR, it works when I run nvim in iTerm2. I think it's because I built YCM using python3 installed using `pyenv` and vimr use system's python.
I've found a similar closed issue before: #96, but I don't want to touch system's python. Is there a way to make VimR works with python configured in my terminal's PATH, at least when starting from `vimr` command line?

* Launch NeoVimServer using the user's login shell.

**Comment by phuna** [comment]
Hmm.. I'm not sure what I did but it works when running `vimr` command line. Maybe my env had some problems before. I'll close this.

**Comment by qvacua** [comment]
Unfortunately I don't know `pyenv`... I described in the wiki how VimR sets `$PATH`, maybe you can spot what's missing?

**Comment by phuna** [comment]
@qvacua : 
`:echo $PATH` inVimR gives this:
* When run VimR app directly: `/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin`
* When run VimR app via `vimr` command: `/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/phuna/.jenv/shims:/Users/phuna/.pyenv/shims:/Users/phuna/.rbenv/shims`
So it's just the difference of the environment I launch VimR.
BTW, thanks a lot for adding `vimr` command line and fixing cursor render problem. Now I can fully replace neovim with VimR. Great works. 👍

**Comment by qvacua** [comment]
Thanks! 😀. But this issue seems to be a bug... `$PATH` should be set correctly, ie to the second one, also for double clicking VimR app. The first `$PATH` is the default path when something went wrong executing the `env ...` command described in the wiki. What shell are you using?

**Comment by romaninsh** [comment]
@phuna in which file you add the "phuna" folder? ~/.bash_profile, ~/.bash_rc or something else?

**Comment by phuna** [comment]
I'm using zsh. "phuna" folder is added by `pyenv`, `rbenv` & `jenv` for management of python, ruby & java installations.
Below is `.zshrc` content:
```sh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export JAVA_HOME=$(/usr/libexec/java_home)

export PATH=/usr/local/bin:$PATH

# rbenv
eval "$(rbenv init -)"

# pyenv
eval "$(pyenv init -)"

export EDITOR=vim
export VISUAL=vim

eval "$(jenv init -)"
```

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160826.1731-65

**Comment by phuna** [comment]
@qvacua : I've just tried but still the same problem, `YouCompleteMe` only available when launching via `vimr` in terminal.

**Comment by qvacua** [comment]
Could you download <http://taewon.de/TextBox.app.zip>, run it and post the result?

**Comment by phuna** [comment]
I got 404 not found for http://taewon.de/TextBox.app.zip

**Comment by qvacua** [comment]
Ups, a typo: <http://taewon.de/TestBox.app.zip>

BTW: it just prints out some of the steps VimR is doing to launch neovim.

**Comment by phuna** [comment]
I ran it and got this:
```
Got shell '/usr/local/bin/zsh'
Got url for shell path: file:///usr/local/bin/zsh
Using args '["-l", "-c", "env | grep \'^PATH=\' | sed \'s/^PATH=//\'"]'
/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by phuna** [comment]
@qvacua Can you share source code of TestBox? I can do some investigation myself.

**Comment by qvacua** [comment]
I'll upload the source code tomorrow (it's on my other machine). In case you cannot wait: It's basically [ShellUtils](https://github.com/qvacua/vimr/blob/7cccc87f7ff8012553a4bcae6872895568cf5d4e/SwiftNeoVim/ShellUtils.swift).pathForUserShell() with some `print()`s. 😀

**Comment by phuna** [comment]
@qvacua I think we should use login + interactive shell for launching neovim. I'm not sure for others but for me environment settings are mainly in interactive session (for zsh they're defined in .zshrc file). I've tried to changed:
```objc
[shellArgs addObject:@"-l"];
```
to
```objc
[shellArgs addObject:@"-il"];
```
and `$PATH` is set correctly when launching like starting `vimr` from command line.

**Comment by qvacua** [comment]
Thanks! I'll try it with some other shells and add the option. 😀

**Comment by qvacua** [comment]
@phuna Could you try the [issue/262-path](https://github.com/qvacua/vimr/tree/issue/262-path) branch? I tried something else...

**Comment by qvacua** [comment]
Or try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160909.2233-69 😁

**Comment by phuna** [comment]
@qvacua I tried your new version and got `/usr/local/bin/zsh: bad option: -z` when trying to open VimR's window and the app hang.
I tried to remove this: 
```objc
[shellArgs addObject:[@"-" stringByAppendingString:shellPath.lastPathComponent]];
```
then VimR can start but the `$PATH` is still not correct.

**Comment by qvacua** [comment]
OK, try this one: https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160910.0900-70

Using `-i` only for `zsh`.

**Comment by phuna** [comment]
@qvacua I've tried the latest version and it works, starting VimR from both Finder or command line can see my `$PATH`. Thank you for your effort to fix this :)

**Comment by qvacua** [comment]
You're welcome and thanks for `-i`! :)

**Comment by cHoco** [comment]
Since build 69 when opening VimR no window opens and the app hangs using 100 % of the cpu :(
I use zsh as my shell.
Not sure if it's useful but this is the output of the program above:
```
Got shell '/usr/local/bin/zsh'
Got url for shell path: file:///usr/local/bin/zsh
Using args '["-l", "-c", "env | grep \'^PATH=\' | sed \'s/^PATH=//\'"]'
/usr/local/bin:/usr/local/sbin:/Users/cHoco/Library/Haskell/bin:/usr/local/opt/go/libexec/bin:/Users/cHoco/Projects/Go/bin:/Users/cHoco/Projects/dotFiles/bin:/Users/cHoco/Projects/kwm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
```

**Comment by qvacua** [comment]
Does the newest snapshot also do this?

**Comment by cHoco** [comment]
Yes, since snapshot 69. I think the issue is that I by launching the shell as interactive (`-i` option) zsh also loads the content of .zshrc which for me includes additional processing stuff dedicated to an interactive shell, like tmux integration etc... VimR shouldn't launch the shell in interactive mode, and users with path issues should move their path customisation in the `.zprofile` file.

**Comment by qvacua** [comment]
I'll add an option to Preferences -> Advanced -> Checkbox: Use `-i` flag for zsh.

**Comment by qvacua** [comment]
Try the build [77](https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160924.1647-77). The `-i` flag is turned off by default. You can turn it on in "Preferences -> Advanced" though, @phuna .

**Comment by cHoco** [comment]
Working  good here! thank you @qvacua :D

**Comment by phuna** [comment]
Work great here too @qvacua , thank you :)

**Comment by pitkling** [comment]
Is it possible that the option for the `-i` flag is broken in the current build? When I activate it and restart VimR, the option is unchecked again.

**Comment by qvacua** [comment]
@pitkling I cannot reproduce your issue with the latest snapshot. Which version are you using?

**Comment by pitkling** [comment]
I'm on 0.26.9 (312). I played around a bit and I got the following behavior:

-   open VimR, got to Preferences (`CMD + ,`), go to the "Advanced" tab, change the zsh option, quit VimR (`CMD + q`) → change in the zsh option is not saved
-   open VimR, got to Preferences (`CMD + ,`), go to the "Advanced" tab, change the zsh option, close the preferences window (`CMD + w`), quit VimR (`CMD + q`) → change in the zsh option is not saved
-   open VimR, got to Preferences (`CMD + ,`), go to the "Advanced" tab, change the zsh option, close the preferences window (`CMD + w`), close the automatically opened editor window (`CMD + w`), quit VimR (`CMD + q`) → change in the zsh option **is** saved

I did a similar test with the "Use Ligatures" option under "Appearance", which is saved correctly in all three cases above.

**Comment by willdavidow** [comment]
This appears to still be an issue in a very specific set of cases: only when launching the application using Mac OS's Spotlight launcher and Alfred. If I open the app directly from the Applications folder or from the command line it picks up $PATH perfectly fine.

I'm setting $PATH in `.zshenv`, and I do not have the `use interactive mode for zsh` option enabled in vimr.

**Comment by tkolleh** [comment]
Experiencing the same behavior described by @willdavidow 

<img width="704" alt="Screen Shot 2020-01-29 at 1 15 36 PM" src="https://user-images.githubusercontent.com/3095197/73384592-8c548400-4299-11ea-8655-a6b7be6edf92.png">
