### ISSUE TITLE
echo has("gui_running") return 0

### ISSUE THREAD

**Issue by SolaWing** [qvacua/vimr#265]
How can I distinguish it from TUI neovim?

**Comment by phuna** [comment]
I think you can use `has("gui_vimr")` as described in wiki: https://github.com/qvacua/vimr/wiki

**Comment by SolaWing** [comment]
Thanks for tip. but some plugin use "gui_running" to check if running in a gui. this feature return 0 may have some compatible issue.

**Comment by qvacua** [comment]
NeoVim does not have this option anymore. I could re-add it in my fork... What plugins rely on `gui_running`?

**Comment by SolaWing** [comment]
It seems the most cases is related to theme. like Solarized.
fugitive,ctrlp,tagbar also use it. though I don't see obvious issue.

**Comment by qvacua** [comment]
I'm (at least for the time being) re-adding `gui_running` option. It also solves the airline issue GH-236. We have to think about a better way to do it though...

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160830.1837-66

**Comment by cHoco** [comment]
Adding `gui_running` produces all kinds of issue in my setup, since some plugins after the gui_running check use other gui options like guifont etc... Wouldn't it be better to automatically set termguicolors if it isn't? Then plugins can rely on that (for example vim-airline does)

**Comment by qvacua** [comment]
@cHoco that's probably the better solution than returning `gui_running=1`... Will do.

**Comment by qvacua** [comment]
I guess it's a good idea not to re-add options removed by NeoVim like `gui_running`. As @cHoco mentioned NeoVim-compatible plugins will probably use `termguicolors`. So use `set termguicolors` in your `init.vim`. `gui_running` is removed.

https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160926.1854-79
