### ISSUE TITLE
cursor disappear when entering command

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#267]
snapshot: 64

- hit ":"
- enter "hello"
- hit "left" button few times

cursor is not visible when going left. It re-appears if you type or go right.

![cursor-ghost](https://cloud.githubusercontent.com/assets/453929/18046528/3c8f950a-6dd0-11e6-8338-48dca6920623.gif)

**Comment by qvacua** [comment]
This will be fixed with GH-275. Closing.

**Comment by qvacua** [comment]
try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20160911.2123-73
