### ISSUE TITLE
Open Quickly doesn't have a way to filter files

### ISSUE THREAD

**Issue by ghevait** [qvacua/vimr#268]
The Open Quickly window is spammed with git files, it would be better to be able to filter them based on some rules.

Also I think fuzzy search is not quite working. I have a script called 'build'. And if I type in 'bulid', it doesn't give me the right suggestion.

**Comment by qvacua** [comment]
Have you tried to set some [ignore filters](https://github.com/qvacua/vimr/wiki/VimR-MacVim#ignore-pattern)?

**Comment by ghevait** [comment]
Sorry I forgot to check Wiki, my bad :)

**Comment by qvacua** [comment]
:)

As for the search issue, I'm afraid that VimR-MacVim is not maintained anymore. I'm concentrating my open-source efforts into VimR with a NeoVim backend as described in README. I'm closing this issue.
