### ISSUE TITLE
Change cursor shape

### ISSUE THREAD

**Issue by mfojtik** [qvacua/vimr#276]
It is possible to change the cursor shape to a vertical line when in insert mode and block shape when in ex mode? Similar to what MacVim does.

Looking at the code it seems the block shape is hardcoded. I will also be happy with just an option to turn on the vertical line permanently.

Thanks!

**Comment by qvacua** [comment]
It's not yet possible (or it's not implemented yet). However, the current cursor rendering has to be fixed first 😬.

**Comment by pluskid** [comment]
+1 this! Two main reasons for me to use a GUI vim instead of a terminal one is

- cursor indicate mode: now that is not implemented yet
- good interaction with the system clipboard: now it is kind of buggy in VimR: if you select a region **using mouse** and type Cmd+C, then you selection is replaced by the text `"+y`.

**Comment by qvacua** [comment]
I cannot reproduce the second point. So I did

* select some text using the mouse
* Cmd+C => VimR reports how many lines are yanked and the text is copied to the system clipboard.

@pluskid: can you describe the steps to reproduce the bug in more detail?

**Comment by pluskid** [comment]
@qvacua I double checked. It seems to be caused by the following setting:
```
source $VIMRUNTIME/mswin.vim
```
This came from my (very) old vim configuration. It seems this is now not working properly for nvim. I get expected behavior after removing this. Thanks!

**Comment by wayneashleyberry** [comment]
+1

https://github.com/neovim/neovim/wiki/FAQ#how-can-i-change-the-cursor-shape-in-the-terminal

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161111.2237-124
