### ISSUE TITLE
Font rendering for polytonic Greek has problems

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#283]
First off, I apologize. I apologize for this hideously specific bug report and I apologize for what might be a poor title. (Feel free to rename it if you can think of anything better.)

I work with ancient Greek quite a lot. Vim and NeoVim handle it pretty well. Although the rendering of complex words (where complex means "with several diacritics or accents all over one letter) can be ugly (squished, etc.), it works.

I just noticed, however, that a document I'm editing looks different in vimR versus in NeoVim in Terminal.app. The problems are visible on line 1025 and below (where the cursor is in both pictures).

vimR:

![screen shot 2016-09-16 at 4 00 08 pm](https://cloud.githubusercontent.com/assets/62958/18599676/8c6a16a8-7c27-11e6-8e74-68aad88ce9eb.jpg)

neovim in Terminal.app:

![screen shot 2016-09-16 at 4 01 33 pm](https://cloud.githubusercontent.com/assets/62958/18599678/94d5cbc0-7c27-11e6-93ed-56f073344d5f.jpg)

This may be related to https://github.com/qvacua/vimr/issues/212 or to https://github.com/qvacua/vimr/issues/239.

OSX 10.11.6
Terminal.app: Version 2.6.1 (361.1)
neovim: NVIM v0.1.6-105-g6e9f329
Build type: Dev
Compilation: /usr/local/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160916-53343-179mv16/build/config -I/tmp/neovim-20160916-53343-179mv16/src -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/tmp/neovim-20160916-53343-179mv16/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160916-53343-179mv16/build/src/nvim/auto -I/tmp/neovim-20160916-53343-179mv16/build/include
Compiled by telemachus@mbpr1315-3192.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui  
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-6e9f329/share/nv
vimR: Version 0.9.0-SNAPSHOT-20160915.2238 (75)

Here's the LaTeX file in question: https://gist.github.com/734ac38e99a7acb73e968cd1158c03f7.

Please let me know if any other information would help.

**Comment by qvacua** [comment]
My first guess would be that the character is interpreted as being _wide_, i.e. it occupies two cells in NeoVim. However I then cannot explain why Terminal is rendering them correctly... I'll have a look at this, but it'll take some time.

**Comment by telemachus** [comment]
Just a quick follow-up for this bug: today I'm seeing a new problem with Greek. On a line containing a mixture of polytonic Greek and Latin characters, vimr (but not neovim in the terminal) is showing a whole bunch of non-existent encoding garbage. 

vimr:

![screen shot 2016-11-14 at 2 35 08 pm](https://cloud.githubusercontent.com/assets/62958/20279927/7bc747b0-aa78-11e6-94e0-eb04209181ae.jpg)

neovim in terminal:

![screen shot 2016-11-14 at 2 36 13 pm](https://cloud.githubusercontent.com/assets/62958/20279937/848d1e2e-aa78-11e6-93e8-ca9a6fe98943.jpg)

OS X: 10.11.6

vimr: Version 0.11.0-SNAPSHOT-20161113.1502 (126)

neovim: NVIM v0.2.0-63-g4539d86

Let me know if I can do anything else to debug this for you.

**Comment by qvacua** [comment]
Hm... That looks bad. Can you post the problematic part of the file?

**Comment by telemachus** [comment]
Sure: it's the bottom portion of this file: https://gist.github.com/telemachus/6652d8a2fcbb90cf321e26eedfa81d8f.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F219

**Comment by telemachus** [comment]
Terrific work: thanks to you and to @nhtzr!

vimr:

![vimr](https://user-images.githubusercontent.com/62958/29423517-11a3acf6-834a-11e7-8796-8212b97373f2.jpg)

neovim in iterm2:

![iterm2](https://user-images.githubusercontent.com/62958/29423520-17d4c0b0-834a-11e7-8216-535090ca4493.jpg)

**Comment by qvacua** [comment]
:D
