### ISSUE TITLE
Paste in insert mode

### ISSUE THREAD

**Issue by zaius** [qvacua/vimr#285]
First of, massive kudos for this project. I'm very excited to find a native mac gui for neovim.

It looks like pasting with command-v works fine from normal mode, or when in insert mode with paste mode on.

However in insert mode with paste mode off some of the the pasted text is treated like commands. I am not sure what the commands being sent are, but I can get it to consistently occur when pasting text with newlines.

Let me know if I can help with any more debugging info!

**Comment by qvacua** [comment]
Hm... I cannot reproduce this. I just opened this page and `Cmd-A` -> `Cmd-C`, did `set nopaste` went into insert mode and then `Cmd-P`. I did not get any strange behavior. Can you post an example text?

**Comment by qvacua** [comment]
BTW: used the latest release v0.10.0.

**Comment by zaius** [comment]
I just downloaded v0.10.0-118 and this is still happening for me.

Here's a quick example - http://recordit.co/sMw0nZbOKS

Keys typed:

```
shift-v
j
cmd-c
cmd-v  # this works
i
cmv-v  # this breaks
```

Let me know if that makes sense!

**Comment by qvacua** [comment]
When I do what you described, I obtain
```
foo
foo
bar
foo
bar
bar
```
which is correct. Does this also happen with a "clean" `init.vim`?

**Comment by qvacua** [comment]
Maybe related to GH-329

**Comment by zaius** [comment]
I hadn't even thought about my init.vim being an issue - my apologies! It doesn't happen with a clean init.vim. I've narrowed it down to the following line:

`imap <C-j> <ESC>:tabnext<CR>`

It seems like remapping Ctrl-J in insert mode is the issue.

**Comment by qvacua** [comment]
Thanks for that information. I'll look into it.

**Comment by zaius** [comment]
No worries! Closing this since the title is a bit misleading.

**Comment by qvacua** [comment]
I've create a new issue: GH-332 😃

**Comment by qvacua** [comment]
I asked around in the neovim's gitter and it turns out that `Ctrl-J` is equivalent to `\n` in vim... That explains why you get the strange behavior.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161111.1436-123

It's not perfect, but at least you can paste...

**Comment by zaius** [comment]
Awesome! Works great for me. Thanks for the fix.

**Comment by woahdae** [comment]
When using yankstack in combination with this update, `<Plug>yankstack_after_paste` gets inserted after the pasted content. See also, [this reddit thread describing the issue](https://www.reddit.com/r/vim/comments/7txqkq/amixs_awesome_vimrc_vimyankstack_plugin_issues/).

Not sure where the responsibility for the fix lies, but since it only happens in VimR, probably here?

**Comment by 9mm** [comment]
This still happens for me. @woahdae did you ever fix this?

**Comment by 9mm** [comment]
Specifically if i paste something and i have vim-yankstack on.. if im pasting `xxx` this is what appears:

    xxx<Plug>yankstack_after_paste

**Comment by 9mm** [comment]
for pasting im using `command+v`
