### ISSUE TITLE
Basic help documentation not available

### ISSUE THREAD

**Issue by jrolfs** [qvacua/vimr#288]
Not sure if this has something to do with my setup but I've noticed I don't get any of the default vim/neovim runtime help in VimR ( ຈ ﹏ ຈ )

![how do?](http://d.pr/i/10iJp+)

**Comment by jrolfs** [comment]
This is https://github.com/qvacua/vimr/commit/f3754ca27e35ad42255fc20f88c0703f51203bec compiled from source with included Neovim submodule.

**Comment by qvacua** [comment]
Probably I messed up something when launching NeoVim and setting the runtime path. Will look into it.

**Comment by jrolfs** [comment]
Thanks!

**Comment by qvacua** [comment]
It seems that the content of `runtime` must be "compiled". Till now I just copied `neovim/runtime` folder to the `.app`-package, but that folder does not contain the help-tag file which seems to be needed. Will have to look at it in more detail to fix this.

**Comment by qvacua** [comment]
The help files were missing. Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20161008.1820-86

**Comment by jrolfs** [comment]
Thank you!
