### ISSUE TITLE
Representation Issues on OSX while Scrolling

### ISSUE THREAD

**Issue by hypergnash** [qvacua/vimr#291]
![vimr](https://cloud.githubusercontent.com/assets/1956146/19114689/5612eb06-8b0f-11e6-81a3-da737a4ae817.png)

Representation Issues on OSX while Scrolling a huge file (30MB)

VimR Version 0.8.0 (32)
on OSX 10.11.6 (15G1004)

**Comment by qvacua** [comment]
VimR with MacVim backend won't be developed anymore, thus closing this issue. I'm concentrating my open source efforts into VimR with NeoVim backend. Please try the snapshot builds from <https://github.com/qvacua/vimr/releases>. The file browser will be there soon 😁.
