### ISSUE TITLE
When press "x" or "dd", VimR gets really laggy

### ISSUE THREAD

**Issue by fevin86** [qvacua/vimr#305]
I am using OSX 10.12 and 0.9.0-SNAPSHOT-20161010.1956-90 snapshot.

**Comment by qvacua** [comment]
Hm... I use VimR everyday and I did not have this problem. Does anyone else have this problem?

**Comment by qvacua** [comment]
BTW: using VimR on 10.11 and 10.12.

**Comment by fevin86** [comment]
Do you use the snapshot with built-in nvim? Or should I try building vimr rather than using the snapshot?

**Comment by qvacua** [comment]
Yes, the snapshot builds contains neovim built as library (and all the necessary runtime files). It shouldn't make any difference whether you use the snapshot builds or you build VimR yourself.

**Comment by fevin86** [comment]
okay, that's weird. I tried the same thing on my other laptop, it was laggy when using "x" to delete characters. I also found the cpu usage of neovimserver raised from almost 0 to 5.x%.

BTW, my keyboard repeat is set to be the fastest.

**Comment by romaninsh** [comment]
How is your clipboard configured?

**Comment by fevin86** [comment]
@romaninsh I see what you mean. Seems it's an issue of neovim with system clipboard, thanks.

@qvacua thanks for your help as well, I'll close the issue.
