### ISSUE TITLE
Relative Paths for vimr cli tool

### ISSUE THREAD

**Issue by pbdeuchler** [qvacua/vimr#306]
You currently can't pass relative paths to `vimr --cwd`, which precludes people (ahem) from doing things like aliasing `vimr --cwd` to, say, `e` and running `e .` to open the current directory in vim (which is what I do with my system vim).

If it matters, `vimr --cwd .` opens up my root directory in vim, and trying any kind of relative path opens up my home directory

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.9.0-SNAPSHOT-20161017.2152-107

**Comment by pbdeuchler** [comment]
That was fast! Much appreciated!

**Comment by qvacua** [comment]
Thanks for reporting! 😀

**Comment by pbdeuchler** [comment]
Updated the homebrew cask recipe for the new version: https://github.com/caskroom/homebrew-cask/pull/25599

**Comment by pbdeuchler** [comment]
Probably should have tested first...

```
 → vimr .
Traceback (most recent call last):
  File "/usr/local/bin/vimr", line 66, in <module>
    vimr(action, args, dry_run)
  File "/usr/local/bin/vimr", line 24, in vimr
    "cwd": abspath(args.cwd) or os.getcwd()
  File "/usr/local/bin/vimr", line 17, in abspath
    return os.path.abspath(os.path.expanduser(path))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by qvacua** [comment]
I did not test the script without `--cwd` option, 😔. It's fixed now. (I hope!) https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.9.0-SNAPSHOT-20161018.1206-109

**Comment by qvacua** [comment]
Oops, the build above is broken, I deleted it. I'll build another one later.

**Comment by qvacua** [comment]
So... https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.9.0-SNAPSHOT-20161018.1801-110

**Comment by pbdeuchler** [comment]
Awesome, thanks!
