### ISSUE TITLE
When opening a file in a new window set `cwd` to the parent folder of the file

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#308]
- a file -> parent folder
- a folder -> the folder
- when a window is already open with a new unmodified file and we're opening a file or a folder, set `cwd`, too.

**Comment by timhatch** [comment]
Adding the auto command `au BufEnter * :cd %:p:h ` within an `if has('vim)` block inside my .vimrc seems to do the trick, but as noted this is unnecessary for macvim or vim

**Comment by qvacua** [comment]
In VimR you can set the `cwd` property of the `NeoVimView` somewhere appropriate.

**Comment by timhatch** [comment]
Thanks. Works a treat. Thumbs up.

**Comment by andrimarjonsson** [comment]
Hi,

Don't know it this should be entered as a new bug, will do so if that is the case, but I'm facing the problem that when I right click a file in Finder and select VimR in the "Open With" menu. The VimR window that gets opened always has the CWD set to $HOME, no matter where the file being opened is located.

IIRC that is how MacVim works, perhaps there is something in their codebase that can be used to achieve the same in VimR?

**Comment by qvacua** [comment]
This is rather a bug. Could you please create a new issue? Thanks!
