### ISSUE TITLE
Any way to set terminal colours?

### ISSUE THREAD

**Issue by mikl** [qvacua/vimr#310]
I really love the new VimR, but there's one thing I'm missing to achieve editor perfection, and that is terminal colours.

As you probably know, one of the exciting new features of NeoVim is the ability to have terminal buffers. This is great, because it makes it possible to have a Vim-powered IDE-like experience, without having to resort to additional tools like tmux (which adds another level of window management to be confused about), or constantly switching apps.

So what I wanted to figure out, is if its possible to configure the terminal colour scheme somehow. As you can see in the attached screenshot, VimR uses the standard console colours, which may or may not clash horribly with the Vim colour scheme you're using. In this case, the (garish) neon-green has poor legibility on the beige background (that's the Solarized theme), and the yellow plus in the Git status line is almost invisible. As comparison, iTerm 2 shows the same output with its Solarized theme.

![2016-10-23 at 01 23](https://cloud.githubusercontent.com/assets/10263/19623189/d4beeed2-98c0-11e6-876f-4a5a22466608.png)

Is this possible to do at the moment? If not, I'd like to add it as a suggestion for the future – thanks for reading 😄

**Comment by qvacua** [comment]
I'm guessing that NeoVim's terminal integration sets the colors. I'll look into it.

**Comment by timhatch** [comment]
wouldn't the easiest thing be to just set the terminal colours in .vimrc like so:
  " Set neovim embedded terminal colors
  let g:terminal_color_0  = '#2e3436'
  let g:terminal_color_1  = '#cc0000'
  let g:terminal_color_2  = '#4e9a06'
  let g:terminal_color_3  = '#c4a000'
  let g:terminal_color_4  = '#3465a4'
  let g:terminal_color_5  = '#75507b'
  let g:terminal_color_6  = '#0b939b'
  let g:terminal_color_7  = '#d3d7cf'
  let g:terminal_color_8  = '#555753'
  let g:terminal_color_9  = '#ef2929'
  let g:terminal_color_10 = '#8ae234'
  let g:terminal_color_11 = '#fce94f'
  let g:terminal_color_12 = '#729fcf'
  let g:terminal_color_13 = '#ad7fa8'
  let g:terminal_color_14 = '#00f5e9'
  let g:terminal_color_15 = '#eeeeec'

**Comment by qvacua** [comment]
@mikl have you tried the setting @timhatch has suggested?

**Comment by mikl** [comment]
Yes, that works great, thanks.

For reference, if you want to follow the Solarized colour scheme, use these settings:

```viml
let g:terminal_color_0 = '#003541'
let g:terminal_color_1 = '#dc322f'
let g:terminal_color_2 = '#859901'
let g:terminal_color_3 = '#b58901'
let g:terminal_color_4 = '#268bd2'
let g:terminal_color_5 = '#d33682'
let g:terminal_color_6 = '#2aa198'
let g:terminal_color_7 = '#eee8d5'
let g:terminal_color_8 = '#002833'
let g:terminal_color_9 = '#cb4b16'
let g:terminal_color_10 = '#586e75'
let g:terminal_color_11 = '#657b83'
let g:terminal_color_12 = '#839496'
let g:terminal_color_13 = '#6c6ec6'
let g:terminal_color_14 = '#93a1a1'
let g:terminal_color_15 = '#fdf6e3'
```

**Comment by qvacua** [comment]
What about a PR to https://github.com/iCyMind/NeoSolarized and/or https://github.com/frankier/neovim-colors-solarized-truecolor-only ?

**Comment by mikl** [comment]
@qvacua good idea, I've added a PR for NeoSolarized.
