### ISSUE TITLE
text anti-aliasing

### ISSUE THREAD

**Issue by wayneashleyberry** [qvacua/vimr#312]
It looks like text anti-aliasing is disabled, is this a known issue or something being worked on?

I'm using the v0.9.0-112 release.

Here pictured from left to right is VimR, MacVim and iTerm 2

![screen shot 2016-10-23 at 8 20 07 pm](https://cloud.githubusercontent.com/assets/727262/19628442/234ef48c-995e-11e6-8b54-ad3e1061c571.png)

**Comment by qvacua** [comment]
Probably related to GH-239.

**Comment by qvacua** [comment]
Could you please try https://github.com/qvacua/vimr/releases/tag/snapshot/v0.10.0-SNAPSHOT-20161024.2203-114 and give me feedback?

**Comment by wayneashleyberry** [comment]
Looking much better to me @qvacua! I can only test on my retina laptop right now but I'm going to consider this closed - thanks!

Left is MacVim, Right is VimR - there's still a subtle different, but it's minor.

<img width="629" alt="screen shot 2016-10-24 at 10 19 47 pm" src="https://cloud.githubusercontent.com/assets/727262/19662501/0e9551be-9a38-11e6-8f00-c34843bfed20.png">

**Comment by qvacua** [comment]
Try the latest snapshot which uses font smoothing on both retina and non-retina displays.

**Comment by wayneashleyberry** [comment]
Oh wow, it's identical to MacVim now @qvacua - thank you!
