### ISSUE TITLE
Custom Title Bar

### ISSUE THREAD

**Issue by wayneashleyberry** [qvacua/vimr#313]
Allowing custom title bar's based on the color scheme would be amazing!

There's an informative pull request on atom where they implemented it, hopefully it helps?

https://github.com/atom/atom/pull/11790

Here's a screenshot:

![24a16dde-8ba2-11e6-83a3-b6d75180fc65](https://cloud.githubusercontent.com/assets/727262/19705258/ce7e5db2-9b0b-11e6-8e9d-218bd37affdc.png)

**Comment by qvacua** [comment]
This would be indeed nice, but it would require quite some work and let's see... 😅
