### ISSUE TITLE
Enable mapping of <C-Tab> and <C-S-Tab>

### ISSUE THREAD

**Issue by rolandcrosby** [qvacua/vimr#315]
I'd like to be able to use `<C-Tab>` and `<C-S-Tab>` to switch between tabs. Currently this doesn't work correctly in VimR because Tab is treated as C-I. [neovim-dot-app was able to fix this](https://github.com/rogual/neovim-dot-app/issues/190) so it should be doable, I just don't know how different the codebase is, so not sure if you can reuse that solution.

**Comment by qvacua** [comment]
Probably one just has to port the Obj-C code to Swift. Thx for reporting!
