### ISSUE TITLE
add <C-space> as <NUL>

### ISSUE THREAD

**Issue by yqrashawn** [qvacua/vimr#319]

**Comment by qvacua** [comment]
Can you explain in more detail what this'll do?

**Comment by yqrashawn** [comment]
[This may explain, and also this](http://stackoverflow.com/questions/23189568/control-space-vim-key-binding-in-normal-mode-does-not-work).
And also `<C-i>` and `<Tab>` at `:help tab`.
My init.vim
```
nnoremap <tab>   <c-w>w
nnoremap é <C-i>zz
```
And I let <C-i> send é in iterm2.

**Comment by yqrashawn** [comment]
Never mind, I solved this by `tnoremap <C-space> <C-\><C-n>:Ttoggle<CR>`

**Comment by qvacua** [comment]
Ok, I'll close the issue. Please feel free to reopen if nec'.
