### ISSUE TITLE
Option to disable file browser

### ISSUE THREAD

**Issue by idpbond** [qvacua/vimr#320]
Couldn't find anything about this in the documentation/settings/issues, but is there a way to disable (not hide/collapse) the file browser (even the white vertical bar with the "Files" text on it when it is collapsed)?

Although it's relatively thin, it's still an extra white column that serves me no purpose (using NERDTree, etc).

Thanks

**Comment by qvacua** [comment]
Yes, you can! 🙃
![screen shot 2016-11-01 at 18 24 25](https://cloud.githubusercontent.com/assets/460034/19899439/7195c5ae-a060-11e6-934d-c957d820b0ab.png)
(That menu item _only_ hides the bar. You should also hide the file browser to hide both.)
Thanks for pointing this out: I should mention this in the wiki...

The plan is to introduce other tools as in the following mockup: <https://twitter.com/vimrefined/status/779948056674467840> Then the column will make more sense...

Does this solve your issue?

**Comment by idpbond** [comment]
@qvacua 

Yes. Completely missed that.
Thanks for the heads up and the great project
