### ISSUE TITLE
Cmd-V paste does not work in terminal buffers

### ISSUE THREAD

**Issue by mikl** [qvacua/vimr#321]
When a terminal buffer is active (in it's special input-like mode), trying to paste with Cmd-V simply outputs the string `"+p`.

This is presumably because VimR tries to exit a normal insert mode with `esc` or a similar signal, but in the case of terminal buffers, this is simply passed on to the shell (since you can run any terminal program in the terminal, including vi, this is a practical choice).

To get back to normal mode from a terminal buffer, the keystroke combination `<C-\><C-n>` is used.

**Comment by qvacua** [comment]
You're right. Did not think about that. Will do.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161106.2224-119

**Comment by qvacua** [comment]
Sorry, this one... https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161106.2304-120

**Comment by mikl** [comment]
Works like a charm, thanks 👍
