### ISSUE TITLE
When launching from terminal, keep in same directory

### ISSUE THREAD

**Issue by carl0m** [qvacua/vimr#324]
When I launch VimR from a terminal using the command 
open -a "VimR"
I would like VimR to think it's in the same directory as I was when I launched it from the terminal.  This would be very useful for a script I have, and MacVim does this the way I want.  More specifically, when I launch an external command from VimR which creates some auxiliary files (such as latex), I would like those files to appear in the current directory, not in my home directory.

**Comment by qvacua** [comment]
If you want to open file(s) from a terminal you should use the included command line tool `vimr`: <https://github.com/qvacua/vimr/wiki#command-line-tool>

**Comment by carl0m** [comment]
I see there is a second solution as well:  in init.vim, include the command:
set autochdir
