### ISSUE TITLE
Closing File browser with ⌘1 does not focus NeoVimView

### ISSUE THREAD

**Issue by mikl** [qvacua/vimr#330]
Currently, another keystroke (⌘.) is necessary to bring NeoVim into focus. It would be nice to save that keystroke.

**Comment by qvacua** [comment]
Thanks for pointing it out. Will be in the next snapshot (and release).

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161109.2136-121

**Comment by mikl** [comment]
Works great, thanks :)
