### ISSUE TITLE
:CheckHealth reports no environment variable TERM set

### ISSUE THREAD

**Issue by ngocphamm** [qvacua/vimr#331]
I apologize in advance if this is too noob of a question.

I do have it set within `.zshrc` with `[[ $TMUX = "" ]] && export TERM="xterm-256color"`. Opening a new terminal window and do `echo $TERM` and I can see `xterm-256-color`.

Quit then open a new VimR instance, trigger `:CheckHealth` and still see

```
## terminfo
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
```

Any idea where VimR read the environment variable from, or I have to logout/login again to have that in effect?

**Comment by qvacua** [comment]
Well, I'm quite noob in these things, too. 😃 The NeoVim process in VimR is launched your `$SHELL`. However, since VimR integrates NeoVim as a library (and therefore does not include the TUI) it may well be that the terminal related variables are broken (by design)...

**Comment by ngocphamm** [comment]
I think I found out the reason, @qvacua.

Because VimR is not ran under an interactive zsh shell (by design), it won't actually got the environment set by `.zshrc`. Putting that line to `.zprofile` would do it. 😃

**Comment by qvacua** [comment]
OK. Good to hear. You can force the interactive mode of zsh though if necessary, cf. https://github.com/qvacua/vimr/issues/262.

**Comment by ngocphamm** [comment]
I was scared of the warning text, so I would not want to f* with it 😆

**Comment by qvacua** [comment]
😛
