### ISSUE TITLE
`set termguicolors` and `set title` by default when opening a new window

### ISSUE THREAD

**Issue by wookayin** [qvacua/vimr#334]
Hi, thanks for the awesome project, and I am greatly enjoying it :-)

Currently vimr does not show powerline fonts

Normal terminal environment that supports powerline fonts: (e.g. iTerm2)
![image](https://cloud.githubusercontent.com/assets/1009873/20165568/d531a9dc-a751-11e6-85d5-3bf1e39d8e8d.png)

in VimR, Version 0.11.0-SNAPSHOT-20161109.2136 (121):
![image](https://cloud.githubusercontent.com/assets/1009873/20165585/064cc970-a752-11e6-9d33-c2a45bf59d51.png)

I am using `SauceCodePowerline` fonts for both environment. It looks like a font rendering issue, but I do not know why.

**Comment by qvacua** [comment]
You have to `set termguicolors` in your `init.vim` as described in the [wiki](https://github.com/qvacua/vimr/wiki#initvim).

**Comment by wookayin** [comment]
Oops, there was already an issue #269 and a [wiki document](https://github.com/qvacua/vimr/wiki#initvim); sorry I missed it.

By the way, setting them by default looks a good idea!
Thanks for your reply!

**Comment by wookayin** [comment]
How can we apply those configs (i.e. `termguicolors` and `title`) **only** for vimr?

I can not find any stuff like `has("vimr")` or `~/.config/vimr/init.vim`. It seems that [`~/.vimr_rc`](https://github.com/qvacua/vimr/wiki/VimR-MacVim) is available, but just for a wonder.

**Comment by wookayin** [comment]
I found it, #241 : `has(gui_vimr)`. It would be nice if documentation mentioned it, so I updated the wiki.

**Comment by qvacua** [comment]
Thanks. There was a section about the `gui_vimr` at the end of the wiki page 🙃 However, it's better to mention it in the `init.vim` section. I'll move the old section.

**Comment by qvacua** [comment]
This [snapshot](https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161111.2237-124) will do this.
