### ISSUE TITLE
Command line tool opens two windows on startup

### ISSUE THREAD

**Issue by adam-stone101** [qvacua/vimr#338]
Reproduce:

1. Get VimR CLT
2. Tick 'Open Untitled Window on Launch'
3. Quit VimR
4. Launch VimR from command line

Notice that two editor windows are opened, one untitled window, one with the file you specified in command line arguments. Not sure if this is desired behaviour.

**Comment by qvacua** [comment]
Thanks for reporting. No, it should only open one window with the specified file. Which version of VimR are you using? Have you tried the newest snapshot? I get only one window when I repeat the steps you describe.

**Comment by adam-stone101** [comment]
I'm using version 0.8.0 . When I check for update, it says no updates available, so I assume it's the newest version.

It's strange since I did the steps above and it did open up two windows. Note that when you reactivate VimR through command line, only one window shows up, even when 'Open untitled window on re-activation' is ticked. The problem only happens when VimR first starts.

If no other people are reporting this, I'm OK with it, it's not a huge problem :)

**Comment by qvacua** [comment]
> I'm using version 0.8.0 . When I check for update, it says no updates available, so I assume it's the newest version.

It is outdated. Recently VimR has been rebooted and we now use Neovim as its backend. Check the [releases](https://github.com/qvacua/vimr/releases) page for the newest releases and snapshots. If you download one of the new versions, you'll again get automatic updates.
