### ISSUE TITLE
Add a preview tool for markdown

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#339]
* add it to the right tool bar by default
* for markdown
    - convert and display the html file
    - use JS for conversion?
* for html
    - just display the file

**Comment by butterflyfish** [comment]
please add pdf support. example use scenario, run make to convert markdown/tex to pdf, and then preview pdf.

**Comment by qvacua** [comment]
Oh right, I used to use vim-latex and the inverse/forward search was really important back then: GH-342

**Comment by romaninsh** [comment]
I think #242 would help as well.

In my projects I use "sphinx-doc" for generating documentation. Currently I write doc in RST format then execute "make" that converts it into HTML. I then have to switch to browser to preview. 

If it would be possible to open HTML browser component inside a window (like Atom does) and if HTML would reload automatically (kqueue?) on change keeping scroll position, that would improve my workflow significantly.

**Comment by qvacua** [comment]
First rough snapshot: https://github.com/qvacua/vimr/releases/tag/snapshot%2F160

**Comment by telemachus** [comment]
This looks terrific at first glance. Even ancient Greek (which had been a problem in vimr) looks very good.

![Greek!](http://imgur.com/a/huqJV)

Not a bug, but a feature request: would it be possible to have an option to flip 100% between preview and code? That is, as things are, you have to share the window between raw markdown and preview. But what I often want to do is flip entirely and simply view and read the preview, and then go back to the raw markdown.

In any case, thanks so much for vimr. It keeps getting better and better.

**Comment by butterflyfish** [comment]
It seems pictures can not be previewed. [Typora](http://typora.io) is a markdown editor I like, its backend is pandoc.

**Comment by qvacua** [comment]
We use https://github.com/indragiek/CocoaMarkdown and pictures are working for me.
![screen shot 2017-01-10 at 7 38 11 am](https://cloud.githubusercontent.com/assets/460034/21796248/bfb8bb3c-d707-11e6-8bc7-7355d30a9df2.png)
Maybe it's some kind of base URL issue? Could you post a reduced version of your markdown with dummy pictures in a folder like your actual files?

**Comment by qvacua** [comment]
@romanish something like that would be possible. That way you probably would have a very general previewer where the user somehow (using some Vim plugins) generates the preview html files and the web view just displays it (keeping the scroll position 😀) => GH-383

**Comment by butterflyfish** [comment]
@qvacua,
only one line at md file
```
 ![](a.png)
```

vimr version is snapshot 161. Typora can render it.

**Comment by wookayin** [comment]
Awesome! Some bugs or suggestions:

- URL strings are not automatically linked (e.g. https://github.com). 
- Will it be possible for make it configurable or extensible so that one can activate mathjax? Would it be difficult because the UI rendering is not web-based?

I believe the behavior originates from CocoaMarkdown, but could we deal with it?

**Comment by robertgzr** [comment]
Would it be possible to render the content of the vim buffer instead of the file on the disk? Could the preview update as you type that way?

**Comment by qvacua** [comment]
@butterflyfish Yes, you're right, local images (or files) do not get loaded because somehow `WKWebView.loadHTMLString` does not load local files; did not know that... It's fixed by serving the files via an http server: yes, a bit of an overkill, but alas...

@wookayin Automatic linking is [not included](https://talk.commonmark.org/t/autolinking-is-not-automatic/73/7) in commonmark spec. Neither is Mathjax... Let's postpone this to the next iteration of the preview... 😀

@robertgzr It's possible, but I'd postpone this to the next iteration of the preview.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F163: should fix the image issue.

**Comment by butterflyfish** [comment]
web viewer is ready. how about allow use to configure Markdown backend. For example, when press  
"Markdown", it will invoke pandoc(or others) to convert markdown to html.  different Makrdown render have little different, it's better to leave backend choice at user, as result, vimr focus on editing.

**Comment by HustLion** [comment]
can we have a popup when editing markdown image field? not just in the render window?
