### ISSUE TITLE
Swapfile dialog causes freezes neovim when opening a file from the file browser

### ISSUE THREAD

**Issue by robertgzr** [qvacua/vimr#341]
When I try to open a file from the file browser and the swapfile dialog opens where I have the choice to (O)pen read-only, (E)dit anyway ... neovim freezes and I can't close VimR normally (with Cmd+Q).

![cpu usage](http://i.imgur.com/3UtyNYf.png)

**Comment by qvacua** [comment]
I cannot reproduce this. Which macOS and VimR version are you using?

**Comment by robertgzr** [comment]
I'm running 10.11.6 and version 0.11.0-SNAPSHOT-20161113.1502 (126) of VimR.

**Comment by qvacua** [comment]
I reproduced it, sorry, I did not get the "open a file from the file browser" part the first time. Will investigate and hopefully fix..

**Comment by robertgzr** [comment]
sorry for not being able to provide more information on this... but I'm glad you found it. This really only happens occasionally but when it does it's really annoying^^

**Comment by qvacua** [comment]
It's fixed, but I'll fix another annoying bug, GH-347, then build a snapshot.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161120.1616-129
