### ISSUE TITLE
Support for :python3 on neovim

### ISSUE THREAD

**Issue by kunxi** [qvacua/vimr#345]
Issue #158 is related to the macvim backend.

The new neovim does not support `+python3` feature.

**Comment by qvacua** [comment]
Maybe this can help you? https://neovim.io/doc/user/provider.html#provider-python

**Comment by kunxi** [comment]
My bad, it turns out that I am using `pyenv` and `python` module from `prezto`. The working directory is configured to use python2.7, so the vimr starts without python3 support.

**Comment by qvacua** [comment]
Ehm, ok, I'm not a python guy, so whatever you say 🙃
