### ISSUE TITLE
Environment variable `TERM` not set

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#348]
Running `:CheckHealth` shows the following:

    ## terminfo
      - ERROR: command failed: infocmp -L
        infocmp: environment variable TERM not set

I'm assuming that this has to do with how `vimr` sets up the environment, because `:CheckHealth` with `nvim` in the terminal shows this:

     ## terminfo                                                                 
       - INFO: key_backspace terminfo entry: key_backspace=\177,

This may not matter. That is, I haven't run into a concrete problem that this causes, but in theory it might lead to issues when running `!` commands from `vimr`. In any case, I noticed it and thought I would mention it for future reference.

**Comment by qvacua** [comment]
I think that this is a duplicate of GH-331: See https://github.com/qvacua/vimr/issues/331#issuecomment-258941061

**Comment by justinmk** [comment]
Actually, this is arguably a CheckHealth bug. It should skip that check if `TERM` is empty (better: if TUI isn't running).

**Comment by qvacua** [comment]
OK. Closing... (probably VimR is the only GUI having this issue?) :)
