### ISSUE TITLE
100% CPU usage on start after GH-297

### ISSUE THREAD

**Issue by wookayin** [qvacua/vimr#350]
After updating to 0.11.0-SNAPSHOT-20161123.2218 (#297),
vimr does not start and it just hits 100% CPU usage.

It does not happen in v0.11.0-SNAPSHOT-20161123.2001-132.
I am using macOS 10.11.6.

**Comment by wookayin** [comment]
For your diagnosis, I attach the result of sampling tool.

[VimR-GH350-sample.txt](https://github.com/qvacua/vimr/files/610123/VimR-GH350-sample.txt)

**Comment by qvacua** [comment]
Yes, I also noticed it five minutes ago on my private machine which runs 10.11.6. jemalloc/jemalloc#494 seems to be the cause for this. I'll build a new snapshot without jemalloc upgrade on Neovim.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161123.2350-134. It works on my machine 😏

**Comment by wookayin** [comment]
Thanks, it works.
