### ISSUE TITLE
Unknown option

### ISSUE THREAD

**Issue by Alok** [qvacua/vimr#352]
I get this error every time i open VimR. I'm using the HEADs of VimR and Neovim

`Unknown option inccommand=nosplit`

Is VimR using a version of `nvim` that isn't updated for that yet? Is there any way to get it working?

**Comment by qvacua** [comment]
We try to use very recent version of Neovim. VimR uses since the version [0.10.1] (https://github.com/qvacua/vimr/releases/tag/v0.10.1-122) Neovim with `inccommand`. Which version of VimR are you using? (BTW VimR does not use `nvim` installed via Homebrew or similar. It brings its own Neovim)

**Comment by Alok** [comment]
My version is `NVIM v0.2.0-121-gecd7beb`, the latest from HEAD. I installed VimR with `brew cask reinstall vimr --HEAD`.  Is that the right command?

**Comment by qvacua** [comment]
I don't use Homebrew cask, so I cannot tell whether you're really using the `HEAD` of VimR. However, you can download VimR from https://github.com/qvacua/vimr/releases. VimR has automatic update (if you want to you can also follow kind of daily snapshot, see https://github.com/qvacua/vimr/wiki#automatic-update).
