### ISSUE TITLE
TERM is not set

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#356]
Probably not a huge deal, but if you type

``` 
:CheckHealth
```

It complains about TERM variable not being set:

```
## terminfo
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
```

**Comment by qvacua** [comment]
😆 This is a duplicate of #331 and #348 (see especially https://github.com/qvacua/vimr/issues/348#issuecomment-263370259). Closing...
