### ISSUE TITLE
Add touchbar support

### ISSUE THREAD

**Issue by nicosuave** [qvacua/vimr#358]
Would be pretty awesome if say, there was a full keyboard width escape ☺️

![touchbar](http://i.imgur.com/kWkKDgd.jpg)

**Comment by qvacua** [comment]
When I get one of those MBPs.... 🙃 One could add more buttons doing, say, stuff. 😏

**Comment by nicosuave** [comment]
I guess that works 😁

**Comment by romaninsh** [comment]
Let's kickstart fund MBP for @qvacua :D.

**Comment by dezzeus** [comment]
Full width isn't necessary (right hand on `hjkl`), let's keep same space to list eventual tabs and switch between them. :)

**Comment by qvacua** [comment]
#528 will land on `develop` soon...
