### ISSUE TITLE
Shift+Space keymappings not respected.

### ISSUE THREAD

**Issue by jordwalke** [qvacua/vimr#36]
I tried my `.vimrc` setup which has normal<Space> and normal<Shift+Space> mapped to tabn/tabprev respectively. It seems shift+Space doesn't work in VimR.

(Admittedly low priority).

**Comment by jordwalke** [comment]
I notice most mac apps get this wrong for some reason - is it some kind of system shortcut that apps have a hard time receiving (like cmd+tab)? Anywhere in the code I could take a peak?

**Comment by qvacua** [comment]
Hm, I don't know since I never used it, however, you could look at `-sendEvent:` in the `VRApplication` class where all events are intercepted and inspected in order to implement the `Cmd-N` tab switching shortcut.

**Comment by jordwalke** [comment]
:+1:

**Comment by jordwalke** [comment]
Is this a won'tfix? Most gui apps allow remapping shift-space.

**Comment by qvacua** [comment]
Ah, this was closed for the MacVim version of VimR and since I don't use the key combo, I did not re-open it. I'll check and re-open.
