### ISSUE TITLE
Freeze after read only buffer enters insert mode

### ISSUE THREAD

**Issue by yannvr** [qvacua/vimr#360]
I'm finally getting around the weird issue I was having using a bare (no plugins) VimR 0.12.0-SNAPSHOT-20161130.1903

1. Start vimR 
2. Open error window (:cope) 
3. Make an insertion without escaping it (that's the bug!)
4. Go back to editing window with mouse and try to close the error window will hang (:ccl)

Then the window becomes unresponsive..

This might sound like an edge case but this happens to me all the time because:

- It seems plugins displaying a status via read only buffer (like AirLine/syntastic etc) will eventually create this scenario  when used (unfinished insert stuck in a readonly buffer)
- Leaving insertion mode without escaping is not unusual when you use the awesome file browser

**Comment by adamalbrecht** [comment]
I'm not sure if this is the root problem I'm experiencing or not, but it has been freezing on me once or twice per day lately. Today it was when I was using the Ctrl-P plugin, but I don't think that is always the case.

When it freezes, the mac app itself seems partially okay (for example, when I hit cmd-w, a native mac dialog pops up asking me if I'm sure I want to close the buffer), but NeoVim is totally frozen.  But then when I try to quit, nothing happens and I have to force-quit the app.

**Comment by qvacua** [comment]
I'm sorry to hear that. I'll look into it.

**Comment by qvacua** [comment]
@adamalbrecht which version are you using?

**Comment by adamalbrecht** [comment]
@qvacua Version 0.11.1 (140)

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.2-SNAPSHOT-20161205.2209-141 : ⚠️ this is for testing purpose only. It may very well be quite unstable. It will show a dialog when the communication between the GUI and the background neovim process breaks. If that happens, could you please post the reason here?

As for the `:cope` crash: if I enter `:cope` and try to insert, neovim does not allow it. Do I have to do something else?

**Comment by qvacua** [comment]
Better https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.1-SNAPSHOT-20161206.2148-141

**Comment by adamalbrecht** [comment]
I used these snapshots all day and it did finally happen again (in the 2nd snapshot).

It was while using [ctrl-p](https://github.com/ctrlpvim/ctrlp.vim). I don't see any sort of dialog, though.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.1-SNAPSHOT-20161207.2041-142

**Comment by yannvr** [comment]
Nice! I can't reproduce the bug :) Thank you!
