### ISSUE TITLE
Update on snapshot channel seems out of sequence and kills vimr

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#365]
macOS: 10.11.6
vimR: 0.12.0-SNAPSHOT-20161130.1903

I'm being offered an update to "0.11.1-SNAPSHOT-20161207.2041". The date looks good, but the version looks like I'm stepping backwards. In any case, I didn't notice this at first, and I tried to do the update.

If I accept the update to that snapshot, then vimr freezes when reopening. If I force quit and manually restart, the same problem occurs. The 0.11.1-SNAPSHOT-20161207.2041 snapshot seems not to work at all for me.

**Edit**: I just tried the same update on a 10.12 machine, and it was fine.

**Comment by qvacua** [comment]
This is probably the same issue as #363 and #366. I'll look into it.

**Comment by qvacua** [comment]
Closing, see #363 for progress.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.1-SNAPSHOT-20161211.1138-143

**Comment by telemachus** [comment]
The latest updates have been fine for me on 10.11.6. Thanks.
