### ISSUE TITLE
Send focus event to the Neovim backend: eg to enable `FocusLost` and `FocusGained` events

### ISSUE THREAD

**Issue by ivalkeen** [qvacua/vimr#368]
Looks like `FocusLost` and `FocusGained` events don't work when switching between VimR window and any other window (e.g. with cmd+tab).

For example, this works in neovim in iTerm, but not in VimR:

```
autocmd FocusLost * echo("Focus Lost")
autocmd FocusGained * echo("Focus Gained")
```

I will be happy to provide more information (or testing) if needed.

**Comment by qvacua** [comment]
The reason is simple: VimR does not (yet) send the focus events to the Neovim backend 😐... Will do.

**Comment by ivalkeen** [comment]
Awesome, thanks!
