### ISSUE TITLE
cwd of the file browser not set correctly when using `vimr`

### ISSUE THREAD

**Issue by mikl** [qvacua/vimr#369]
I usually start VimR by going to my project directory in a terminal and launching it with `vimr composer.json` or similar.

When I do this, the file browser opens my homedir, instead of the folder I launched it from.

This makes it bit hard to use, since there's no obvious way to select a new root for it (other than going up another level) – it's especially bad if I display hidden files:

![screen shot 2016-12-12 at 23 40 58](https://cloud.githubusercontent.com/assets/10263/21119934/20a994ba-c0c5-11e6-8626-57f778004a70.png)

**Comment by qvacua** [comment]
Ups, that's a bug. You should automatically `cd` to the enclosing folder when you use the `vimr` command line tool the first time for a window.

BTW: you can `:cd xyz` to a folder, then the file browser should follow. Or you can use the context menu of the file browser to set the `cwd`.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.12.0-SNAPSHOT-20161213.1835-146

**Comment by qvacua** [comment]
Ups, I messed up, try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.12.0-SNAPSHOT-20161213.1852-147

**Comment by mikl** [comment]
Works great, thanks :)
