### ISSUE TITLE
Keyboard mappings(or Vim-like defaults) for file explorer.

### ISSUE THREAD

**Issue by jordwalke** [qvacua/vimr#37]
I really like how the quickopen has ctrl+p/n to move up and down the results. That's consistent with Mac OS (try searching for a file in finder - ctrlp/n moves up and down the results). But it would be nice to use keymappings in the file explorer that resemble vim (and maybe a bit of NERDTree influence).
- `j/k` to move up and down the file tree.
- `l`  (or `o`) to open a directory.
- `<cr>` to open a file (not a directory). (Same modifier scheme as quick open perhaps).
- Some shortcut to shift focus. between the editor and the file explorer.

I'm sure you'd love to allow customization of the keymappings, but some reasonable defaults would make the file explorer ready for serious use in day-day work until keyboard mappings are implemented.

**Comment by anmonteiro** [comment]
@qvacua I'd love to see this in the Neovim based builds – AFAICT the movements don't work in the file explorer there.
