### ISSUE TITLE
Whether you can allow users to completely hide their own "Files", "Buffers" menu, because it can be more beautiful

### ISSUE THREAD

**Issue by iuunhao** [qvacua/vimr#370]
Whether you can allow users to completely hide their own "Files", "Buffers" menu, because it can be more beautiful

**Comment by qvacua** [comment]
You can hide all the non-Neovim stuff with `Cmd-\` or Menu -> Tools -> "Toggle All Tools". Or do you mean something else?

**Comment by iuunhao** [comment]
你解决了我的问题，感谢您的回答。😊

**Comment by iuunhao** [comment]
You solved my problem, thank you for your answer.😊

**Comment by iovis9** [comment]
Is there an option I can use so it's hidden by default?

**Comment by iovis9** [comment]
bump 👆

**Comment by qvacua** [comment]
After hiding it should be stored. The newest snapshots have additional options to turn some or all tools off in Preferences -> Tools

**Comment by iovis9** [comment]
Before it stored, but one or two versions ago it stopped storing. Should I create an issue?

**Comment by qvacua** [comment]
Ups, I haven't noticed. I'll create an issue and fix it. Thx.

**Comment by qvacua** [comment]
@iovis9 are you sure it does not work? Have you tried the newest snapshot for example? I cannot reproduce the issue.

**Comment by qvacua** [comment]
BTW: the last snapshot allows you to "really" turn off some or more tools via Preferences -> Tools

**Comment by iovis9** [comment]
I wasn't using the snapshots channel. I downloaded the last snapshot and toggling them with the shortcut and restarting would show again the tools, but deactivating them in the settings worked!

**Comment by qvacua** [comment]
@iovis9 you're right. It does not get stored. Will fix it.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F190 (it should now store the state even when you haven't turned off the tools)

**Comment by iovis9** [comment]
Confirmed bug solved. Thanks!
