### ISSUE TITLE
Drawing Bug

### ISSUE THREAD

**Issue by timhatch** [qvacua/vimr#373]
OSX 10.11.6 / VimR Snapshot 150

Issue:
Netrw directory listing not drawn onscreen when opening directory

Steps to repeat:
From GUI - Launch VimR. Open a folder. Resulting VimR window is blank. Typing :h|:q to defocus and refocus the buffer (or opening a new tab and then switching back to the initial tab) causes the Netrw directory listing to be drawn.

Same behaviour when running vimr from the command line.

Last previous snapshot I have on my machine which operates as expected (opening a folder/directory shows a Netrw directory listing) is Snapshot 126 

I see if I can track down the first snapshot where this behaviour comes into play

**Comment by qvacua** [comment]
Thank you for reporting and finding the last working version. I'll look into it.

**Comment by timhatch** [comment]
I tried moving forward through the Snapshots to narrow down where the bug first appears.

Snapshot 130 behaves as expected.
Snapshot 132 is the last that behaves as expected but exhibits poor text anti-aliasing on retina screen.

Snapshot 133 locks up on OSX10.11.6 (as expected given the release notes for Snapshot 134)

Snapshot 134 exhibits the display bug but fixes the anti-aliasing problems of Snapshot 132

**Comment by timhatch** [comment]
Seems to be fixed in Snapshot 160. Was there a reason you didn't close this issue - would you prefer me to?

**Comment by qvacua** [comment]
Oh, I haven't closed it because I haven't done anything yet to fix it. But if it's somehow fixed by some other commits, well, 🙃. Closing...
