### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by timhatch** [qvacua/vimr#376]
Snapshot #152 frequently crashes when working in Full Screen mode with multiple tabs/buffers open.
Usually, but not exclusively occurs when a quick fix window is open.

Background. My normal usage is Full Screen mode, two tabs, one typically containing a neovim buffer in terminal mode and the second with between 2 and 4 open buffers for the files I am working on.

Frequently when using a quick fix window vimr locks up leaving all windows unresponsive. I've disabled various plugins to see if any of these are causing the problem, but without any conclusive result.

I've appended the OSX crash report. Any thoughts as to possible cause or diagnostic steps that I can take to help find the problem?

[crash_report.txt](https://github.com/qvacua/vimr/files/680035/crash_report.txt)

**Comment by qvacua** [comment]
I'm (yet) kind of clueless here.. Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F154... I'll try to hunt it further down..

**Comment by qvacua** [comment]
I think I found a zombie. I'll try to fix it..

**Comment by qvacua** [comment]
I think I got it: Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F155. If ok, I'll build a release.

**Comment by timhatch** [comment]
Just downloaded Snapshot 155. I'll do some tests when I get home tonight

**Comment by timhatch** [comment]
Better, but still unstable, though the behaviour is changed. 
First indication of a problem is that the tab-bar changes appearance (I attempted to attached a screenshot). Once the problem is evident, it is possible to switch between buffers (using the mouse at least) and two switch between tabs. The buffers respond to text input, but it is not possible to save or quit a buffer without quitting the application.

I've tried disabling the Lightline.vim extension in case that was causing the problem, but no joy.

No problems with vim in the terminal or MacVim (but since the issue appears to be in the NeovimSwift framework I wouldn't expect any) 


![screenshot](https://cloud.githubusercontent.com/assets/435261/21627011/c1535830-d20c-11e6-954a-7c6410974d4a.gif)

**Comment by qvacua** [comment]
Hm... I thought I've fixed the problem since I could reproduce (and fix) the crash report you've attached. Can you post your `init.vim`? So if I understand you correctly, the app does not crash, and the background neovim process seems to be alive (since you can normally change buffers/tabs), but it does not react to `:w`? After the problem occurred, when you quit the app without having modified any buffer, does it (incorrectly) say that there are modified buffers?

**Comment by qvacua** [comment]
BTW: I'll still build a release since at least one annoying bug (your original crash report) is fixed. I did not notice it since I almost never use any app in the full screen mode... 😶

**Comment by timhatch** [comment]
It is correct that the app does not crash per se:
- the tabline ceases to render correctly (this is usually the first indication that I have that something has gone wrong)

- Text input continues to be accepted and I can switch between buffers/tabs

- the application doesn't respond to :w or :q 

- quitting the app brings up a wanting about modified buffers, but I'll have to check if the warning is present even where no buffers have changed.

I'll see if I can come up with a repeatable problem: 

Here's my .vimrc / init.vim

[vimrc.txt](https://github.com/qvacua/vimr/files/685296/vimrc.txt)

**Comment by qvacua** [comment]
Could you try http://taewon.de/VimR-376-test.app.zip? (I removed some commits which may cause the behavior, but I'm not sure...)

**Comment by timhatch** [comment]
To add to my previous post.
I'm currently in Snapshot 155 with 2 buffers and a quickfix open all in a single tab (window) - the quick fix is displaying the result from running 
:Dispatch rubocop %
on one of the files.

The app has not crashed, nor has it completely locked up, but it has partially locked up:
- I can enter new text in the focussed buffer
- I can save the text in the focussed buffer using :w
- NORMAL mode commands such as i, o, p, h, j, k, l, dd dw etc all work
- I cannot change the focus between buffers in the initially focussed tab/window
- I can leave INSERT mode using the ESC key or <C-[> but the custom <C-space> mapping that's in my .vimrc does nothing

- I can create a new tab using :tabe and quit that tab using :q

- I cannot exit any of the buffers in the initially focussed tab/window using either :q or the menu equivalent
- Quitting the app via the menu works - no crash

I'll try the test version that you've just posted

**Comment by timhatch** [comment]
The test version seems to be holding up so far - I'll see if I can give it a good thrash tonight.

**Comment by timhatch** [comment]
Hi there.

The test version is more robust, it hung only once this evening.

As noted, I've only recently noticed this problem when using vim-dispatch to assist in running concurrent testing and for linting. I can't reproduce the problem in terminal neovim, so I'm not convinced that its a problem with vim-dispatch itself.

I'll carry on testing

**Comment by qvacua** [comment]
It's definitely a bug I produced... -_- I'll build a release identical to the test version and carry on hunting.

**Comment by qvacua** [comment]
Could you please try http://taewon.de/VimR-376-test-2.app.zip. I refactored some of the neovim backend part...

**Comment by timhatch** [comment]
This seems to fix the problem, the program hasn't hung in the last 24 hours and I have tried to reproduce the problem behaviour.

Side effect is that copy/paste doesn't seem to work reliably. Sometimes it does, then sometimes it doesn't.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F158. (paste fix)
