### ISSUE TITLE
vimr does not render the typo with spell check enabled

### ISSUE THREAD

**Issue by kunxi** [qvacua/vimr#378]
With neovim-0.1.7, the typo is rendered, see below:
![screen shot 2017-01-03 at 12 32 37 pm](https://cloud.githubusercontent.com/assets/152705/21622104/c05fc668-d1b0-11e6-9704-3304f02e0c44.png)

The vimr-SNAPSHOT-155 does not render the typo at all:
![screen shot 2017-01-03 at 12 33 21 pm](https://cloud.githubusercontent.com/assets/152705/21622125/d73d2272-d1b0-11e6-889c-c109cf7ea243.png). 
Though I can use `]s` to jump to the typo.

**Comment by qvacua** [comment]
Related to GH-416?

**Comment by tyrocca** [comment]
I think it is - underlines aren't showing up for me

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F204

**Comment by vervas** [comment]
thanks for this!
