### ISSUE TITLE
vimr renders the status line poorly

### ISSUE THREAD

**Issue by kunxi** [qvacua/vimr#379]
See the screenshot below, the neovim in the console renders the status line correctly, while vimr-SNAPSHOT-155 drops the background color.

![screen shot 2017-01-03 at 12 40 45 pm](https://cloud.githubusercontent.com/assets/152705/21622368/02e000e2-d1b2-11e6-9da0-a715f0a45486.png)

**Comment by qvacua** [comment]
Hm, I thought that I fixed this... Do you have `set termguicolors` in your `init.vim`?

**Comment by kunxi** [comment]
My bad, `set termguicolors` is guarded by the check `if has('gui_running')` which is added then removed. It works perfect now.
