### ISSUE TITLE
when install vimr cli, what's that means?

### ISSUE THREAD

**Issue by Cifer-Y** [qvacua/vimr#381]
![image](https://cloud.githubusercontent.com/assets/4470516/21711373/99cf9692-d429-11e6-9cdd-ae15ac157379.png)

 when I clicked the button:

![image](https://cloud.githubusercontent.com/assets/4470516/21711393/b84541bc-d429-11e6-806e-b7b8defed7a1.png)

what should I do next?

**Comment by mzgnr** [comment]
hi @Cifer-Y it lets you start vimr from terminal like `vimr .vimrc`. Simply on this window go to /usr/local/bin/ with CMD+G and click open :)

**Comment by Cifer-Y** [comment]
@mzgnr ah, thank you, I'm confused with the opening window at first, thanks for your explaination, thanks very much 👍

**Comment by diegodesouza** [comment]
If you install it via `brew cask` you don't have to do this, Come to find out.
