### ISSUE TITLE
After upgrading to 0.12.5 (159), command-line "vimr" is broken

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#382]
1. Quit VimR
2. Go to folder "X"
3. type "vimr"
4. observe that "cwd" is no longer in folder "X", it used to work be fore.
5. type "vimr" in the terminal once more
6. new window is semi-functional.

<img width="1215" alt="screen shot 2017-01-09 at 13 21 11" src="https://cloud.githubusercontent.com/assets/453929/21767896/81291c3e-d66e-11e6-803e-6e6013e712e4.png">

**Comment by romaninsh** [comment]
Problem 6 seems to be fixed in 160, but 4 is still here.

**Comment by qvacua** [comment]
Thanks for the detailed steps. Will do.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F161

**Comment by romaninsh** [comment]
work perfectly.
