### ISSUE TITLE
General html viewer component (as tool)

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#383]
As described in https://github.com/qvacua/vimr/issues/339#issuecomment-268878119:

* add a general web view as a tool (Web Viewer?)
* let the user enter the URL
    - this URL may be a file which does not exist yet (it will probably generated by the user using some Vim plugins)
* reload the URL each time the file is written ("Refresh on Write", on by default)
* keep the scroll position of the web view ("Keep Scroll Position on Write", on by default)

**Comment by butterflyfish** [comment]
use vimr to open one html file, but it still needs to open manually at web viewer. it's better if it's render automatically.
