### ISSUE TITLE
File which contains none ascii characters in its path cannot correctly load and display.

### ISSUE THREAD

**Issue by otsukaresama** [qvacua/vimr#384]
I try opening the same file as mentioned on the title using the nvim command and it works well. However, in the vimr, it just open a new buffer and the content isn't shown. Thus, it may result from vimr.

Another problem is that sometime I open the vimr and it display as below. This happens whether installing plugin startify or not.

![2017-01-12 12 13 03](https://cloud.githubusercontent.com/assets/9023097/21856285/6cf70be6-d85c-11e6-90bc-13668863032d.png)

**Comment by qvacua** [comment]
That looks like a bug that has been recently fixed. What happens if you use https://github.com/qvacua/vimr/releases/tag/v0.12.6-162 ?

**Comment by otsukaresama** [comment]
I am afraid the bug hasn't been fixed thoroughly, because I have already installed the latest release on macOS 10.12.2.

Let me clarify the problem! First, when I open a file whatever its path constains using cli or system menu, there is nothing to show.

As you see, the path is not set correctly.
![2017-01-12 9 24 51](https://cloud.githubusercontent.com/assets/9023097/21873485/ab3ae9f2-d8a9-11e6-8350-4d7a39570d21.png)

![2017-01-12 9 25 48](https://cloud.githubusercontent.com/assets/9023097/21873487/afb82968-d8a9-11e6-9379-956176b90b77.png)

Second, If not quitting the application, just close the window, then open the same file. It looks like this:

![2017-01-12 9 26 27](https://cloud.githubusercontent.com/assets/9023097/21873537/023f97b6-d8aa-11e6-8258-23ef862171cc.png)

PS: This problem is really not urgent or maybe just caused by my configuration.

**Comment by qvacua** [comment]
Can you post your `init.vim`?

**Comment by otsukaresama** [comment]
[init.vim.zip](https://github.com/qvacua/vimr/files/700895/init.vim.zip)

**Comment by otsukaresama** [comment]
I found the cause of this problem. VimR has nothing to blame.  @qvacua As you said, the path related problem had been fixed at the former release. Besides, here is the part of my .vimrc which cause this glitch:

![aa](https://cloud.githubusercontent.com/assets/9023097/22737908/3133b3bc-ee40-11e6-88e4-55c080c9ab28.png)
