### ISSUE TITLE
powerline font for vim-airline display without color

### ISSUE THREAD

**Issue by selaselah** [qvacua/vimr#385]
seemed that all symbols have no foreground with white and background color with black.
wrong display result:
![vimr](https://cloud.githubusercontent.com/assets/1323701/21879630/008a6768-d8d5-11e6-8619-da86d218a04b.png)
same init.vim in terminal
![nvim](https://cloud.githubusercontent.com/assets/1323701/21879637/04f7761a-d8d5-11e6-9166-993132360df3.png)

**Comment by qvacua** [comment]
Have you `set termguicolors` in your `init.vim`?

**Comment by selaselah** [comment]
no I havent
but i use dracula/vim as my custom color, maybe that plug set it.
here is my init.vim
```vim
" use 'junegunn/vim-plug' as plugin manager
call plug#begin()

" Make sure you use single quotes
Plug 'dracula/vim' " 配色
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" Add plugins to &runtimepath
call plug#end()

color dracula " 使用配色
let g:airline_powerline_fonts=1 " airline 使用高级字体

set colorcolumn=81
```

**Comment by qvacua** [comment]
Please add `set termguicolors` to your `init.vim` and try again. This issue should have been fixed by GH-236 and GH-265...

**Comment by selaselah** [comment]
add `set termguicolors` and restart vimr, the issue fixed~

**Comment by kmakat** [comment]
Thank you for the quick replies, but it does not work:

```
" GENERAL EDITOR SETTINGS
syntax enable
" enable true color 2016-03-21
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
"filetype off
set encoding=utf8
set termguicolors

let g:airline_powerline_fonts = 1
```

Is there a specific powerline font I shall use?

**Comment by qvacua** [comment]
Oh, forgot to mention that the `guifont` option is ignored in VimR. You have to set the font in the Appearance preferences pane to a Powerline-enabled font.

**Comment by kmakat** [comment]
Fantastic, works.Thanks!
