### ISSUE TITLE
Powerline fonts in Airline 

### ISSUE THREAD

**Issue by marvel64** [qvacua/vimr#386]
Hi,

Airline is not displayed correctly in VimR but works in Terminal.app and iTerm2.

The settings in init.vim:

```
let g:airline_theme='oceanicnext' "'gruvbox'
let g:airline_powerline_fonts = 1
set guifont=Sauce\ Code\ Pro\ Bold\ Nerd\ Font\ Complete\ Mono:h12
if has("gui_running")
   let s:uname = system("uname")
   if s:uname == "Darwin\n"
      set guifont=Sauce\ Code\ Pro\ Bold\ Nerd\ Font\ Complete\ Mono:h12
   endif
endif
```

Look in terminal neovim:

<img width="983" alt="screen shot 2017-01-12 at 10 51 11 pm" src="https://cloud.githubusercontent.com/assets/1090101/21917963/1ea3cbdc-d91a-11e6-841e-0540d7e6a66b.png">

In VimR, Version 0.12.6 (162):

<img width="734" alt="screen shot 2017-01-12 at 10 51 03 pm" src="https://cloud.githubusercontent.com/assets/1090101/21917944/f48ea1be-d919-11e6-9d06-6a9910cd7849.png">

Thanks for any help!

**Comment by qvacua** [comment]
Please see GH-385.
