### ISSUE TITLE
"Buffers" misleading as a tool name?

### ISSUE THREAD

**Issue by robertgzr** [qvacua/vimr#387]
To me buffers in the vim sense of the word means files loaded into memory for editing.

from the [neovim doc](https://neovim.io/doc/user/windows.html):
> A buffer is the in-memory text of a file.
   A window is a viewport on a buffer.
   A tab page is a collection of windows.

Shouldn't vimr keep true to this logic?

As of right now the Buffers tool shows all opened tabs. I would expect to find the output of `:buffers`.

**Comment by bvgastel** [comment]
Very confusing indeed, and I would like to have this changed. Keep up the good work, I really like VimR!

**Comment by qvacua** [comment]
Ok, this sounds reasonable. I'll see what I can do :)

**Comment by UmkaDK** [comment]
There are so many things that I absolutely love about VimR, but I have to say, renaming "Buffers" tool-pannel to "Opened" in SNAPSHOT-169 left me more confused then before. In an application like VimR there could be so many "opened" things: buffers, files, windows, sockets, etc...

May be the way to approach this would be by splitting this tool onto two: Tabs & Buffers? 

- **Tabs** panel would list all open tabs of the current window, just as "Opened" does now and "Buffers" did before SNAPSHOT-169, 

- and the new **Buffers** panel would display a list of all buffers loaded in the current window (output of `:buffers`)

This way the name of the tool would stay true to the terminology used by NeoVim, describe the tool's purpose, and define the content a user can expect to find inside. This solution would also cater for both, those who prefer to use mainly buffers, and those who are tab-heavy users. 

@qvacua, what do you think?

**Comment by lowerzero** [comment]
Agree with @UmkaDK 
Current implementation of "Buffers" a little bit confusing

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F241

**Comment by qvacua** [comment]
BTW: @UmkaDK sorry for late reply, but Tabs tool is a nice idea 😀

**Comment by UmkaDK** [comment]
@qvacua This is absolutely brilliant. Works like a charm! 
Thanks a lot for doing that!
