### ISSUE TITLE
Can we have iterm as a tab in vimr?

### ISSUE THREAD

**Issue by zubairalam** [qvacua/vimr#388]
It would be nice to have a tab or a buffer which can run iterm(in osx) or some other terminal.

**Comment by otsukaresama** [comment]
You may use ":e term://bash(zsh or some other)" to open a new buffer of terminal. It is provided by neovim!

**Comment by qvacua** [comment]
Closing since as @otsukaresama already mentioned, terminal is built-in in neovim.
