### ISSUE TITLE
Weird behaviour when use "termguicolors" and solarized colorscheme

### ISSUE THREAD

**Issue by adam-stone101** [qvacua/vimr#393]
I'm using vimr 0.13.0 and nvim 0.1.7. When enable termguicolors option together with solarized colorscheme, the whole app seems not functioning, but having some weird behaviours.

**Comment by qvacua** [comment]
I'm using https://github.com/frankier/neovim-colors-solarized-truecolor-only and haven't run into any pronblems...

**Comment by qvacua** [comment]
any feedback?

**Comment by adam-stone101** [comment]
@qvacua Hi. Sorry I don't use github frequently. Now most of the time I use terminal neovim since neovim color support for terminal is pretty good. So I can integrate tmux and other toolchain into my workflow. 

But still thank you for building a nice GUI version. I will try the colorscheme you mentioned when I have time.

**Comment by adam-stone101** [comment]
@qvacua  Hi, sorry for the delayed response again. I tried your suggestion, now both gui and terminal work awesomely, thanks!
