### ISSUE TITLE
Is it possible to fully hide the toolbar?

### ISSUE THREAD

**Issue by rafaelrinaldi** [qvacua/vimr#394]
Even when is closed still bothers me. I'm just wondering if there's a way to fully remove it.

**Comment by qvacua** [comment]
Have you tried the menu item "Tools" -> "Toggle All Tools" (also `Cmd-\`)? Or do you mean something else?

**Comment by rafaelrinaldi** [comment]
@qvacua That's exactly what I wanted. Thank you!
