### ISSUE TITLE
VimR freezes when lots of changes happen in project directory

### ISSUE THREAD

**Issue by jemmyw** [qvacua/vimr#395]
I noticed that whenever I changed a file in my project VimR would freeze, sometimes for a couple of minutes. I tried a few things and have narrowed it down to it happens when the build process I run in the background is running. The build process makes a lot of filesystem changes in a hidden folder and VimR seems really unhappy about this. I've tried adding the directory name into "Files To Ignore" and also just setting the ignore pattern to "*" as I don't use the Open Quickly feature.

Vim or neovim running independently do not freeze.

The freeze manifests itself as the spinner appearing over the VimR window and the activity monitor showing VimR as not responding.

This is with the latest snapshot

**Comment by jemmyw** [comment]
I can also reproduce this issue just by running npm install on a freshly checked out project while VimR is open. It doesn't like a new folder with lots of things in it appearing.

**Comment by qvacua** [comment]
I'll look into it. This is most probably due to the file browser...

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F192

**Comment by jemmyw** [comment]
@qvacua yes I can confirm it works fine with that release. Thank you for looking into it.
