### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#404]
1.  can i hide or remove white bar at two side? i don't need file or buffer or preview.
2. vimr startup is significant slow than macvim. maybe this blame to the window i mentioned.
3. i use airline, and the startup ui is wrong. [wrong screen](http://odlb36gky.bkt.clouddn.com/wrong.png) i install a plugin called denite, when i trigger that and then close the plugin window, the ui is ok [right screen](http://odlb36gky.bkt.clouddn.com/right.png
)

**Comment by qvacua** [comment]
1. Menu -> Tools -> Toggle Tool Buttons
2. Yes, hopefully I can do some optimizations...
3. https://github.com/qvacua/vimr/wiki#initvim

**Comment by FinallyFinancialFreedom** [comment]
thank you very much, it solve all my problems. and the start time is acceptable, while, faster is always better.
