### ISSUE TITLE
Refactor app structure

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#405]
* redux like structure?

**Comment by lcowell** [comment]
I tried release #169 and noticed that there were quite a bit of flicker when I'd save a file (which appeared to request a window be redrawn). I've switched back to release 167 for now, but I'd be happy to provide you with more detail.

**Comment by qvacua** [comment]
I haven't experienced this (yet). Could you tell me when in which circumstances it happens?

**Comment by lcowell** [comment]
The flickering seems to have been greatly reduced. Thank you. I didn't notice that I wasn't able to select text with my mouse in the latest release.
