### ISSUE TITLE
unicode copy and paste bug?

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#408]
hello, now vimR is my chief editor. the unicode support is good, i can input Chinese, copy and paste in vimR, but only in vimR, when i copy some Chinese character into vimR from other app, or copy  chinese character in the vimR to other app, the result is unreadable, something like this:	Ë∑ùÁ¶ª‰∏¥ËøëË∑ØÂè£Ë∑ùÁ¶ª

**Comment by qvacua** [comment]
I tested with Korean and it works fine... Could you post some example text?

**Comment by FinallyFinancialFreedom** [comment]
ok，look these Chinese characters. "码农形状".  When i copy it to system clipboard with `cmd+c` and paste it to vimr with `cmd+v`, i get '????'

**Comment by FinallyFinancialFreedom** [comment]
@qvacua hi, I take a look at  #413, it reminds me that maybe the init.vim causes this problem. So i tried some configuration with his CLK characters,**これはサンプル文字列です**, here is the result:
1. If there is not explicit encodings config there, everything is fine.
2. If `set encoding=utf8`, the problem is not showing either.
3. if init.vim contains script below, i got **???????????** after I copy it to vimR.
```vim
try
    lang en_US
catch
endtry
```
i can't remember why i have this script and what is it for. i have removed it.

**Comment by pjg** [comment]
I have the same issue, however my init.vim does not contain any `lang` definitions.

**Comment by qvacua** [comment]
@pjg Do you still have the problem?

**Comment by pjg** [comment]
@pjg Yes. Unfortunately :/ When I paste `码农形状` in VimR I get `????`.

**Comment by qvacua** [comment]
@pjg Does this still happen when you use `vimr --nvim -u NONE`?

**Comment by HustLion** [comment]
Using `vimr --nvim -u NONE` to start VimR makes copying `码农形状` work. But if I start VimR by clicking the app icon, the issue is the same. And btw, `vimr --nvim -u NONE` loses my theme config.

**Comment by pjg** [comment]
Strangely enough, if I run `VimR` from the icon I cannot paste Unicode characters. However, if I run `/Applications/VimR.app/Contents/MacOS/VimR` from the command line (without any options), it works just fine. Maybe it's because I have proper `locale` vars set in my terminal?
