### ISSUE TITLE
i noticed that :q will not quit vimR, is it a little weird?

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#409]
the window is closed, but the progress in on.
more clarify, :q is the same as cmd+W, may be it should be the same as cmd+Q

**Comment by qvacua** [comment]
Usually in (Neo)Vim-GUIs a GUI window corresponds to a (neo)vim process. However, there's a plan to implement "Quit when the last window is closed"-option like the old VimR, GH-326. Closing this issue.
