### ISSUE TITLE
Add support for $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by UmkaDK** [qvacua/vimr#410]
It would be really nice if VimR could store/find it's configuration files in `$XDG_CONFIG_HOME/vimr/` directory, and fallback to using `~/.vimr_rc` if that directory doesn't exist.

To name just a few of the benefits, this would allow:
- logical separation of the config items (eg: `.config/vimr/init.rc`, `.config/vimr/keybindings.rc`, etc) resulting in a less crowded config file
- easy storage of VimR configurations in a git repository

This change would also make VimR configurations more consistent with neovim, which already supports both $XDG_CONFIG_HOME and $XDG_DATA_HOME.

**Comment by qvacua** [comment]
There are two sources for VimR's config:

- Neovim's config `~/.config/nvim/init.rc`: all (neo)vim related settings
- macOS' preferences system: GUI-related settings like fonts

`vimr_rc` was used in the old VimR (with MacVim backend) and is not used anymore. When we (re-) introduce features like remapping of macOS menu keybindings, they'll be stored in macOS' preferences system.

**Comment by UmkaDK** [comment]
Sounds perfect to me!
... and closing it, since my suggestion is now irrelevant.
