### ISSUE TITLE
Environment variables?

### ISSUE THREAD

**Issue by robertgzr** [qvacua/vimr#412]
I don't know if it is intended behavior?

If I start Vimr with the CLI tool I have my env set in .zshrc

But starting it from the Dock I only get what I have set in .zshenv

**Comment by robsonpeixoto** [comment]
Are there something like this https://github.com/purcell/exec-path-from-shell ?

**Comment by qvacua** [comment]
@robertgzr Yes, this is intended. To use `.zshrc`, we have to launch the background `nvim` using an interactive `zsh` which can cause some problems. However, if you really want you can activate the interactive mode in "Preferences -> Advanced -> Use interactive mode for zsh".
