### ISSUE TITLE
Paste CJK texts from system clipboard converted to "?"

### ISSUE THREAD

**Issue by shuntaroy** [qvacua/vimr#413]
When I paste text that contains CJK character from clipboard to VimR, CJK characters in the text is converted into "?" character. 
This occurs via both `cmd-v`And `"*p`. 
On the other hand, yank CJK string within VimR does not cause the problem.

**Comment by qvacua** [comment]
I tried it with Korean and it works. Could you post an example text?

(Related to GH-408?)

**Comment by shuntaroy** [comment]
Here is an example text in Japanese: これはサンプル文字列です

But I found this problem is come from my `init.vim` or so because the issue does not reproduce without my `.config/nvim`.
Sorry for inconvenience...
If I can find which setting causes this, I will report here.
Thank you for your response.

**Comment by qvacua** [comment]
Closing for now... Please re-open if needed.
