### ISSUE TITLE
Vertical alignment problem of text

### ISSUE THREAD

**Issue by someneat** [qvacua/vimr#415]
I think making the vertical alignment of the text slightly higher would be nice.

<img width="839" alt="screen shot 2017-03-21 at 15 18 56" src="https://cloud.githubusercontent.com/assets/24905881/24166477/bebedc42-0e49-11e7-8340-1e7a01a17a56.png">

On the left is VimR (`v0.13.1-167`) and on the right is MacVim. They're both opening the same text file. VimR has `Line Spacing` option set to `0.90` and MacVim to `:set linespaces=-1` which make both almost identical in line space.

As you might be able to recognize, the vertical alignment of text in VimR is slightly lower such that the lower part of the character of "q", "y" and "g" are truncated whereas that's not the case for MacVim. I think it would be very nice if this can be modified (as in MacVim).

**Comment by minusf** [comment]
<img width="771" alt="screen shot 2018-01-15 at 23 49 44" src="https://user-images.githubusercontent.com/3632883/34964633-d6357cd6-fa4e-11e7-854a-17ad17ffe0dd.png">

as you can see MacVim and vimR take exactly opposite approach when changing `linespace` (20) / `Line Spacing` (2.0) :}  MacVim adds to the top, vimR to the bottom (font: fira code retina, size 13).

i feel they both are cheating: they change the line height, and not the space between lines. i think the correct approach would be to have: 10px margin-top (as in css) font line and 10px margin-bottom. so the cursorline wouldn't be part of the margins, only the font line. that is what `linespacing` really is, not `lineheight`, as it is now.

but perhaps this is a technical limitation.  in any case, i find the MacVim approach a bit more natural as font size grows upwards, not downwards, or in other words have the baseline at the bottom.

unfortunately even line spacing of 1.20 is already disturbing to my eyes as i have a highlighted cursorline and the lineheight becomes skewed. on the other hand, line spacing of 1.00 is sardines in a box, the lines are way too tight...

**Comment by qvacua** [comment]
@someneat you can set the lineheight in Preferences -> Appearance. As for how to "interpret" that value... I'll try some combinations :)

**Comment by gazsp** [comment]
This drives me nuts as well. I have OCD around pixels / margins / padding!

**Comment by gazsp** [comment]
Is there any chance of this being implemented any time soon? Really want to love VimR but the line spacing issue makes everything look terrible.
