### ISSUE TITLE
File browser keybindings

### ISSUE THREAD

**Issue by threkk** [qvacua/vimr#417]
Hello,

I have started using VimR recently, migrating from MacVim. In MacVim, I had set up the the Cmd+n to move around the different tabs, like in Chrome and Firefox. After setting up VimR, I realised that Cmd+1 is binded to toggle the file browser. Is there any ways to disable this keybinding so I can still use Cmd+1 to go to the first tab instead of opening the file broswer? I use NERDTree so it is not a feature I really use.

**Comment by qvacua** [comment]
Created an issue which would solve the problem: GH-418. Closing this one.

**Comment by threkk** [comment]
Thank you very much!!
