### ISSUE TITLE
Changing buffers or tabs clobbers current PWD/LCD/TCD

### ISSUE THREAD

**Issue by jrolfs** [qvacua/vimr#423]
I can try and do some bisecting with the pre-releases but I believe the issue is with **SNAPSHOT-177**. I've been on **166** on a couple machines for quite some time as I tried to upgrade to a prerelease when the Redux redesign was first release and noticed more flickering.

I use VimR specifically as a native wrapper and am not particularly interested in the native GUI integration, however after switching from neovim-dot-app a while back I haven't been able to go back as VimR seems more stable, faster etc.

I just tried to upgrade using Sparkle to the latest pre-release and any time I change buffers it seems to change the working directory to whatever I last set it to (regardless of whether I use `:cd`, `:lcd`, or `:tcd`).

I'm currently at work so I went back to the latest "official" release (167) and that seems to have resolved the issue. Hopefully I have time to provide more context and perhaps isolate the issue to a particular release. I have a feeling it may have to do with the native file explorer (which I don't use).

**Comment by jrolfs** [comment]
http://d.pr/v/6q0Lc

**Comment by evanslify** [comment]
I'd like to upgrade to the latest version but this particular bug is preventing me to do so. Is there anything that we can help with on this issue? @qvacua

**Comment by qvacua** [comment]
I have to first read about `cd, lcd, tcd` since I've only used `cd` till now... 😬 But, I'm on it....

**Comment by jrolfs** [comment]
Awesome, thanks! I did try out the latest release and the issue is definitely specifically with switching tabs. My guess is it has something to do with buffer `pwd` and tab switching more than how you get a particular buffer to said `pwd`. I'll try and post another video of the latest behavior when I have time.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F200

**Comment by evanslify** [comment]
Thank you! I will try it out and get back to you soon.

**Comment by jrolfs** [comment]
Fantastic, seems to work great and getting all the improvements is awesome. Thanks @qvacua! 🙏

I'll wait for @evanslify's feedback but I think this is ready to be closed.

**Comment by evanslify** [comment]
Seems like it's fixed, since I have not encountered this issue after a
day's usage. Cheers @qvacua!

**Comment by jrolfs** [comment]
Indeed, 'tis a great day! ⌨️🗂📈

**Comment by jrolfs** [comment]
Thanks @qvacua for your hard work on this project!

**Comment by qvacua** [comment]
😄
