### ISSUE TITLE
Think about a very thin app containing only the neovim and nothing else

### ISSUE THREAD

**Issue by qvacua** [qvacua/vimr#426]
This contains GH-307 and would be a separate app.

**Comment by qvacua** [comment]
Two separate apps are too much work. Adding Tools pref pane to turn off some or all tools.

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/snapshot%2F183

**Comment by FinallyFinancialFreedom** [comment]
the launch time of v0.14.1-182 is significantly improved !!!👍
