### ISSUE TITLE
command mode cursor disappeared after press left key

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#430]
hi, first of all, the latest version has significantly reduced the launch time. great!👍
There is a problem, when i enter command mode with ":", and input some characters, then i press left arrow key to move the cursor back in order to change some of them, but the cursor disappeared. in fact the block cursor appeared in the main edit window.

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F193

**Comment by FinallyFinancialFreedom** [comment]
Thank you, the problem is resolved. Even better, i think 193 is faster than 191.
