### ISSUE TITLE
autochdir does not work

### ISSUE THREAD

**Issue by adr-ableton** [qvacua/vimr#434]
When opening a file in any way `autochdir` does not cd to the folder of the opened file. This problem does not appear in terminal neovim. The latest non snapshot release did not have that problem.

- Neovim version (vimr, terminal): `NVIM v0.2.0`. 
- VimR version: `Version 0.14.1 (182)`

**Comment by ronen** [comment]
FWIW attempting a workaround via

     au BufEnter *   :silent! lcd %:p:h

doesn't seem to work either

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F188

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F189 (the last build had some other bugs... -_-)

**Comment by ronen** [comment]
Works for me.  Thanks for the speedy response.   (And for vimr!)

**Comment by adr-ableton** [comment]
Thanks for addressing this!
