### ISSUE TITLE
v0.14.1-182 crashes on markdown preview

### ISSUE THREAD

**Issue by lndl** [qvacua/vimr#435]
Hi!

The application crashes when I'm previewing a markdown file and the cursor reaches the markdown panel limit (instead of wrap the line in the editor panel, the app crashes)

**Comment by qvacua** [comment]
Does it happen with the newest snapshot? https://github.com/qvacua/vimr/releases/tag/snapshot%2F183

**Comment by lndl** [comment]
It's related with this issue: #431
I removed the referenced plugin and now it works correctly.
