### ISSUE TITLE
feature request: option to set a dark theme for tool panes

### ISSUE THREAD

**Issue by mattsawyer77** [qvacua/vimr#436]
Obviously low priority request here, but I thought it would be nice to be able to set the tools to have a dark background. I normally use a dark color scheme in neovim and the contrast is a bit distracting.

**Comment by madranet** [comment]
+1 from me.

I use Solarised Light for the editor window and [given the choice] would use Solarised Dark for the file browser pane.  The white BG seems glaring to me, even next to the Solarised Light BG colour. So I can 'feel @mattsawyer77's pain', if he's trying to work with a dark theme in the editor.

While you're sorting that one out, the ability to set a separate colourscheme for the markdown preview pane would be a nice touch too.

**Comment by qvacua** [comment]
Yes, this would indeed be a very nice feature. However, there are more pressing matters... Let's see...

**Comment by robertbenjamin** [comment]
1+, would absolute love for a way to theme the sidebars to be darker.

**Comment by qvacua** [comment]
I'm currently thinking about to completely use the selected color theme for the file browser. Is there any Vim-color-scheme-expert who can tell me which color I should use for which part? 😉

**Comment by mattsawyer77** [comment]
@qvacua don't know if this would help, but you might consider looking at [NERDTree](https://github.com/scrooloose/nerdtree) as a guide.

**Comment by jordwalke** [comment]
Don't forget to eliminate the thin 1px border too ;)

**Comment by qvacua** [comment]
Making some progress: 
<img width="794" alt="screen shot 2017-06-25 at 23 34 13" src="https://user-images.githubusercontent.com/460034/27519944-3e3f8b6e-59ff-11e7-8356-47d7bb2a0888.png">
<img width="794" alt="screen shot 2017-06-25 at 23 36 23" src="https://user-images.githubusercontent.com/460034/27519943-3e3e7be8-59ff-11e7-9a3f-731b2ac20747.png">

**Comment by mattsawyer77** [comment]
looks great.

**Comment by jordwalke** [comment]
Looks great! How can you customize the colors? Or, which colors are reused? It would also be awesome to be able to customize the folder/file icons, or until then possibly disable them. I like the direction!

**Comment by qvacua** [comment]
@jordwalke I'm trying to use the colors defined in the color scheme, eg the foreground and background (and 15% darker version of the background 😀).

I didn't quite get your previous comment about eliminating 1px border; Do you mean the border between the Vim view and the file browser?

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F209 and report the bugs here! 😬

**Comment by jordwalke** [comment]
> I didn't quite get your previous comment about eliminating 1px border; Do you mean the border between the Vim view and the file browser?

Yes, I meant that a lot of editors like `Idea` for the longest time wouldn't let you customize the border between the two and it ended up looking pretty bad on many color schemes. I think your default here (15% darker) is a good starting point.

**Comment by qvacua** [comment]
The latest snapshot https://github.com/qvacua/vimr/releases/tag/snapshot%2F211 uses the `directory` color for folders in the file browser: what do you guys think? I'm not quite sure...

**Comment by robertbenjamin** [comment]
Works great for me!

**Comment by iuunhao** [comment]
I've tried your new version. It's very beautiful
