### ISSUE TITLE
Mouse drag-select and double-click select not working since refactor

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#441]
Upgraded from 166 to 182 and the new UI refactor does not allow to double-click-select or drag-select text.

Click and drag to select text. Cursor follows mouse but does not make a selection.

**Comment by qvacua** [comment]
you have to `set mouse=a` in you `init.vim`. Neovim turned it off by default. They'll turn it on again eventually.

**Comment by lcowell** [comment]
I was having the same issue. This fixed it for me.

**Comment by qvacua** [comment]
From the next snapshot (coming later this evening maybe) on, you won't need to `set mouse`. It'll be set automatically.

**Comment by romaninsh** [comment]
Thanks for adding that!

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F190
