### ISSUE TITLE
Add --line to `vimr`: will result in inverse search for LaTeX

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#443]
It seems that after the redesign as `neovim` based, the `vimr` command line utility lost the ability to specify a line with `-l %line`, breaking LaTeX inverse search from, e.g., `skim`. Would it be possible to restore this?

**Comment by clason** [comment]
A workaround is to connect directly to the `neovim` component via `neovim-remote` (which has to be installed). In Skim, this can be done by setting the preset to `Custom`, command to `nvr`, and arguments to `--remote-silent +"%line" "%file"`.

(This might require using `vim-tex` -- which I recommend anyway -- and setting `g:vimtex_compiler_progname = 'nvr'`.)

**Comment by edgarcosta** [comment]
I think you meant: ```--remote-silent :"%line" "%file"```

**Comment by clason** [comment]
No, I meant what I wrote. (Although an update a while back changed things, so now it's just `+"%line" "%file"`. Your line doesn't work for me at all -- maybe you have an older version of `neovim-remote`?)

**Comment by edgarcosta** [comment]
I am sorry, I was missing a ``-c`` which I added.

With your `+` I was not going to the right line, but instead moving down that number of lines.

**Comment by clason** [comment]
Strange, the `+` version is working fine for me, correct line and all. Maybe a different `neovim-remote` version?

**Comment by edgarcosta** [comment]
I'm also on 1.9.1. 

I went back to trying yours and it also works fine.
I believe I must have mistyped your line with an extra `-c`, and thus the weird behavior.

Sorry for the confusion.

**Comment by clason** [comment]
That's fair, I initially forgot the extra `-c` and wondered why *your* line wasn't working :)

Anyway, good to know that both versions work now.

**Comment by qvacua** [comment]
Please try <https://github.com/qvacua/vimr/releases/tag/snapshot%2F284>. `vimr --line SOME_LINE SOME_FILE` will open the file and go to the given line. If the file is already open in an UI window, that window will be selected and the cursor moved. Note that you have to re-install `vimr`.
