### ISSUE TITLE
Vimr version 0.14.3 on Macos sierra 10.12.4 copy and paste using the mouse not working

### ISSUE THREAD

**Issue by shoaibsufi** [qvacua/vimr#444]
Hi,

Copy and paste using the mouse is not working with Vimr version 0.14.3 on Macos Sierra 10.12.4 - earlier version used to work fine.

I use it a lot as the buffer for taking our formatting on formatted text when I need the plain text.

Thanks

**Comment by qvacua** [comment]
This may be the same issue as GH-441. You have to `set mouse=a` in your `init.vim` or you can use the latest snapshot. :)

**Comment by pjg** [comment]
I have `set mouse=a` in my `init.vim`, however when I start VimR, it sets it to an empty string. When I run `nvim` in the console, it doesn't happen. Using latest (`Version 0.20.0 (238)`).

**Comment by qvacua** [comment]
@pjg Does the issue still persist in the latest version?

**Comment by pjg** [comment]
@pjg nope. It works for me just fine now.
