### ISSUE TITLE
Shift-tab doesn't work in vimr

### ISSUE THREAD

**Issue by pencilcheck** [qvacua/vimr#447]
```
vnoremap <Tab> >gv|
vnoremap <S-Tab> <gv
nnoremap > >>_
nnoremap < <<_
```

In vimr, the first line works but second line moves the cursor up one line instead of decrease indentation like it should be in nvim.

**Comment by mkhl** [comment]
I’m seeing this as well. VimR seems to see the key combination as <kbd>C-y</kbd> instead of <kbd>S-Tab</kbd> (checked using <kbd>C-v</kbd>).

**Comment by mkhl** [comment]
Probably a duplicate of #403, except the problem ist not limited to command mode.
