### ISSUE TITLE
Full Screen.

### ISSUE THREAD

**Issue by jordwalke** [qvacua/vimr#45]
I really like MacVim's fullscreen support. Can we still achieve it while using MacVim framework? It's great how MacVim lets you bypass Mac OS X's extremely long full screen animation. How could anyone get work done while waiting that long for an animation!

**Comment by jordwalke** [comment]
This works, but wow - OS X's full screen animations are incredibly slow! Also, once in full screen cmt+tabbing to another app now becomes slower *each* time you switch! How do you people live with that?

**Comment by kode54** [comment]
Now, on El Capitan, the Fullscreen toggle menu item just makes the app lock up.
