### ISSUE TITLE
Build 0.15.0 (191) ignores "Quit"

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#451]
Right clicking on the dashboard icon and selecting "Quit" only closes all windows but does not actually quit the application.

**Comment by qvacua** [comment]
I cannot reproduce it. Could you describe in more detail when it happens?

**Comment by qvacua** [comment]
https://github.com/qvacua/vimr/releases/tag/snapshot%2F202 could have fixed it...

**Comment by romaninsh** [comment]
Yes, the problem has been fixed some time ago.
