### ISSUE TITLE
Filebrowser support for keyboard shortcuts

### ISSUE THREAD

**Issue by manjuXD** [qvacua/vimr#452]
Does the file browser support any keyboard shortcuts? right now it only seems to be up/down and enter.

j/k for navigation, search etc would be nice to have.

I saw some issues related to this but they seem to be before the neovim rewrite, hence I'm asking this here.

Best regards,
Manju

**Comment by qvacua** [comment]
Duplicate of GH-334, closing this issue.

**Comment by manjuXD** [comment]
Hi @qvacua ,

Did you mean to mention some other issue? the issue you mentioned is for powerline colors and not related to keyboard shortucts not present/working in the filebrowser.

Best regards,
Manju

**Comment by qvacua** [comment]
Oh, sorry, thanks, I meant to mention GH-335: edited the previous comment.
