### ISSUE TITLE
getcwd() returns the user home directory in the VimEnter event

### ISSUE THREAD

**Issue by azag0** [qvacua/vimr#457]
I have a VimEnter event that loads a session based on the current working directory. This doesn't work with VimR because `getcwd()` always returns the home directory at that point. So I assume that the current working directory in the neovim client is set up by VimR only after VimEnter is executed. Is there a way around that?

**Comment by qvacua** [comment]
Could you try https://github.com/qvacua/vimr/releases/tag/snapshot%2F200 and give me feedback whether the issue's still there?

**Comment by azag0** [comment]
I've tried 204 and it works now, cool!
