### ISSUE TITLE
feature request: send to background after closing last window

### ISSUE THREAD

**Issue by hakamadare** [qvacua/vimr#460]
Hello!  I'd like to request a feature in VimR that I found very convenient in MacVim.

Procedure:

1. launch application
2. application is in foreground, new NVIM window is open
3. close NVIM window (either by clicking close button, command-W, `:wq`, some other way)

Current behavior:

4. window closes, VimR application remains in foreground (captures mouse and keyboard input, visible in menu bar)

Desired behavior:

5. window closes, VimR application moves to background, application that was in foreground prior to launch of VimR returns to foreground

To be clear, if any VimR windows remain open, VimR should stay in the foreground; it's only upon closing the last open window that I would like it to move to the background.

**Comment by qvacua** [comment]
Yes, this feature does make sense when you want to use for example the diffmode which will be possible with GH-302. However, I don't know how to just deactivate the app, will hide it...
