### ISSUE TITLE
Return of "cwd" issue (regression)

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#464]
Snapshot: 200

1. Quit VimR
2. Go to folder "X"
3. type "vimr"
4. observe that "cwd" is no longer in folder "X", it used to work before.

Here is similar issue from the past: #382.

Broke in the recent weeks.

**Comment by qvacua** [comment]
I think Snapshot-202 fixes this. At least I could not reproduce it with 202. Try [203](https://github.com/qvacua/vimr/releases/tag/snapshot%2F203) though.

**Comment by romaninsh** [comment]
Fixed in 203 after reinstalling "vimr" tool. Thanks!
