### ISSUE TITLE
vimr command, working directory is wrong

### ISSUE THREAD

**Issue by carl0m** [qvacua/vimr#466]
When opening vimr using the command "vimr", the working directory is set to the home directory instead of the current directory.  Also, vimr --cwd CWD does not set the working directory to CWD as it should.

**Comment by qvacua** [comment]
What version of VimR are you using? If you've upgraded to >= SNAPSHOT-202, you have to re-install the `vimr` command line tool.

**Comment by carl0m** [comment]
I'm using 0.15.2

**Comment by carl0m** [comment]
0.15.2-201 to be precise

**Comment by qvacua** [comment]
Could you please try the latest snapshot (and re-install the `vimr` command line tool)?

**Comment by carl0m** [comment]
Good, the problem is solved in the latest snapshot.

**Comment by qvacua** [comment]
🙂

**Comment by shangsunset** [comment]
Hi @qvacua How should I install the `vimr` command line tool? I saw a `Copy 'vimr' CLI tool` button but dont know what to do next...

Thanks.

**Comment by qvacua** [comment]
@shangsunset you have to put the `vimr` tool in you `$PATH`. For example, if you have `brew` installed, you can put the `vimr` tool in `/usr/local/bin`.

Or you could install VimR via `brew cask`. It will take care of everything.

**Comment by shangsunset** [comment]
@qvacua Thanks a lot for your help!

**Comment by tsvgmi** [comment]
This problem seems to happen again.   I'm running version 0.24.0 (282)
