### ISSUE TITLE
VimR does not source ginit.vim

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#467]
When starting VimR, my `ginit.vim` is not sourced from `~/.config/vim`, only `init.vim`. I can source it manually with either `source ~/.config/vim/ginit.vim` or `runtime ginit.vim`, so it should be fairly simple to add this.

(See https://github.com/equalsraf/neovim-qt/issues/74 and https://github.com/equalsraf/neovim-qt/commit/288d4254cda96e834d09727a8541e7573206f62b.)

**Comment by qvacua** [comment]
To set GUI specific options, you can use the `gui_vimr` flag in your `init.vim`, cf. the description in the [wiki](https://github.com/qvacua/vimr/wiki). Will it suffice?

**Comment by clason** [comment]
Not really, sorry, because I want to share GUI specific options across machines and operating systems (which is one of the reasons I'm using VIM in the first place), and other GUIs (such as `neovim-qt`) use `ginit.vim` (the neovim version of `.gvimrc`) for this.

**Comment by dvcrn** [comment]
Are there any updates on this? I tried sourcing my `ginit.vim` within the `gui_vimr` check but that just crashed the editor for me

**Comment by qvacua** [comment]
The latest release implements this. See #506.
