### ISSUE TITLE
Wrong pwd after opening directory (cwd param ignored)

### ISSUE THREAD

**Issue by cobbweb** [qvacua/vimr#469]
```
=> echo $PWD
/Users/cobbweb/.config/nvim
=> vimr -s --dry-run .
/usr/bin/open vimr://open-in-separate-windows?cwd=%2FUsers%2Fcobbweb%2F.config%2Fnvim&file=%2FUsers%2Fcobbweb%2F.config%2Fnvim
```

After VimR opens (without `--dry-run`), `:echo $PWD` shows `/Users/cobbweb/`

I've disabled my `init.vim`, but even with my config: running `=> nvim .` works as expected. I'm on the latest stable release, Version 0.15.2 (201).

**Comment by qvacua** [comment]
Please try the newest snapshot, this issue should be fixed: https://github.com/qvacua/vimr/releases

**Comment by cobbweb** [comment]
Yes, it appears to be fixed in the latest snapshot. I had to re-copy the CLI tool, otherwise it wouldn't open VimR properly. Thanks!
