### ISSUE TITLE
Sparkle does not upgrade from snapshot to full release

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#471]
Checking for updates from Snapshot 204 tells me 

> You're up to date! 
> 
> VimR Snapshot-204 is currently the newest version available.

even though 205 (specifically release v0.16.0-205) is available. Since are commits between 204 and 205, it would be nice if snapshot users could get those as well without having to wait for 206 (which, given your (highly appreciated) update frequency, will probably be pretty soon, but still...)

Would it be possible to release a snapshot update first and then pushing the same binary to the release channel?

**Comment by qvacua** [comment]
Will do :)

**Comment by clason** [comment]
Nice, thank you very much!
