### ISSUE TITLE
Scrolling non-focused split window with mouse

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#472]
When scrolling in nvim terminal, the buffer which is currently under the mouse is scrolled. Vimr always scrolls active buffer.

This used to work OK, before the changes in scrolling introduced around 190-200.

**Comment by qvacua** [comment]
Yes, this is a bug which is introduced by the latest scroll performance improvement. Will fix, but could take a while...

**Comment by qvacua** [comment]
Please try the latest release: https://github.com/qvacua/vimr/releases/tag/v0.16.1-208

**Comment by romaninsh** [comment]
I'm having problem with 208. Touchbar scrolling is working OK, but physical mouse scrolls wrong window.

**Comment by qvacua** [comment]
My bad: mixed up row and column... Please try https://github.com/qvacua/vimr/releases/tag/v0.16.2-210
