### ISSUE TITLE
Updating during composition events(Chinese, Japanese, etc. IME)

### ISSUE THREAD

**Issue by jtr109** [qvacua/vimr#473]
OS: macOS Sierra Ver. 10.12.5 (16F73)
NeoVim: v0.2.1-dev
VimR: Version 0.16.0 (205)
Happens in native Neovim: No
Happens in terminal or iterm2: No

---

Hello everyone. I got a problem in using.

I am from China. I need to input Chinese characters with Chinese input method app. So I have to switch between Chinese input and English from time to time. Sometimes, I forgot to switch from Chinese to English in normal mode of Neovim. And it will cause the problem. Sorry for only showing the problem, because I do not know the solution.

When using Chinese input in normal mode, such as using a lot of `l` for right moving. The character preparing affect the normal mode should not make effect unless the <kbd>space</kbd> or <kbd>Enter</kbd> be hit. But it not works well in vimr currently. The little word selection window in input method app would not show, and the cursor will move crazy.

I think it might happen in all input method app with input selection.

If my description cannot make you understand. Tell me anytime. Thanks a lot! :smile:

**Comment by iuunhao** [comment]
@jtr109 
I met the same problem with you, also did not find a solution, the terminal does not exist such problems, the use of the terminal, I used `cmd+w` to close the buffres, leading to the closure of the whole process, I hate it, if you find the solution, trouble you tell me.

**Comment by jtr109** [comment]
@iuunhao Well, I am sorry that I have not found the solution.
The characters be hit in the input method app should be shown but not make effect under normal circumstances. But it not work well in VimR temporarily.

**Comment by qvacua** [comment]
If I understand you correctly:You are in insert mode and type something in Chinese. You hit `ESC` and want to move around using for example the home row, however, since your input method is still Chinese, VimR does not understand what you want to do and goes crazy. Is that about right?

If so: Yes, I also have the same problem with Korean input method and I'm planning to address the problem in near future.

**Comment by jtr109** [comment]
@qvacua Yes, you are right. That is the problem I met.

I think it is difficult for VimR to change the layout of input method. But it is great if works.

In my opinion, the input may have 2 steps when typing:

1. The characters hit by users show on a "preview area", which should not make effect on app.
2. When hit <kbd>space</kbd> or <kbd>Enter/Return</kbd>. The characters are placed on the app.

I hope my idea can give you some inspiration.

BTW, It is an awesome app! 😃

**Comment by fanzeyi** [comment]
I am experiencing a similar issue in vimR, but I am not sure if I understand the discussion above correctly. Here is a screencast I recorded demonstrating the issue I have: https://www.dropbox.com/s/5fdj5vync1lwa8a/vimr-ime-bug.mov . The text being typed in the buffer area of the input method is also inserted to vimR. I can also confirm MacVim does NOT have this issue.

**Comment by jtr109** [comment]
What input method do you used? Is it [squirrel](https://github.com/rime/squirrel)?

I had a try with it in vimR with version is 0.20.5 (259) but I cannot recurrence it in insert mode.

The issue confused me only happens in normal mode.

I am afraid they are not same issue. You can create a new issue with more information if you don't mind.

**Comment by fanzeyi** [comment]
@taohonker No, it is not squirrel's fault. I've tested other IMEs, and VimR still can't work with them properly. [Here](https://www.dropbox.com/s/upvyq2sblx6nm32/vimr-bug.mov?dl=0) is a screencast I recorded demonstrating using Apple's Pinyin in VimR. My guess is that the issue is rooted in how VimR handles the keyboard events.

**Comment by SolaWing** [comment]
it's not only affect normal mode, insert mode mapping also being affected. eg: I map insert mode jk to esc, vimr currently execute the mapping immediately, and cause input method's input not work well.

And It's ok in terminal nvim, macvim.

this issue may block other use this editor as a daily editor
