### ISSUE TITLE
Start error reporting

### ISSUE THREAD

**Issue by iuunhao** [qvacua/vimr#478]
This happens whenever I open the program, and of course it doesn't affect the use. I want to know how to prevent this error from happening.

![image](https://user-images.githubusercontent.com/7666692/27675076-10ac08f6-5cdb-11e7-8cb1-5321e72e5880.png)

**Comment by qvacua** [comment]
It seems that your `init.vim` contains an error. After clicking OK, try `:messages`, neovim should print where the error is located in `init.vim`.

**Comment by iuunhao** [comment]
fixed
