### ISSUE TITLE
Emoji + CJK chars are not rendered correctly

### ISSUE THREAD

**Issue by iwinux** [qvacua/vimr#482]
## Env

* macOS 10.12.3
* Neovim 0.2.0
* VimR 0.17.0 (213)

## Text for Test

```
🤓🤓（这是一个测试）
```

## Tried Fonts

* Menlo
* Noto Mono
* PT Mono

## Expected Rendering

Screenshot of Neovim on iTerm2:

![2017-07-02 at 11 14](https://user-images.githubusercontent.com/98864/27766989-a5db4ce6-5f17-11e7-9006-52b4778381c6.png)

## Actual Rendering

Screenshot of VimR:

![2017-07-02 at 11 15](https://user-images.githubusercontent.com/98864/27766992-d14c1ffe-5f17-11e7-954a-32bd7396e8d5.png)

## Additional Info

Emojis can be rendered as expected if there are whitespace around them...

**Comment by lujiacn** [comment]
same issue, cannot input Chinese character.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F219
