### ISSUE TITLE
The title looks inverted with latest version 0.17.0 (213)

### ISSUE THREAD

**Issue by pencilcheck** [qvacua/vimr#485]
Using startify, the color of the title looks weird, I guess it is because it uses black when the background is dark as well.

Using colorscheme https://github.com/rakr/vim-one

<img width="1014" alt="screen shot 2017-07-10 at 1 49 48 am" src="https://user-images.githubusercontent.com/116532/28009939-25f16ee2-6512-11e7-9f6a-2bf24dca82de.png">

**Comment by ashfinal** [comment]
+1 for this.

Just checked atom and emacs. Now I'm quite sure we should use light title when the background is dark, instead of "slightly darker version".

**Comment by iuunhao** [comment]
I have the same problem, but I don't think it's a problem. Of course, light colors don't have such a bad problem.

**Comment by iovis9** [comment]
Yeah, I'm having contrast issues too. But it looks really cool, can't wait!
<img width="588" alt="screen shot 2017-07-18 at 00 35 45" src="https://user-images.githubusercontent.com/6660202/28292791-104cce7a-6b51-11e7-95a6-411c0f3d6d5b.png">

**Comment by qvacua** [comment]
Yes, this is an issue... However I'm not quite sure how to solve this without either
- using a dirty hack to get the view of the title of `NSWindow`
- using a custom window class with a custom title (I'd rather prefer to use a standard `NSWindow` or a minimally extended version of it...)

Quick research on Google does not gave me much on this. Can someone help?

**Comment by iovis9** [comment]
I have no idea of macOS development but I know iTerm 3.1 beta has a similar dark themed window. Maybe it's worth checking out: https://github.com/gnachman/iTerm2

**Comment by qvacua** [comment]
I think I've found a workaround... It's a still a dirty hack, but not sooo dirty... Let's see...

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F227.

**Comment by qvacua** [comment]
Please try [SNAPSHOT-228](https://github.com/qvacua/vimr/releases/tag/snapshot%2F228). (SNAPSHOT-227 has a small bug...)

**Comment by ashfinal** [comment]
@qvacua Wonderful! Works as intended. 👍

**Comment by pencilcheck** [comment]
Snapshot 228 looks ok so far 👍 
<img width="1135" alt="screen shot 2017-09-03 at 3 10 05 pm" src="https://user-images.githubusercontent.com/116532/30007014-0a111de8-90ba-11e7-896d-0771b4cba708.png">

**Comment by qvacua** [comment]
That issue with "Title" at the beginning is also resolved... :)

**Comment by ashfinal** [comment]
![](https://ws1.sinaimg.cn/large/006tKfTcly1fj7j418aclj30qg0dmmzc.jpg)

I'd prefer the title to be "No Name", but "Title" is acceptable. :)

[edited] Just notice the title does't change when the current buffer switches. But it worked on Version 0.19.0 (226). I guess the old code will be back, uh?

**Comment by qvacua** [comment]
The previous behaviour will be restored in the next version. :)
