### ISSUE TITLE
use document types to associate vimr with common text file extensions

### ISSUE THREAD

**Issue by schmeisers** [qvacua/vimr#486]
It would be great to have vimr shown as an option in the "Open With" contextual menu for text files (and shown by default in the "Open with" item info dropdown.  I think this can be done by setting Document Types in the Info.plist: https://developer.apple.com/library/content/documentation/Carbon/Conceptual/LaunchServicesConcepts/LSCConcepts/LSCConcepts.html#//apple_ref/doc/uid/TP30000999-CH202-CIHHEGGE

**Comment by jaywilliams** [comment]
This would be a great improvement. If you check MacVim, you can see the file types they specify in their Info.plist file. It would be rather trivial to add those to VimR.

https://github.com/macvim-dev/macvim/blob/master/src/MacVim/Info.plist

**Comment by qvacua** [comment]
Yes, we should do that... I was just too lazy up to now... 😳

**Comment by qvacua** [comment]
This is a duplicate of #402, closing...
