### ISSUE TITLE
Chrome warning trying to download   v0.17.0-213  29e2aca Verified v0.17.0-213

### ISSUE THREAD

**Issue by ssteinerx** [qvacua/vimr#490]
Big huge red security warning blocking the URL:

Deceptive site ahead

Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

Automatically send some system information and page content to Google to help detect dangerous apps and sites. Privacy policy

**Comment by qvacua** [comment]
??? What's going on there? I tried it and it works (now). Closing, please reopen when the issue re-occurs.
