### ISSUE TITLE
vimr 0.17.0 (213) / 0.18.0 (217) crashes with EXC_BAD_ACCESS (SIGSEGV) when closing from fullscreen with :qall

### ISSUE THREAD

**Issue by piero** [qvacua/vimr#491]
Steps to reproduce with Mac OS X 10.12.6 (16G29):
1) Open the current directory in vimr from terminal (e.g. <code>$ vimr -n .</code>)
2) Open some files (not strictly required)
3) Go fullscreen
4) Do <code>:qall</code>

Attaching the core dump: [vimr_crash.txt](https://github.com/qvacua/vimr/files/1174038/vimr_crash.txt)

**Comment by piero** [comment]
Also attaching my [init.vim](https://github.com/qvacua/vimr/files/1176200/init.vim.txt) for additional details

**Comment by qvacua** [comment]
Unfortunately I cannot reproduce this. Does this also happen with the newest snapshot?

**Comment by piero** [comment]
Yes it happens with Version 0.18.0 (217) as well

**Comment by piero** [comment]
Just realised that it happens only when closing vimr from fullscreen.
I updated the title and the steps to reproduce accordingly, thank you.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F221

**Comment by piero** [comment]
That snapshot crashes as well on :qall, but the stack trace seems to be different: [vimr_snapshot-221_crash.txt](https://github.com/qvacua/vimr/files/1249250/vimr_snapshot-221_crash.txt)

**Comment by qvacua** [comment]
Unfortunately I cannot reproduce this with 221. Does this always happen? Could you post steps to reproduce?

**Comment by piero** [comment]
It always happens, steps to reproduce are:

1. Open VimR
2. Go to full screen
3. Close with `:q` or `:qall` (or `Cmd+w`)

It wouldn't be an issue if I only had one window open (I could close it with `Cmd+q`) but it's a problem with multiple windows as closing one of them .

Let me know if you need additional information, stack traces, etc... and thank you for looking into this!

**Comment by qvacua** [comment]
Hm... Those steps do not cause a crash on my desktop and laptop, both 10.12.6. Yes, maybe stacktraces and your `init.vim`?

**Comment by qvacua** [comment]
Could you try https://github.com/qvacua/vimr/releases/tag/snapshot%2F225?

**Comment by piero** [comment]
Hi, sorry for the delay.

I've tried 226 and the problem still occurs, I'm attaching the trace and my `init.vim`.

Thank you

[vimr_226_trace.txt](https://github.com/qvacua/vimr/files/1263124/vimr_226_trace.txt)
[init.vim.txt](https://github.com/qvacua/vimr/files/1263129/init.vim.txt)

**Comment by tbastos** [comment]
I have the same problem, with v0.19.1 (229).
It only happens in fullscreen, if you have two or more windows open in the tab bar. It crashes when you quit any of the windows.

**Comment by piero** [comment]
Thank you @tbastos for commenting on this, it may be useful if you could upload a stacktrace to help the investigation.

**Comment by piero** [comment]
Sorry for the long silence, just want to say that this problem has gone away in recent releases and would like to thank you for your effort in keeping developing VimR, which is now my favourite dev environment. Really appreciated!!
