### ISSUE TITLE
Shortcuts to toggle tools - Buffers, Markdown, HTML

### ISSUE THREAD

**Issue by GirishPatel** [qvacua/vimr#501]
For file browser toggle we have #-1, similarly it would be good if can have shortcuts for other tools buffer, markdown, html. Might be #-2,#-3,#-4 respectively.

**Comment by qvacua** [comment]
Yes. I think that this should be done in conjunction with #418.

**Comment by januz** [comment]
I came here looking for the feature. Did you have the chance to look into implementing keyboard shortcuts for showing/hiding the markdown preview?

Also, would it be possible to store the size of the markdown preview somehow? At the moment, one has to resize it every time one opens it...

Thanks!!

**Comment by qvacua** [comment]
It will be included in the next snapshot.
