### ISSUE TITLE
Titlebar doesn't change with colorscheme

### ISSUE THREAD

**Issue by robertgzr** [qvacua/vimr#508]
I have the `Preferences > Appearance` option checked and the file browser changes colors but the titlebar stays default.

**Comment by qvacua** [comment]
Which macOS version are you using? I'm on 10.12.6 and it works as intended: When checked, the title bar changes color, when unchecked it's back to default.

**Comment by robertgzr** [comment]
I'm on 10.11.6

**Comment by robertgzr** [comment]
This was resolved with a recent update.
