### ISSUE TITLE
Possibility to use system `NeoVim`

### ISSUE THREAD

**Issue by felipesere** [qvacua/vimr#511]
Hi! I really like `VimR`, excellent work!

I was wondering how much work it would be to use the system (_or homebrew_) installed `NeoVim`.

Here is the `:version` output of `VimR`:

<img width="226" alt="screen shot 2017-08-18 at 09 47 56" src="https://user-images.githubusercontent.com/1850188/29449573-8ed1a2ee-83fb-11e7-9c24-2ac5e116e2ce.png">

And to compare `nvim`:
<img width="208" alt="screen shot 2017-08-18 at 09 54 41" src="https://user-images.githubusercontent.com/1850188/29449601-a761b36c-83fb-11e7-943b-9830f8b80657.png">

If you could point me in the right direction, I'd try to do it myself.

**Comment by qvacua** [comment]
VimR integrates Neovim as library and does not bring a Neovim binary inside it. Thus, as of now, it's not possible to use other Neovim binaries. We're trying to be up-to-date with Neovim's development, cf. the [update-neovim](https://github.com/qvacua/vimr/tree/update-neovim) branch.
