### ISSUE TITLE
Flickering completion menu

### ISSUE THREAD

**Issue by crisidev** [qvacua/vimr#513]
Hello, I use the completion menu a lot and in Vimr every time I move from one value to another of the completion list, it flickers and it makes it very complex to use.

It is not happening on terminal based neovim.

Example GIF: https://media.giphy.com/media/l1J9PIMsB8nywvcKA/giphy.gif

**Comment by squgeim** [comment]
I can confirm this happens when using completion menus with YouCompleteMe.

**Comment by crisidev** [comment]
It happens also using deoplete and neocomplcache. Looks like it is not a YCM only related problem.

**Comment by matipan** [comment]
Hi! I can't reproduce it with deoplete. It's working fine: https://media.giphy.com/media/3ohhwDzogwct3EUjS0/giphy.gif 

I'm using vimr version `0.19.1 (229)`

**Comment by matipan** [comment]
Ok, I have no idea why but it started happening. I'll update when I know which change triggered this

**Comment by jcxia43** [comment]
@crisidev @squgeim Do you have `set relativenumber` ? I had the same issue and it's gone after I turn off the relative number option.

**Comment by crisidev** [comment]
@jcxia43, removing relative numbers fixed the issue for me.

I cannot honestly live without relative numbers :D this looks like a bug between pumvisible and rnu or something like it.

**Comment by crisidev** [comment]
This is not happening anymore with latest releases of VimR, even when using relative numbering. I am going to resolve this.
