### ISSUE TITLE
There is a problem with the exit of the SNAPSHOT-222 version

### ISSUE THREAD

**Issue by azzsh** [qvacua/vimr#515]
The SNAPSHOT-222 version uses "in conjunction with phpcd.vim ":q" command to exit the editor, the editor directly stuck, can not be closed, and prior versions of SNAPSHOT-221 and earlier versions are not very worried about this problem, then more stable version will continue to carry the problem, if you can, I hope you can look at. Thanks very much.

**Comment by qvacua** [comment]
This could be the same problem as #512. Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F225

**Comment by azzsh** [comment]
Thank you, update is too timely, big love, look forward to better features and experience.
