### ISSUE TITLE
On the Mac, the double finger scroll is not smooth

### ISSUE THREAD

**Issue by azzsh** [qvacua/vimr#519]
In MAC, when I use the two finger sliding, rolling screen is not too smooth, feel Caton, hope can be changed.

**Comment by qvacua** [comment]
What kind of files do you usually edit with VimR? The situation of scrolling performance is as following (on my MBP with i5-6267U CPU @ 2.9GHz and in fullscreen mode @ Retina resolution):

1. If the file mainly contains Roman alphabets, the scrolling is very very fast.
2. If the file mainly contains Korean characters, the scrolling is fast to very fast.
3. If the file contains many unusual(?) characters like polytonic greek, cf. #283, the scrolling is very slow.

So I guess in many cases the scrolling will be quite fast. (I did not test with a file mainly consisting of Chinese characters though... Maybe you can post a file you are working on?)

I'm aware that the scroll performance is one of the main KPIs of an editor... To be honest I am not sure whether a big performance leap is possible without (or even with!) a big refactoring of the code base... Anyhow, we'll look out for possible optimizations.

**Comment by azzsh** [comment]
Thank you for your reply, such as the file below in the same configuration in macvim rolling without any problems (not through the <C-f> command scroll, but through the touch panel double finger gestures), but vimR does have this problem, I uploaded pictures and test files, my Mac configuration is as follows:

After the test found. After GUI was enlarged to a certain size. Caton phenomenon began to appear. This problem does not appear in the small size GUI

[PHPExcel.php.zip](https://github.com/qvacua/vimr/files/1291553/PHPExcel.php.zip)

![macvim - effect](https://user-images.githubusercontent.com/5249123/30262307-fef2a98c-9702-11e7-8b24-3b3dd33cac54.gif)

![vimr - effect](https://user-images.githubusercontent.com/5249123/30262322-0b356b9e-9703-11e7-9000-7feefe965056.gif)

Think you!  O(∩_∩)O !

**Comment by james2doyle** [comment]
I found that setting `syntax sync minlines=64` made the scroll performance much better

**Comment by qvacua** [comment]
If you `set re=1`, i.e. using the old regex engine, the scroll performance gets much better. It seems particularly bad for PHP files...
