### ISSUE TITLE
nvim 0.2.1 removes <FocusGained> pseudokey

### ISSUE THREAD

**Issue by justinmk** [qvacua/vimr#520]
In https://github.com/neovim/neovim/pull/7221 the `<FocusGained>` and `<FocusLost>` pseudokeys were removed. Because VimR runs in-process, I would guess this will be easy to deal with. Just like the Nvim TUI, VimR can call `aucmd_schedule_focusgained()`.

```swift
  public func didBecomeMain() {
    aucmd_schedule_focusgained(true)  // however swift calls into C
  }

  public func didResignMain() {
    aucmd_schedule_focusgained(false)
  }
```

**Comment by qvacua** [comment]
Thanks for the heads-up! 🙂
