### ISSUE TITLE
The file browser will be Caton when there are too many files

### ISSUE THREAD

**Issue by azzsh** [qvacua/vimr#521]
More than thousands of files in the directory, Caton makes me unbearable, this is exactly the same with the NERDTree, and will be even slower, so I have no way to stop using easyTree and turn to the built-in and beautiful navigation bar, hope can be improved, such as sumlineText navigation bar

**Comment by qvacua** [comment]
I can imagine what it means, but what do you mean by "Caton"? :)

**Comment by azzsh** [comment]
Yes, often feign death!

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F231
