### ISSUE TITLE
sending msg to neovim failed for 1 with -1

### ISSUE THREAD

**Issue by AlesTsurko** [qvacua/vimr#524]
Hi. I'm using VimR for about 9 months. All this time I'm getting the "```VimR encountered an error from which it cannot recover. This window will now close.
Reason: sending msg to neovim failed for 1 with -1```" on the each start. This error is really annoying because of the alert on top of a working window with loaded content, that I should close and then reload the app (the alert disappears after the reload). There was a release in which this issue was rare, but starting from some of the last releases I became to get this on the each start again.

**Comment by qvacua** [comment]
Hm... That's unfortunate. Does this also happen when you do the following?

* Launch the latest VimR and install the `vimr` command line tool.
* Open Terminal and execute `vimr -u NONE`

**Comment by AlesTsurko** [comment]
Looks like something in my dotfile caused the problem. I can't say what exactly, but after editing the file the problem has disappeared. I'll close the issue for now. Thanks.
