### ISSUE TITLE
how to change the NeoVim font

### ISSUE THREAD

**Issue by DemonCloud** [qvacua/vimr#526]
how to change font setting

**Comment by azzsh** [comment]
You can set the menu there, the specific location is Preferences - > Appearance - > Default Font.

**Comment by DemonCloud** [comment]
@qvacua 
can't set  Mac OS X  dfont( Bitmap font )

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20201121.103800 and re-open when the issue persists.
