### ISSUE TITLE
Basic support for keyboard mappings.

### ISSUE THREAD

**Issue by jordwalke** [qvacua/vimr#53]
I'm not sure what the best way to configure these are (maybe a `~/.vimr` file) but it would be great to be able to control how to toggle the file nav (and focus/unfocus it). Similarly, configuring the shortcut for quick open would be great as well.

**Comment by jordwalke** [comment]
I was going through the issues I've filed and I noticed that the majority of the issues I've filed are related to customizing keyboard interactions. Since Vim is all about the keyboard (and customization of keyboard interactions) would it make sense to at least provide some quick and dirty solution to read them in from a config file in `~/`? I noticed this is the only thing that is preventing me from using VimR in my day-to-day job. Other than that, it's a fantastic experience that I really wish I could enjoy.

**Comment by qvacua** [comment]
Let me see for the next release whether I can squeeze it in :smile:

**Comment by jordwalke** [comment]
Oh that would be so cool!

**Comment by qvacua** [comment]
Try the newest snapshot: http://taewon.de/snapshots/VimR-20150201-1236.tar.bz2 and the preliminary doc for [custom key bindings](https://github.com/qvacua/vimr/wiki/Custom-Key-Bindings)

**Comment by jordwalke** [comment]
Yes! I cannot way to try this!
