### ISSUE TITLE
Closing :help with ⌘-W prompts for confirmation

### ISSUE THREAD

**Issue by reidab** [qvacua/vimr#530]
This seems odd:
1. `:help<CR>`
2. `⌘-W`
3. The current buffer has unsaved changes!

This works as expected, without prompting:
1. `:help<CR>`
2. `:q<CR>`

**Comment by qvacua** [comment]
This issue is the same as #571. Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F240
