### ISSUE TITLE
Can't hide tab or tab bar

### ISSUE THREAD

**Issue by asbjornh** [qvacua/vimr#532]
I accidentally hit cmd+shift+t, and a weird bar appeared on top of airline. You can see in the following screenshot that it repeats the filename in black text:
![screen shot 2017-10-04 at 13 28 24](https://user-images.githubusercontent.com/13281350/31173568-5e0fb2fe-a908-11e7-9a67-af5cbd6d5dec.png)

From the View menu I can see that what I did was "Show Tab Bar" (which looks to be the same thing that you can do in many macOS-apps like Terminal and Finder):
<img width="224" alt="screen shot 2017-10-04 at 13 28 36" src="https://user-images.githubusercontent.com/13281350/31173567-5e0a730c-a908-11e7-911a-6c75eed73d8a.png">

Problem is, the button is now greyed out, and there's no "Hide Tab Bar" option anywhere, and no "Close Tab" or anything like that (cmd+w doesn't help), so I'm basically stuck with that weird thing.

**Comment by qvacua** [comment]
Ah... I did not think about the tab bar of Cocoa... Will do... (I'll probably just disable the tab bar..)

**Comment by asbjornh** [comment]
Gonna close this now, since it's been nearly two years and this issue is cluttering up my Issues list and the `ready` label seems to suggest that it's been fixed 😊
If this still needs to be an open issue I'd be really grateful if a new one was created in favour of reopening this!

**Comment by j-rahman** [comment]
I do not see a "Hide Tab Bar" option anywhere on a fresh install of `vimr 0.44.0,20230103.174333` as of this writing. I would like to be able to hide the tab bar when there is only one tab open. That should be the default behaviour anyway. Could you please reopen this issue and fix it once and for all? Thank you.
