### ISSUE TITLE
Neoformat plugin not working with VimR

### ISSUE THREAD

**Issue by Snazzyham** [qvacua/vimr#540]
Not sure if this is a Neoformat issue or a VimR issue, but Neoformat works fine when I use it in terminal Nvim, but for some reason doesn't run in VimR. It just says "No change necessary", even when there are changes to be made. Same file, same formatting, gets formatted in terminal nvim but not in VimR.

**Comment by jannschu** [comment]
Might be related because similar API is used probably: `rustfmt` does not work either in VimR (but in terminal). Here no effects are visible.

**Comment by qvacua** [comment]
Do you still have the issue @Snazzyham ?

**Comment by Snazzyham** [comment]
Just tested sorry, it works fine. Closing issue now.
