### ISSUE TITLE
Markdown preview not working 

### ISSUE THREAD

**Issue by sts10** [qvacua/vimr#541]
Hello! Just trying VimR again after a bit. Love the idea of a built-in Markdown preview, but I'm only seeing this error with an emoji and the words "no preview..."

![screen shot 2017-10-20 at 9 14 16 am](https://user-images.githubusercontent.com/4871664/31822559-29eca830-b577-11e7-93fe-ca155a95e00b.png)

I am editing a Markdown document (I confirmed that `:set ft` gives me `filetype=markdown`). Are there any dependencies I might need to make the preview work? Or settings to configure first?

The HTML preview does appear to work. 

VimR Version 0.19.1 (229)
macOS 10.11.6

And if relevant, on the command line `nvim --version` gives me "NVIM v0.2.0"

**Comment by qvacua** [comment]
VimR only shows the preview if the file has `md` or `markdown` as its extension. Maybe you have a different one?

**Comment by sts10** [comment]
Ahhh I use `.mdown`. Should have checked-- stupid of me. Thanks so much.
