### ISSUE TITLE
Setting to treat Option or Alt key as Meta instead of modifier

### ISSUE THREAD

**Issue by viktorstrate** [qvacua/vimr#543]
Mac terminal has this feature, under Settings -> Profiles -> Keyboard -> "Use Option as Meta Key", iTerm2 has it too.

This would allow all keys, not just Arrow keys and special signs, to be mapped together with `Option`,
example `<M-j>` would be the same as pressing `Option` + `J`

**Comment by qvacua** [comment]
Sorry, re-opening: this is different than #314.

**Comment by qvacua** [comment]
Please try the latest release: <https://github.com/qvacua/vimr/releases>. You can find the new option in the Keys preferences.
