### ISSUE TITLE
Focus is lost after entering fullscreen mode

### ISSUE THREAD

**Issue by interstellar716** [qvacua/vimr#545]
The VimR window looses focus when entering fullscreen mode. `Cmd-Tab` to VimR doesn't help, you have to click on it to reacquire focus. The issue persistes even if I disable all my plugins and `init.vim` file.
It looks like the kind of problem that most users would face but I didn't find any other issues related to this. I'm sorry if that's not the case.

VimR 0.19.1-229
macOS High Sierra 10.13.0

**Comment by tjdoc** [comment]
I'm also experiencing the same issue.

**Comment by dgorodnichy** [comment]
+1

**Comment by interstellar716** [comment]
I've just tested and looks like the issue is fixed.
Thank you very much for your time and effort!

VimR 0.20.4-256
macOS High Sierra 10.13.2
