### ISSUE TITLE
Crashes when useing YouCompleteMe

### ISSUE THREAD

**Issue by RRRRRm** [qvacua/vimr#553]
the crash report is as follows

2017-11-04 23:56:13.739 VimR[42024:1174467] server started on http://localhost:65446
2017-11-04 23:56:20.729 VimR[42024:1174501] adding file:///Users/bear/ to monitoring
2017-11-04 23:56:21.313 VimR[42024:1174467] *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff520d82fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff78a49c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff52169d6d +[NSException raise:format:] + 205
	3   AppKit                              0x00007fff4ff33319 _NSRunModal + 484
	4   AppKit                              0x00007fff4f9137ad -[NSAlert runModal] + 240
	5   SwiftNeoVim                         0x000000010a82ace7 _T011SwiftNeoVim0bC4ViewC06launchbC033_ED7F0BC1D60B2DEA7686777EA9206B78LLyAA4SizeVFTf4xn_n + 519
	6   SwiftNeoVim                         0x000000010a82adf1 _T011SwiftNeoVim0bC4ViewC12setFrameSizeySC6CGSizeVFTf4xn_n + 241
	7   SwiftNeoVim                         0x000000010a829dbf _T011SwiftNeoVim0bC4ViewC12setFrameSizeySC6CGSizeVFTo + 47
	8   AppKit                              0x00007fff4f6a7a52 -[NSView setFrame:] + 371
	9   AppKit                              0x00007fff4ff18cf2 NSViewActuallyUpdateFrameFromLayoutEngine + 392
	10  AppKit                              0x00007fff4f6b5122 NSViewLevelLayout + 385
	11  AppKit                              0x00007fff4ff189e4 _NSViewLayout + 587
	12  AppKit                              0x00007fff4f71419b -[NSView _layoutSubtreeWithOldSize:] + 437
	13  AppKit                              0x00007fff4f714414 -[NSView _layoutSubtreeWithOldSize:] + 1070
	14  AppKit                              0x00007fff4f714414 -[NSView _layoutSubtreeWithOldSize:] + 1070
	15  AppKit                              0x00007fff4ff1f740 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1380
	16  AppKit                              0x00007fff4f731987 -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 163
	17  AppKit                              0x00007fff4f718b1e -[NSWindow _setFrame:updateBorderViewSize:] + 1124
	18  AppKit                              0x00007fff4f730eff -[NSWindow _oldPlaceWindow:] + 604
	19  AppKit                              0x00007fff4f7304ae -[NSWindow _setFrameCommon:display:stashSize:] + 3108
	20  AppKit                              0x00007fff4f72f87d -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
	21  AppKit                              0x00007fff4f72f798 -[NSWindow setFrame:display:] + 67
	22  VimR                                0x000000010a687e27 _T04VimR10MainWindowCAC7RxSwift10ObservableCyAC5StateVG6source_AA13ActionEmitterC7emitterAH5statetcfc + 17735
	23  VimR                                0x000000010a5ee72c _T04VimR6UiRootC13newMainWindow33_8ECA61C70B364ED2D49DC97051709EC7LLAA0eF0CAG5StateV4with_tFTf4gn_n + 3500
	24  VimR                                0x000000010a5f12d1 _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_Tf4gn_n + 4385
	25  VimR                                0x000000010a5e51d4 _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_ + 964
	26  VimR                                0x000000010a5ed049 _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_TA + 41
	27  VimR                                0x000000010a675312 _T04VimR8AppStateVIxx_ACIxi_TR + 578
	28  VimR                                0x000000010a5ed0a3 _T04VimR8AppStateVIxx_ACIxi_TRTA + 51
	29  RxSwift                             0x000000010aa60d28 globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 19736
	30  RxSwift                             0x000000010aa60a69 globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 19033
	31  RxSwift                             0x000000010aa60bdc globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 19404
	32  RxSwift                             0x000000010aa79ad7 __swift_destroy_boxed_opaque_existential_0 + 9383
	33  RxSwift                             0x000000010aa66323 globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 41747
	34  RxSwift                             0x000000010aa6650a globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 42234
	35  RxSwift                             0x000000010aaf21d1 globalinit_33_932BAA1B71BEB3FA14752E35DCF55AA2_func17 + 37649
	36  RxSwift                             0x000000010aaf2bb9 create_generic_metadata_ObserveOnTm + 169
	37  RxSwift                             0x000000010aaf2c6c create_generic_metadata_ObserveOnTm + 348
	38  RxSwift                             0x000000010aa5bfb6 block_destroy_helper + 294
	39  RxSwift                             0x000000010aa5be40 globalinit_33_E3BC7F891F5DA88E0E2A9C34CB16220E_func3 + 1408
	40  RxSwift                             0x000000010aa42550 swift_rt_swift_dynamicCastClass + 13424
	41  libdispatch.dylib                   0x00007fff796066cd _dispatch_call_block_and_release + 12
	42  libdispatch.dylib                   0x00007fff795fee88 _dispatch_client_callout + 8
	43  libdispatch.dylib                   0x00007fff7960a471 _dispatch_main_queue_callback_4CF + 1148
	44  CoreFoundation                      0x00007fff520909c9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	45  CoreFoundation                      0x00007fff52052c4a __CFRunLoopRun + 2586
	46  CoreFoundation                      0x00007fff52051fa3 CFRunLoopRunSpecific + 483
	47  HIToolbox                           0x00007fff51371866 RunCurrentEventLoopInMode + 286
	48  HIToolbox                           0x00007fff513714df ReceiveNextEventCommon + 366
	49  HIToolbox                           0x00007fff51371354 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	50  AppKit                              0x00007fff4f66ea23 _DPSNextEvent + 2085
	51  AppKit                              0x00007fff4fe03e6c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	52  AppKit                              0x00007fff4f663831 -[NSApplication run] + 764
	53  AppKit                              0x00007fff4f6329d2 NSApplicationMain + 804
	54  VimR                                0x000000010a571dd9 main + 9
	55  libdyld.dylib                       0x00007fff79638145 start + 1
	56  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ELLIOTTCABLE** [comment]
So, I'm seeing this with a whole host of unrelated configuration options and lines.

I've tried re-installing VimR from scratch; I've tried in everything from **v0.17.0-213* to **v0.20.0-238**; I've tried removing arbitrary combinations of plugins. Whatever I do, I can get VimR to open with *no* configuration, but almost no combination of even basic configuration options or plugins, from my setup, will convince it to launch.

Here's some MWE .vimrcs which cause it to explode every single time — but I'm bisecting through my config, and it appears that there's another bajillion such examples. All of these examples work fine in tui-nvim — indeed, my entire config, with all of the breaking examples, works fine on a daily basis. Something's very fundamentally broken.

1. Trying to highlight `EndOfBuffer`

       " ~/.vimrc
       hi EndOfBuffer ctermbg=fg
       hi! link EndOfBuffer SignColumn

2. Testing for the presence of VimR

       if has('gui_vimr')
          set showtabline=0
          let g:lightline.enable.tabline = 0
       endif

This is a *complete* blocker; I can't find any minimal subset of my configuration that will actually reliably launch VimR, right now. O_O

**Comment by ELLIOTTCABLE** [comment]
Ah! I spoke too soon! (And also, I'm an idiot.)

It's pretty clear that VimR crashes *when there's a vim-script error during launch* — i.e. what terminal-nvim would display like this …

<img width="453" alt="screen shot 2017-11-28 at 14 40 41" src="https://user-images.githubusercontent.com/200/33348190-3ae41e42-d44a-11e7-9f13-642f900cf641.png">

… VimR will immediately crash, with:

<img width="464" alt="screen shot 2017-11-28 at 14 46 52" src="https://user-images.githubusercontent.com/200/33348366-071c8f62-d44b-11e7-9f59-b8eecb63f721.png">

(All of the issues causing this in my own config were situations where VimR configuration needed to differ from terminal configuration — for instance, `ctermbg=fg` fails in the GUI for obvious reasons; and `g:lightline.enable` didn't exist, but that bug was guarded on `has('gui_vimr')` … etceteras.)

@RRRRRm, you might want to try your configuration in terminal-NeoVim — especially, unguarding any GUI-specific sections, to see if you can surface any bugs in them?

Meanwhile, the title of this Issue should probably be changed to reflect the actual bug: errors in configuration cause crash-on-launch before the UI even renders, with no useful information.

**Comment by kenny-evitt** [comment]
@RRRRRm Would you please edit your initial comment and format the exception info as code? That would make it easier to scan.

**Comment by qvacua** [comment]
I'll first fix the issue described by @ELLIOTTCABLE

**Comment by qvacua** [comment]
Please try the latest snapshot and re-open if the issue persists: https://github.com/qvacua/vimr/releases
