### ISSUE TITLE
How to configure vimr?

### ISSUE THREAD

**Issue by laur1s** [qvacua/vimr#556]
Hi,

How can I configure vimr similarly as editing ~/.vimrc for vim?

I found out that the file should be ~/.vimr_rc however my rvim crashes with this config
` syntax on
 filetype plugin indent on
 set background=light
 colorscheme solarized`

**Comment by bsia** [comment]
There is a ~/.config/nvim/init.vim file you can use pretty much like a
.vmrc file.

**Comment by qvacua** [comment]
`.vimr_rc` file is not supported anymore (it was a feature of the old MacVim-based VimR). Closing...

**Comment by lovepocky** [comment]
@qvacua How can i change the shortcut of vimr now ?

**Comment by qvacua** [comment]
@lovepocky It's not yet possible. I hope to find some time soon to implement it...
