### ISSUE TITLE
Snapshot-234 with neovim 0.2.1 cannot use Lua interpreter, eg `:version` closes the window.

### ISSUE THREAD

**Issue by mortonfox** [qvacua/vimr#559]
This started happening in snapshot-234. (under OS X High Sierra, if it matters)

When I invoke the ```:version``` command, an error message appears and the window disappears before I can read that message.

**Comment by qvacua** [comment]
I'm having problems with the Lua interpreter of Neovim 0.2.1... Hopefully it can be resolved soon...

**Comment by qvacua** [comment]
Please try the snapshot 235.

**Comment by mortonfox** [comment]
I don't see this problem any more in snapshot 235. Thank you.
