### ISSUE TITLE
--nvim doesn't seem to work very well

### ISSUE THREAD

**Issue by gglanzani** [qvacua/vimr#567]
If I do

```
vimr --wait -s some_file.txt --nvim
```

Then vimr starts in insert mode, and the beginning of the file is truncated. I'm using the latest snapshot.

**Comment by qvacua** [comment]
If you use `--nvim` option, then all other arguments, except `--wait`, are forwarded to the backend `nvim` process. Thus, your command will forward `-s` to `nvim`, which would interpret `some_file.txt` as normal mode commands.

Closing...
