### ISSUE TITLE
crash when vimrc have echom

### ISSUE THREAD

**Issue by xiehuc** [qvacua/vimr#569]
```
echo "echom 'hello'" > /tmp/vimrc
vimr --nvim -u /tmp/vimrc
```

reproduce it

**Comment by ELLIOTTCABLE** [comment]
Looks like a duplicate of #553 (see [my comment](https://github.com/qvacua/vimr/issues/553#issuecomment-347690154)!)

**Comment by qvacua** [comment]
@xiehuc do you still have the problem?

**Comment by xiehuc** [comment]
use newest version never crash，thank you👍👍

发自我的 iPad
