### ISSUE TITLE
Mistreating NerdTree and Startify buffers as files with changes

### ISSUE THREAD

**Issue by kcmannem** [qvacua/vimr#571]
Whenever you try quitting(by pressing the red traffic light button) startify or nerd tree, Vimr treats the buffer as an actual file and asks you if you want to discard the changes in a dialog. This gets very annoying very fast.

**Steps to Reproduce**
- open an empty buffer
- invoke NerdTree sidebar
- close vimr window using red traffic light exit button
![screen shot 2017-11-26 at 7 45 37 pm](https://user-images.githubusercontent.com/9054726/33246462-aa10b438-d2e2-11e7-841d-137a055ce926.png)

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F240

**Comment by 9mm** [comment]
@qvacua this works perfectly for me! Can this be added into the latest version?
