### ISSUE TITLE
scrolling with trackpad too sensitive

### ISSUE THREAD

**Issue by kcmannem** [qvacua/vimr#572]
On Macbook Pro trackpads, using the two finger scrolling gesture to navigate up and down the page is too fast. It becomes very hard to be precise. There should be a setting which allows user customization of the sensitivity.

**Comment by Quiark** [comment]
Or just use system default? That seems to work pretty well for everything else on macOS.

**Comment by minusf** [comment]
if you mean the 'tracking speed' in system preferences, it does not affect the scroll speed for me. it's still too fast.  only the mouse cursor is moving around more slowly. once i start scrolling with 2 fingers, it's crazy fast again.

**Comment by Quiark** [comment]
No, I mean I have the same problem as OP, it's too fast. But every other app on my Mac behaves well without configuring each of them. So the I would specify the problem as "make vimr scroll equally fast as other apps"

**Comment by minusf** [comment]
i have found the actualy scroll speed setting under 'Accessiblity' -> 'Mouse and Trackpad'. so yes, VimR should honor this setting, it does not at the moment.

**Comment by michaelfresco** [comment]
It was my hope that VimR would offer scrolling more akin to Sublime, but it is not. Actually, VimR's scrolling is really really slow compared to Sublime.

**Comment by minusf** [comment]
not sure about an external mouse, but the internal trackpad is way to sensitive.

**Comment by michaelfresco** [comment]
Are you aware of the `Mouse Options...` menu under Accessibility? It has a slider for scrolling speed.

**Comment by minusf** [comment]
have you read the whole thread?  the trackpad speed settings have no effect in VimR... at least not for me.

**Comment by qvacua** [comment]
VimR does not use the standard scroll mechanism of macOS, but has got a custom one due to neovim's UI binding structure. The tuning will be implemented eventually. :)

**Comment by edgarcosta** [comment]
I have noticed the same problem on my laptop.
However, things are way worse with a magic mouse, it requires a tremendous effort to be a magic mouse with vimR.

Couldn't one use the macOS mechanism to smooth out the signal before passing it to the custom mechanism?

**Comment by qvacua** [comment]
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2F263 and open the Advanced preferences. There's a slider to set the sensitivity.

**Comment by slmjkdbtl** [comment]
is there a way to turn off scrolling with trackpad entirely? it feels weird when `nowrap`

**Comment by ekstasis** [comment]
The slider doesn't seem to be changing the scroll speed for me, which is still way too fast.  Let me know if how I can help with more information.  

Version 0.24.0 (282)
Macbook Pro 13" Early 2011
macOS High Sierra 10.13.5

**Comment by nilsbecker** [comment]
almost the same as @ekstasis but on an iMac with an external Apple trackpad connected. scrolling is always too fast even at the leftmost setting, but the speed does change a little bit when the slider is used.

**Comment by edgarcosta** [comment]
For me on a iMac, with a magic mouse, it is still way too fast.
On a newer macbook pro, things work fine

**Comment by nilsbecker** [comment]
there is a simple logic to the scrolling normalization on trackpads that is used on native apps AFAIK. namely, the page should scroll by the same distance that the curse would have moved with the same gesture in non-scroll mode. that way, one gets the illusion of moving the page by putting a finger on it an moving a piece of paper over the desk.

**Comment by dylan-chong** [comment]
The slider on the minimum setting are still too fast

**Comment by ahti** [comment]
@qvacua you might be able to use an invisible scroll view without any content displayed, just to get the scroll offset and forward that to nvim. That should give you nice native-feeling scrolling regardless of whether the user is using a mouse, trackpad or whatever. Apple have actually shown similar things in WWDC sessions to get native scrolling behaviour into OpenGL games on iOS.

**Comment by 9mm** [comment]
Yes its still very fast. If you leave the window open the slider seems to affect the speed but then it reverts back after a few seconds. It's like the slider works 10% of the time and then its way way too fast

**Comment by dlejay** [comment]
Same issue: too fast, does not feel like all the other macOS apps. And the slider has no effect.

**Comment by georgeharker** [comment]
definitely very fast.  I'd love to see a scroll bar / standard view used to contain the text so it felt more mac like.
