### ISSUE TITLE
Probably a bunch of known issues

### ISSUE THREAD

**Issue by kenny-evitt** [qvacua/vimr#576]
Yesterday VimR stopped working for me. I couldn't open files via the `vimr` CLI command nor could I get even a single window to appear even after opening the app directly. I had recently done 'two' major changes to my system that could *definitely* be responsible: I upgraded to the latest Mac OS (High Sierra), and I installed Xcode (for the first time on this computer).

In particular, I suspect installing Xcode might be responsible for a lot of the apparent problems I've been having. My evidence for this suspicion is mainly that Xcode highjacked `git` and broke it until I'd agreed to the Xcode EULA. [That is a really terrible 'design decision' and incredibly arrogant to effectively assume that I'd only use Git for Xcode projects.] I wouldn't be surprised if installing Xcode broke other programs or scripts.

But I was also running an old version of VimR – version 8 (?)! #575 seemed to cover my (initial) problem so I downloaded and installed the v0.20.0-238 build as suggested. That (somehow) worked, at least for a little while.

Next, my color scheme wasn't being loaded or applied (or something). I setup a new scheme and in the *init.vim* file instead of my *.vimrc* file. That worked too for a little while. But then VimR crashed. And then I couldn't re-open VimR without it crashing. #553 seems to be what I'd run into in that case. I commented out the line in my *init.vim* that sources my *.vimrc* file and that seems to have fixed VimR crashing.

**Comment by kenny-evitt** [comment]
This seems very much not-actionable but I wanted to describe the entirety of my recent experiences in one place.

**Comment by qvacua** [comment]
Could you try the latest release? https://github.com/qvacua/vimr/releases

**Comment by kenny-evitt** [comment]
I just upgraded to 0.20.3 (255). The `vimr` script still doesn't work:

```shell
$ vimr a-text-file 
108:193: syntax error: A to:the front window can’t go after this openFilesInFrontmostWindow(/Users/kenny/a-text-file). (-2740)
```

**Comment by kenny-evitt** [comment]
I un-commented the line in my *init.vim* that sources my *.vimrc* and now VimR isn't crashing.
