### ISSUE TITLE
Crash on start.

### ISSUE THREAD

**Issue by antonshiryaev** [qvacua/vimr#578]
Terminal NeoVIM works.  `vimr --nvim -u NONE` also works.

Terminal output:
`2017-12-05 20:54:30.238 VimR[24028:1673831] server started on http://localhost:57171
2017-12-05 20:54:30.284 VimR[24028:1673831] *** WARNING: Textured window <NSWindow: 0x7f883de7afc0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2017-12-05 20:54:32.931 VimR[24028:1673901] adding file:///Users/aosh/ to monitoring
2017-12-05 20:54:33.280 VimR[24028:1673831] *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.)'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff574702fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7dde1c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff57501d6d +[NSException raise:format:] + 205
	3   AppKit                              0x00007fff552cb319 _NSRunModal + 484
	4   AppKit                              0x00007fff54cab7ad -[NSAlert runModal] + 240
	5   SwiftNeoVim                         0x0000000102bf3450 _TTSf4s_n___TFC11SwiftNeoVim10NeoVimViewP33_ED7F0BC1D60B2DEA7686777EA9206B7812launchNeoVimfVS_4SizeT_ + 592
	6   SwiftNeoVim                         0x0000000102bf3568 _TTSf4s_n___TFC11SwiftNeoVim10NeoVimView12setFrameSizefVSC6CGSizeT_ + 248
	7   SwiftNeoVim                         0x0000000102bf2c9d _TToFC11SwiftNeoVim10NeoVimView12setFrameSizefVSC6CGSizeT_ + 45
	8   AppKit                              0x00007fff54a3fa52 -[NSView setFrame:] + 371
	9   AppKit                              0x00007fff552b0cf2 NSViewActuallyUpdateFrameFromLayoutEngine + 392
	10  AppKit                              0x00007fff54a4d122 NSViewLevelLayout + 385
	11  AppKit                              0x00007fff552b09e4 _NSViewLayout + 587
	12  AppKit                              0x00007fff54aac19b -[NSView _layoutSubtreeWithOldSize:] + 437
	13  AppKit                              0x00007fff54aac414 -[NSView _layoutSubtreeWithOldSize:] + 1070
	14  AppKit                              0x00007fff54aac414 -[NSView _layoutSubtreeWithOldSize:] + 1070
	15  AppKit                              0x00007fff552b7740 -[NSView _layoutSubtreeIfNeededAndAllowTemporaryEngine:] + 1380
	16  AppKit                              0x00007fff54ac9987 -[NSWindow(NSConstraintBasedLayout) _layoutViewTree] + 163
	17  AppKit                              0x00007fff54ab0b1e -[NSWindow _setFrame:updateBorderViewSize:] + 1124
	18  AppKit                              0x00007fff54ac8eff -[NSWindow _oldPlaceWindow:] + 604
	19  AppKit                              0x00007fff54ac84ae -[NSWindow _setFrameCommon:display:stashSize:] + 3108
	20  AppKit                              0x00007fff54ac787d -[NSWindow _setFrame:display:allowImplicitAnimation:stashSize:] + 222
	21  AppKit                              0x00007fff54ac7798 -[NSWindow setFrame:display:] + 67
	22  VimR                                0x0000000102974404 _TFC4VimR10MainWindowcfT6sourceGC7RxSwift10ObservableVS0_5State_7emitterCS_13ActionEmitter5stateS3__S0_ + 18836
	23  VimR                                0x00000001028ab6b2 _TTSf4g_n___TFC4VimR6UiRootP33_8ECA61C70B364ED2D49DC97051709EC713newMainWindowfT4withVCS_10MainWindow5State_S1_ + 3506
	24  VimR                                0x00000001028ae2ae _TTSf4g_n___TFFC4VimR6UiRootcFT6sourceGC7RxSwift10ObservableVS_8AppState_7emitterCS_13ActionEmitter5stateS3__S0_U_FS3_T_ + 7086
	25  VimR                                0x000000010289fa85 _TFFC4VimR6UiRootcFT6sourceGC7RxSwift10ObservableVS_8AppState_7emitterCS_13ActionEmitter5stateS3__S0_U_FS3_T_ + 965
	26  VimR                                0x000000010295e946 _TTRXFo_oV4VimR8AppState__XFo_iS0___ + 582
	27  RxSwift                             0x0000000102e0fdd0 _TFFE7RxSwiftPS_14ObservableType9subscribeFT6onNextGSqFwx1ET__7onErrorGSqFPs5Error_T__11onCompletedGSqFT_T__10onDisposedGSqFT_T___PS_10Disposable_U_FGOS_5EventwxS1__T_ + 352
	28  RxSwift                             0x0000000102e0ff6c _TPA__TFFE7RxSwiftPS_14ObservableType9subscribeFT6onNextGSqFwx1ET__7onErrorGSqFPs5Error_T__11onCompletedGSqFT_T__10onDisposedGSqFT_T___PS_10Disposable_U_FGOS_5EventwxS1__T_ + 172
	29  RxSwift                             0x0000000102e15ca3 _TFC7RxSwift12ObserverBase2onfGOS_5Eventx_T_ + 403
	30  RxSwift                             0x0000000102dd9808 _TTWurGC7RxSwift12ObserverBasex_S_12ObserverTypeS_FS1_2onfGOS_5Eventwx1E_T_ + 40
	31  RxSwift                             0x0000000102e9dbc2 _TFFC7RxSwiftP33_277A93ABA8477198C125F3F26B2D4B6232ObserveOnSerialDispatchQueueSinkcFT9schedulerCS_28SerialDispatchQueueScheduler8observerx6cancelPS_10Cancelable__GS0_x_U_FTGS0_x_GOS_5Eventwx1E__PS_10Disposable_ + 242
	32  RxSwift                             0x0000000102e9e57e _TPA__TFFC7RxSwiftP33_277A93ABA8477198C125F3F26B2D4B6232ObserveOnSerialDispatchQueueSinkcFT9schedulerCS_28SerialDispatchQueueScheduler8observerx6cancelPS_10Cancelable__GS0_x_U_FTGS0_x_GOS_5Eventwx1E__PS_10Disposable_ + 14
	33  RxSwift                             0x0000000102e9e651 _TPA__TTRGRx7RxSwift12ObserverTyperXFo_oGCS_P33_277A93ABA8477198C125F3F26B2D4B6232ObserveOnSerialDispatchQueueSinkx_iGOS_5Eventwx1E__iPS_10Disposable__XFo_iTGS1_x_GS2_wxS3____iPS4___ + 145
	34  RxSwift                             0x0000000102e0b0b8 _TFFC7RxSwift13MainScheduler16scheduleInternalurFTx6actionFxPS_10Disposable__PS1__U_FT_T_ + 136
	35  libdispatch.dylib                   0x00007fff7e99e6cd _dispatch_call_block_and_release + 12
	36  libdispatch.dylib                   0x00007fff7e996e88 _dispatch_client_callout + 8
	37  libdispatch.dylib                   0x00007fff7e9a2471 _dispatch_main_queue_callback_4CF + 1148
	38  CoreFoundation                      0x00007fff574289c9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	39  CoreFoundation                      0x00007fff573eac4a __CFRunLoopRun + 2586
	40  CoreFoundation                      0x00007fff573e9fa3 CFRunLoopRunSpecific + 483
	41  HIToolbox                           0x00007fff56709866 RunCurrentEventLoopInMode + 286
	42  HIToolbox                           0x00007fff567094df ReceiveNextEventCommon + 366
	43  HIToolbox                           0x00007fff56709354 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	44  AppKit                              0x00007fff54a06a23 _DPSNextEvent + 2085
	45  AppKit                              0x00007fff5519be6c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	46  AppKit                              0x00007fff549fb831 -[NSApplication run] + 764
	47  AppKit                              0x00007fff549ca9d2 NSApplicationMain + 804
	48  VimR                                0x00000001027c3739 main + 9
	49  libdyld.dylib                       0x00007fff7e9d0145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    24028 abort      /Applications/VimR.app/Contents/MacOS/VimR`

**Comment by qvacua** [comment]
Which version of macOS are you using?

**Comment by antonshiryaev** [comment]
10.13.1

Антон Ширяев
anton.o.shiryaev@gmail.com

**Comment by turnspike** [comment]
Same issue here. VimR was working great yesterday from a new install. Today after a restart it crashes on run. Snapshot has the same issue.

Awesome app by the way, if I can get it running it'll prolly replace Atom. 😃

VimR version: 0.19.1
MacOS version: 10.13.1
Crash log: [crash.txt](https://github.com/qvacua/vimr/files/1537191/crash.txt)

```
> /Applications/VimR.app/Contents/MacOS/VimR

2017-12-07 09:27:46.596 VimR[3818:160006] server started on http://localhost:51708
2017-12-07 09:27:46.662 VimR[3818:160006] *** WARNING: Textured window <NSWindow: 0x7fc4a5e12750> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
2017-12-07 09:27:46.809 VimR[3818:160031] adding file:///Users/work/ to monitoring
2017-12-07 09:27:48.202 VimR[3818:160006] *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.)'

```

**Comment by cweagans** [comment]
Same issue. I can provide a backtrace if needed:

```
Process:               VimR [5467]
Path:                  /Applications/VimR.app/Contents/MacOS/VimR
Identifier:            com.qvacua.VimR
Version:               0.20.0 (238)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VimR [5467]
User ID:               501

Date/Time:             2017-12-07 09:51:18.176 -0700
OS Version:            Mac OS X 10.13.1 (17B1003)
Report Version:        12
Bridge OS Version:     3.0 (14Y661)
Anonymous UUID:        B46E8A1B-77A7-BB5A-4852-4FF41E2C296B

Sleep/Wake UUID:       C8894BA4-A3BA-41F2-8BCA-DB503BAF33FB

Time Awake Since Boot: 17000 seconds
Time Since Wake:       4500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.)'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by cweagans** [comment]
Downgrading to 0.20.0 (238) fixed the problem. I think there's something wrong in the new SNAPSHOT release.

**Comment by qvacua** [comment]
I'll try to fix the issue soon...

**Comment by qvacua** [comment]
Please try the latest snapshot: https://github.com/qvacua/vimr/releases

**Comment by antonshiryaev** [comment]
Nope, still crashes.

**Comment by qvacua** [comment]
Does the latest release has the same problem? https://github.com/qvacua/vimr/releases/tag/v0.20.1-245

**Comment by qvacua** [comment]
Could you provide the log for https://github.com/qvacua/vimr/releases/tag/v0.20.3-255

**Comment by antonshiryaev** [comment]
It no longer crashes. Sorry I didn't report back earlier.

**Comment by nclark** [comment]
I experienced this issue for the first time today. To resolve, I ran `vimr --nvim -u NONE` to open VimR, and updated from `VimR | Check for Updates...`. This upgraded me from v0.19.? to `SNAPSHOT-265`. Thanks @qvacua 👍
