### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#580]
Upgrading to SNAPSHOT-243 (243) from the previous snapshot might have introduced a memory leak. After some time editing RST documents VimR became more and more sluggish.

<img width="655" alt="screen shot 2017-12-07 at 13 31 03" src="https://user-images.githubusercontent.com/453929/33717767-0fcd7dd8-db53-11e7-84af-48a5974b2314.png">

**Comment by qvacua** [comment]
Oh, that's bad. I'm currently updating to High Sierra and having other issues. I'll try to fix them soon.

**Comment by qvacua** [comment]
Please try the latest release: https://github.com/qvacua/vimr/releases/latest
