### ISSUE TITLE
feature request :open file and jump to specific line number at start

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#584]
like vi program in terminal, it can accept a line number argument when startup.

**Comment by qvacua** [comment]
You can already do this by `vimr --nvim +10 SOME_FILE` for line 10 of SOME_FILE.

**Comment by ptzz** [comment]
> You can already do this by vimr --nvim +10 SOME_FILE for line 10 of SOME_FILE.

It seems passing `--nvim` always opens a new window though.

**Comment by FinallyFinancialFreedom** [comment]
yes it does not work anymore in SNAPSHOT-280 (280)
