### ISSUE TITLE
Denite causes VimR to freeze as of snapshot-249

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [qvacua/vimr#586]
I can't reproduce in tui-nvim, but this is reproducible on both of my machines:

1. Install Denite.nvim
2. `:Denite buffer`
3. Wait indefinitely

Downgrading to the stable release (`v0.20.1-245`) solves this for me.

**Comment by qvacua** [comment]
Please try the latest snapshot :)

**Comment by ELLIOTTCABLE** [comment]
Fixes it! `<3`
