### ISSUE TITLE
Question: Support for floating buffers

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#595]
Tools such as "fzf" and "CtrlP" use buffer to look for files. I wonder if it is possible for vimr to float that buffer above in a separate GUI?

**Comment by tssm** [comment]
[It is possible](https://github.com/neovim/neovim/blob/master/runtime/doc/ui.txt) although not every element has been externalized yet

**Comment by derekstavis** [comment]
Floating windows are now on neovim master. Since [coc](https://github.com/neoclide/coc.nvim) uses it for nice completions, I'm back to terminal again, but would love to be able to use vimr and all its niceties :)

**Comment by skbolton** [comment]
Just discovered vimr and I really like it. But I am surprised how much I miss the floating window look that is available in the terminal. Would love to see this in vimr

**Comment by wookayin** [comment]
@skbolton You can use neovim-0.4.0 version (pre-release) https://github.com/qvacua/vimr/releases/tag/neovim-nightly.

**Comment by skbolton** [comment]
Fantastic thanks for the suggestuion @wookayin

**Comment by huytd** [comment]
Now that neovim 0.4.0 is released, is there any plan for VimR to upgrade instead of using nightly?

**Comment by qvacua** [comment]
The newest release https://github.com/qvacua/vimr/releases/tag/v0.28.0-328 uses Neovim 0.4.2. Closing; please re-open when there are issues.
