### ISSUE TITLE
Can not Paste into VimR.

### ISSUE THREAD

**Issue by J-Liu** [qvacua/vimr#596]
macOS 10.13.2 (17C88)
VimR Version 0.20.3 (255)
CMD+C copy some text from any other apps, CMD+P in VimR will paste nothing.

**Comment by sfcgeorge** [comment]
Works fine for me in both normal and insert mode, odd. Try commenting out everything in your .nvimrc to see if a particular plugin or setting is breaking it.n 

macOS 10.13.2 (17C88)
VimR Version 0.20.3 (255)

**Comment by qvacua** [comment]
To launch VimR without loading your `init.vim` you can also use `vimr --nvim -u NONE`.

**Comment by jonahfang** [comment]
I leave VimR and still use MacVim because the copy and paste function is not stable yet.

**Comment by bradparks** [comment]
yeah copy paste isnt working for me either....  if I try and copy, it deletes the text, and if I keep hitting `CMD+C`, it dumps `<D-c>` literally into the buffer whenever i do?

**Comment by nornagon** [comment]
This is broken for me currently in vimR 0.26.10 and macOS 10.14.4. It used to work though :S

I've tried launching with `vimr --nvim -u NONE` and I get the same issue.


Ohhhhh, Cmd+V is apparently now bound to "Focus Neovim View" and paste is Cmd+K. That's very confusing and I think should be changed :\

**Comment by nornagon** [comment]
... wait, I think VimR is trying to reverse-engineer my keyboard layout. <kbd>K</kbd> is what you get when you press the keyboard key that has <kbd>V</kbd> written on it in Dvorak.

This is confusing and undesirable behaviour.
