### ISSUE TITLE
Fugitive Crashes vimr on empty commit

### ISSUE THREAD

**Issue by lsgos** [qvacua/vimr#597]
The steps to reproduce are;
Run :Gstatus with fugitive
stage changes
start the commit using cc
try to save with an empty message, which causes fugitive to abort the commit.

This also causes vimR to crash, with the message 'sending msg to neovim failed for 1 with -3.

It's not too crucial because I can avoid making empty commits, but it's still a bit annoying since it's possible to do this accidentally and have it crash anyway, potentially losing work or killing processes I launched from nvim. 

I tested this in the terminal version of neovim and it doesn't crash, so i think the issue is with how vimr handles this.

Here's my init.vim (sorry its a bit of a mess)
let mapleader=","
let maplocalleader=","
"relative line numbers
set rnu 
set splitright
syntax on
filetype plugin indent on

"use spaces instead of tabs by default, unless overridden somewhere.
set tabstop=2
set shiftwidth=2
set expandtab
nohlsearch
"automatic line breaks for text type files
autocmd FileType text setlocal textwidth=78 

"use ripgrep for the :grep tool.
set grepprg=rg\ --vimgrep
set grepformat^=%f:%l:%c:%m

"plugins
call plug#begin('~/.local/share/nvim/plugged')
Plug 'https://github.com/michaeljsmith/vim-indent-object'
Plug 'https://github.com/dag/vim-fish'
Plug 'JuliaEditorSupport/julia-vim'
Plug 'https://github.com/morhetz/gruvbox'
Plug 'https://github.com/nanotech/jellybeans.vim'
Plug 'https://github.com/jnurmine/Zenburn'
Plug 'https://github.com/vim-scripts/scratch.vim'
Plug 'https://github.com/scrooloose/nerdtree'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-jedi'
Plug 'https://github.com/Shougo/echodoc.vim'
Plug 'https://github.com/tpope/vim-fugitive'
Plug 'cjrh/vim-conda'
"Plug 'airblade/vim-gitgutter' This plugin is nifty but do i really use it?
Plug 'https://github.com/vim-airline/vim-airline'
Plug 'hkupty/iron.nvim', {'do': ':UpdateRemotePlugins' }
Plug 'https://github.com/kana/vim-textobj-user'
Plug 'https://github.com/bps/vim-textobj-python'
Plug 'wincent/command-t'
call plug#end()
"python configuration
let g:python3_host_prog='/anaconda3/envs/nvim/bin/python'
let g:python_host_prog='/anaconda3/envs/py2nvim/bin/python'

"a e s t h e t i c s
set termguicolors
colorscheme zenburn
set background=dark
set updatetime=250 "faster redraws

"look for tags in .tags by default
set tags=./.tags 

"key bindings
let g:gitgutter_map_keys=0
"for now, turn of the gitgutter keys because they clash with the python text
"objs which are probably more useful to me
noremap <D-s> :w
noremap <D-/> :NERDTreeToggle<CR>
tnoremap <Esc> <C-\><C-n> "Set ESC to exit terminal mode when a terminal is open
nmap <localleader>ss <Plug>(iron-send-motion)
vmap <localleader>ss <Plug>(iron-send-motion) 
noremap <localleader>rl <ESC>:IronRepl<CR>
"add terminal style movement shortcuts
noremap <C-A>  <Home>
noremap <C-E>  <End>
"recognise .jl as julia, not some weird lisp

**Comment by lsgos** [comment]
edit; this sometimes seems to happen even if the commit was successful

**Comment by qvacua** [comment]
Do you still have this problem? I cannot reproduce it with the newest version.

**Comment by lsgos** [comment]
I just re-downloaded the latest release, but I can still get vimr to crash on an empty commit message, and occasionally with a normal one. I can still reproduce it in a new, empty repository, and all my other plugins disabled. This is the message I get now

Reason: sending msg to neovim failed for 7 with -3

I’m using zsh, but other than that I don’t think there’s anything non-standard about my setup? 

I don’t know anything about swift, but if there’s anything else you want me to try let me know.

**Comment by minusf** [comment]
i get a similar crash even with a non empty commit message:
<img width="420" alt="screen shot 2018-01-16 at 12 07 13" src="https://user-images.githubusercontent.com/3632883/34985914-f5c524e0-fab5-11e7-881f-a1a0e4fa8d0b.png">

**Comment by minusf** [comment]
just tried under vanilla nvim, commits are fine.

**Comment by minusf** [comment]
do you need any extra info?  this is the showstopper bug for me that won't let me use VimR as my main editor.  i cannot commit anything :/

**Comment by qvacua** [comment]
Unfortunately I still cannot reproduce this. Does this also happen with the latest snapshot? Does this also happen with the following `init.vim`?

```
syntax on
filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-fugitive'
call plug#end()
```

**Comment by minusf** [comment]
yep. same same.

**Comment by qvacua** [comment]
Could you please try <http://taewon.de/VimR-fugitive.zip>?

**Comment by minusf** [comment]
no crash after commit with that snapshot for now 👍

**Comment by qvacua** [comment]
New release with the fix: https://github.com/qvacua/vimr/releases/tag/v0.20.5-259
