### ISSUE TITLE
Additional file browser keyboard actions

### ISSUE THREAD

**Issue by dnerdy** [qvacua/vimr#60]
I've added additional file browser actions in this branch: https://github.com/dnerdy/vimr/tree/file-browser-additional-keyboard-actions

Is there any interest in this? Additional ideas below.

The actions are inspired by NerdTree:

o: open file in new tab
O: open file in current tab
i: open file in horizontal split
s: open file in vertical split

Any of the above can also be used to expand and collapse directories.

The code needs to be refactored. I've modified VRMovementsAndActionsProtocol to include the new actions, but I think it would make sense to extend the protocol since the actions are specific to the file browser.

I'd also like to add additional actions, like search (/,?,n,N) and file creation/deletion/etc (m, then (a)dd, (m)ove, (d)elete.

The plan is to have feedback display in the status bar.

**Comment by sfcgeorge** [comment]
It looks like this has regressed and no longer works :(

**Comment by qvacua** [comment]
@sfcgeorge it's not yet been implemented in the "reboot" of VimR using neovim.
