### ISSUE TITLE
scrolling is very CPU heavy

### ISSUE THREAD

**Issue by kcmannem** [qvacua/vimr#605]
Scrolling spikes to >50% (2016 Touch Bar 13 inch) most of the time when scrolling. The scrolling is also very choppy. The file is about 1000 lines. The same file on MacVim, is very easy to scroll through and peaks at about ~18% CPU usage. Maybe just adapt their rendering technique, idk how hard this would be. This might limit Vimr's usability since very big files will be a pain to scroll through.

**Comment by minusf** [comment]
this will be very hard to track down exactly.  for example i dont see with a 5000 lines sql dump file with syntax highlighting on a 2015 macbook pro, cpu spikes 30%ish. i also see similar spikes in macvim if a scroll around enough.

this is also absolutely plugin specific and the quality of the syntax highlight plugins varies wildly as well.

have you tried with no plugins and syntax/filetype off?

**Comment by qvacua** [comment]
As described in https://github.com/qvacua/vimr/issues/519#issuecomment-359282426, for some syntax highlighting the old regex engine has much better performance. You can use it by `set re=1` in your `init.vim`. To see whether it gives you performance gain, you can use `syntime on`, scroll around, then `syntime report`.

**Comment by qvacua** [comment]
BTW: the newest snapshot has slightly improved scroll performance 😬...

**Comment by minusf** [comment]
to be clear, i am not stating that this is a syntax highlighting issue. but in my limited experience scrolling is often heavily affected by it.

**Comment by kcmannem** [comment]
@qvacua I'm not having any change in performance with old re. I'll see how the next release goes. Thanks for the quick update.

**Comment by qvacua** [comment]
Closing. I'll re-open or create a new issue when I have a new idea for optimization. :)
