### ISSUE TITLE
Ability to move focus between file browser and buffer text

### ISSUE THREAD

**Issue by dnerdy** [qvacua/vimr#61]
I like the idea of using ⌘1 to show/focus the file browser (ensuring that there is a selection) and ⌘2 to focus the buffer text area. This is useful so that you can move from editing text to interacting with the file browser via the keyboard and back to editing text seamlessly.

I've created an experimental branch here: https://github.com/dnerdy/vimr/tree/move-focus

If you don't like this specific implementation, please let me know what you think a good implementation would be as I think the general idea is a good one.

The current implementation changes:

```
View
------------------------------
Sidebar > Show File Browser ⌘1
```

to

```
View
------------------------------
Focus File Browser ⌘1
Focus Buffer Text ⌘2
------------------------------
Sidebar > (remaining menu items)
```

**Comment by Anzumana** [comment]
we should add that to the readme that esc focuses the editor. i looked at the symbol for it inside of vimr and was not sure what key i had to press :)

**Comment by qvacua** [comment]
Thanks, indeed. I've added an link to the Wiki in the README.
