### ISSUE TITLE
Font anti-aliasing in snapshot 260 does not seem to be working

### ISSUE THREAD

**Issue by jaischeema** [qvacua/vimr#612]
This might already be a known issue or work in progress feature, wanted to raise this just in case. The rendering in 259 is much smoother when compared to 260 with the same font. If you need any more information, please let me know and I will update the issue.

**Comment by thanosbellos** [comment]
Hi, i have also noticed the same problem:
![screen shot 2018-03-14 at 21 01 04](https://user-images.githubusercontent.com/425283/37425310-8fd52570-27cb-11e8-8737-1d490d7dfdc2.png)

On the left side we have vimr snapshot 259 and on the right latest snapshot 267

**Comment by Quiark** [comment]
Same here, it's especially bad on 2K external monitor.

**Comment by pjg** [comment]
Yes. Terrible rendering of fonts still in 267:

![image](https://user-images.githubusercontent.com/10712/37622809-07bbb888-2bc3-11e8-8faa-86b3bfc42c10.png)

**Comment by vwxyutarooo** [comment]
Same issue. In my case, only current line with `set cursorline` is antialiased.

**Comment by nhat** [comment]
Any updates on this issue? I'm also having it since a few releases.

**Comment by tbastos** [comment]
This font issue is enough to make new VimR versions unusable for me.

With v0.20.6-261 (for accuracy, please open the image in a new tab): 
![v0 20 6-261](https://user-images.githubusercontent.com/150480/38035187-1f3580ba-32a4-11e8-82a0-9c6dccbf6596.jpeg)

With v0.21.1-269 (for accuracy, please open the image in a new tab): 
![v0 21 1-269](https://user-images.githubusercontent.com/150480/38035205-29e142e2-32a4-11e8-9b6b-23f5a29eb9bf.jpeg)

In non-retina displays, legibility is terrible for me. In retina displays it's still usable.

**Comment by qvacua** [comment]
Could you please try <http://taewon.de/VimR-rendering-GH-612.tar.bz2>? I reverted a background coloring optimization which seems to cause this. If this build is OK, then I'll release a bugfix version.
