### ISSUE TITLE
underline rendering going crazy

### ISSUE THREAD

**Issue by minusf** [qvacua/vimr#620]
since update to `Version 0.21.0 (267)` underline rendering is all over the place.

fugitive documentation:
<img width="1073" alt="screen shot 2018-03-13 at 12 22 00" src="https://user-images.githubusercontent.com/3632883/37338937-36f89422-26b9-11e8-9c1d-9b0c26523383.png">

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F268

**Comment by minusf** [comment]
looks ok now, thanks
