### ISSUE TITLE
Background mis-colored when mouse cursor/pointer moves

### ISSUE THREAD

**Issue by braindev** [qvacua/vimr#621]
When I move my mouse pointer (or windows) over the window the background gets repainted in a slightly different color.  You can see it here:

https://monosnap.com/file/3zQvLubAllMJZXHWYg1yfdMTXEIbSg

Obviously this isn't super important b/c most vim users don't use a mouse very much.

Thanks for the helpful development tool!

**Comment by qvacua** [comment]
Does this still happen with the newest snapshot?

**Comment by braindev** [comment]
I believe it's fixed!  Thanks
