### ISSUE TITLE
pwd command always returns $HOME

### ISSUE THREAD

**Issue by idanko** [qvacua/vimr#622]
Hello, I'm a newcomer to the VimR world :), and first I want to say thank you for such good work! After using vimr for a while, I'm concerned about the question how to configure it to respect current path ($PWD). To run vimr from terminal I made the `alias vimr="open -a VimR"` in my .bash_alias (which is consumed by .zshrc). Thanks in advance.
```
VimR: v0.21.0-267
Mac: 10.13.3
$SHELL:/bin/zsh
```

**Comment by qvacua** [comment]
You should use the included command line tool `vimr` <https://github.com/qvacua/vimr/wiki#command-line-tool>.

**Comment by scssquatch** [comment]
@qvacua using the included command line tool, even specifying the directory explicitly I still open vimr and type `:echo $PWD` and get my $HOME directory. Any ideas? I'm on 0.27.4 (326)
