### ISSUE TITLE
rendering error when switching from insert mode to normal mode in :terminal

### ISSUE THREAD

**Issue by icearith** [qvacua/vimr#636]
![image](https://user-images.githubusercontent.com/2555093/38463629-73d89162-3b31-11e8-9905-ae3095f3fc86.png)

As you can see, there are two cursors, after switching to insert mode from normal mode in neovim terminal. this doesn't happen in terminal neovim.

**Comment by icearith** [comment]
@qvacua any ideas about this issue?

**Comment by qvacua** [comment]
The cursor rendering needs some improvement, yes... 😬

**Comment by icearith** [comment]
@qvacua any plans or schedules to fix this bug 😃

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F278
