### ISSUE TITLE
[Feature Request] Associate file types with VimR

### ISSUE THREAD

**Issue by HandsomePixel** [qvacua/vimr#640]
Title says it all.
I know that vim/neovim/VimR is closer to an IDE than a text editor but I _really_ would like to have the option of just double clicking a file and auto opens in VimR

**Comment by ptzz** [comment]
You mean double click in e.g. Finder? Right click the file, select "Show View Options", select VimR under "Open With" and click "Change All". Voila!

**Comment by blahgeek** [comment]
> vim/neovim/VimR is closer to an IDE than a text editor"

I would say the exact opposite :P

**Comment by HandsomePixel** [comment]
Wow, I completely mixed the definition of IDE and Text Editor when I was typing my previous comment.
So sorry for the confusion.
And thank you for the help!
It turns out that I have so many text editors installed that I had to click "Other" in the "Open With" section and manually find and click on VimR, in case that helps anyone.
