### ISSUE TITLE
Reuse current window when opening file from Finder

### ISSUE THREAD

**Issue by ptzz** [qvacua/vimr#642]
In the MacVim preferences, "Open files from applications" can be set to "in the current window" to achieve this. Is it possible to configure VimR in the same way?

**Comment by ptzz** [comment]
Indeed, I unfortunately staying with MacVim due to this. I use it instead of terminal vim mainly when greping stuff in iTerm and then opening relevant files with CMD-click in a single MacVim instance. This could be lots of files and not being able to switch between them using buffer commands etc. is a showstopper for me.

**Comment by leehigh** [comment]
same problem

**Comment by unnamed777** [comment]
Is there any workaround? May be a command line argument to point out which window of VimR should be used to open file (or execute any command like ":edit")?

**Comment by SolaWing** [comment]
terminal vimr is open file in current window. it can be wrapped into a Automation App, for using by Finder.

but still want a config to specify the open window.

**Comment by unnamed777** [comment]
> but still want a config to specify the open window.
I meant GUI window. Each file is opened new new window by default.

**Comment by ThSGM** [comment]
I'm not sure development is still going on on this project, but this remains an issue now three years later.

**Comment by qvacua** [comment]
Please try <https://github.com/qvacua/vimr/releases/tag/v0.38.0-20220317.192248>.
