### ISSUE TITLE
With --nvim argument, new window is always opened

### ISSUE THREAD

**Issue by ptzz** [qvacua/vimr#643]
From `vimr --help`:
> By default all files are open in tabs in the front most window or in a new window

But it seems to not be true when `--nvim` is passed to `vimr`.

Version: 0.22.0

**Comment by qvacua** [comment]
This is intended. Since `--nvim` results VimR passing all the following arguments to the background

**Comment by ptzz** [comment]
Ok, so it’s currently not possible to open a file in the frontmost window at a particular line number?

**Comment by qvacua** [comment]
You can do that with the latest snapshot (GH-443).
