### ISSUE TITLE
Pass environment variables from command line

### ISSUE THREAD

**Issue by blahgeek** [qvacua/vimr#644]
## Summary

Running `vimr` from command line should pass environment variables of current shell to running neovim instance, like running `nvim` directly in terminal.

## Explanation

Currently the VimR application would loads environment variables by starting a new $SHELL under the hood, this usually works fine. But sometimes I'm working on a python's virtual environment, and the python-language-server (used by LanguageClient-Neovim) would only provides correct completions if it detects current virtual environment from $VIRTUAL_ENV.

Note that after this is implemented, it's recommended to set `g:python_host_prog` and `g:python3_host_prog` in neovim config since the neovim python plugin may not exists in virtualenv-ed python. This is also true for neovim in terminal, so no big deal.

**Comment by qvacua** [comment]
This issue is the same as #625 . Closing, please follow the progress there.
