### ISSUE TITLE
VimR should register itself for some file types

### ISSUE THREAD

**Issue by Kwpolska** [qvacua/vimr#648]
It would be handy if VimR was available in the *Open With* menu in Finder for many text file types (like MacVim, VS Code, or BBEdit are, for example), or perhaps for almost everything (like Hex Fiend does). A nice icon would be a plus.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F279 

We‘ve copied MacVim‘s icons, btw.

**Comment by Kwpolska** [comment]
I managed to create a duplicate of my own issue (#402). GitHub’s search seems to work strangely. Sorry for that.

It works neatly, although the MacVim icons can be confusing if someone has both on their system.
