### ISSUE TITLE
Toggling the ‘tools‘ sidebar when invoking from the command-line

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [qvacua/vimr#649]
I use VimR as my `$VISUAL`, with something like this:

    VISUAL="vimr -n --wait"

That gets me pretty close to what I want; save one problem: I generally keep the "tools" sidebars (specifically, the filetree) open on my Vimr instance(s); but on the single, throwaway instances I open from the command-line, I really don't want the screen space wasted on the filebrowser, etc.

On that note, I'd love a way to preform the equivalent of **⌘\\**, but automatically.

Of course, *ideally*, this should be something accessible from within Vim itself (`:ToggleTools` or something?); but given the long-standing Configuration Question and vimscript issues (see [my comment on #506](https://github.com/qvacua/vimr/issues/506#issuecomment-347697451)), that might be better deferred. For the moment, I'd be perfectly happy with an interim solution like a hardcoded `--tools` `--no-tools` argument!

Thoughts?

**Comment by qvacua** [comment]
The latest snapshot supports this. Put for example the following
```
function! s:TempMaxSession() abort
  VimRMakeSessionTemporary
  VimRHideTools
  VimRMaximizeWindow
endfunction
command! -nargs=0 TempMaxSession call s:TempMaxSession()
```

into `~/.config/nvim/ginit.vim` and invoke `vimr` using

```
$ vimr --nvim '+au GUIEnter * TempMaxSession' SOME_FILE
```

Then, you will get a maximized VimR window with hidden tools and this setting is not persisted.

As for the configuration via `ginit.vim`, I'll try to implement some simple settings, e.g. the font.

**Comment by ELLIOTTCABLE** [comment]
This is great work! Thanks! ❤️
