### ISSUE TITLE
Auto update doesn't work with brew cask?

### ISSUE THREAD

**Issue by deinspanjer** [qvacua/vimr#652]
I tried installing the latest stable via `brew cask install vimr` and then ran it, enabled snapshot updates, and tried to `Check for updates...` but I received the error:
![image](https://user-images.githubusercontent.com/286641/41195241-6396c5ca-6bf7-11e8-9640-9ba8412b035b.png)

Is there any chance the auto-update could allow this particular scenario?

**Comment by qvacua** [comment]
Hm, that's still very odd. I would think that the auto update should work even when started with `vimr`. Still, closing this issue since there's a workaround 😬

**Comment by deinspanjer** [comment]
I was guessing that maybe the vimr command was doing something special that resulted in the application looking like it was opened from a read-only or temporary location.  It is good that we have a workaround, but it would be nice if someone familiar with the vimr command might look into why it conflicts with the auto-update and try to fix it.
