### ISSUE TITLE
Report exact version of neovim 

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#655]
When encountering bugs and for reporting issues upstream, it would be very helpful if VimR reported the actual, exact version of the neovim component used in the build. 

For example, the current snapshot 281 reports `NVIM v0.3.0` on startup and with `:version` even though -- if I understand correctly -- you sync the master branch of neovim/neovim for each build, so the actual version would be something like, e.g., `NVIM v0.3.1-125-g70626e6a1` (current HEAD as reported by terminal `neovim`).

**Comment by qvacua** [comment]
No, I only use the released version of Neovim for all of VimR's releases. I keep a separate branch `update-neovim` which tracks the `master` of Neovim.

**Comment by clason** [comment]
Ah, then I misunderstood an earlier comment. Sorry for the noise!
