### ISSUE TITLE
colorscheme is not set on start up

### ISSUE THREAD

**Issue by stnguyen** [qvacua/vimr#657]
In my vimrc I have:

```
set background=dark
colorscheme PaperColor
```

which works fine on vim inside terminal. But when I open vimr, the colorscheme is not set correctly. I need to run the command again inside vimr to apply the color scheme.

Would you pls help?
Thank you

**Comment by hakamadare** [comment]
@stnguyen do you get the desired behavior when you run `nvim` from the terminal?

Check the NeoVim [documentation](https://neovim.io/doc/user/nvim.html) for instructions on porting your Vim config to NeoVim.

**Comment by andradei** [comment]
@NikosEfthias Is right, it is working fine after I did

```
if has("gui_vimr")
  set background=dark
  colorscheme PaperColor
else
  ...Some other colorscheme...
endif
```

Version 0.24.0 (282)

Should this be closed?

**Comment by qvacua** [comment]
Yes :)
