### ISSUE TITLE
Ligatures always on

### ISSUE THREAD

**Issue by minusf** [qvacua/vimr#659]
Changing the preference "Use Ligatures" seems to have no effect:

<img width="410" alt="screen shot 2018-07-17 at 16 41 49" src="https://user-images.githubusercontent.com/3632883/42824570-61d61216-89e0-11e8-9ebe-9a8cfcce9986.png">
<img width="405" alt="screen shot 2018-07-17 at 16 41 59" src="https://user-images.githubusercontent.com/3632883/42824572-61f7d482-89e0-11e8-9919-9a35aefe6e31.png">

This used to work a couple of snapshots back :}

**Comment by qvacua** [comment]
Indeed. We updated the code from MacVim few snapshots ago and the rendering code changed a bit. I'll have a look. (I did not notice since I'm currently using a font without ligatures)

**Comment by qvacua** [comment]
The MacVim code we're using has a small bug: macvim-dev/macvim#711. I've created a PR and fixed it in VimR. The next snapshot will have the fix. I'll comment here when the snapshot is built.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F287

**Comment by minusf** [comment]
the font in the preview window does not change with the toggle, but in the editing window it works. thanks.
