### ISSUE TITLE
is there a way to disable all keyboard shortcuts provided by the app?

### ISSUE THREAD

**Issue by slmjkdbtl** [qvacua/vimr#660]
I mapped a lot of vim predefined key bindings to something else, causing some keyboard shortcuts doesn't work as expected, and I prefer to define all my keyboard actions in my vimrc. Is there a way to turn off all keyboard shortcuts provided by the app?

And also is there a way to turn off trackpad scrolling?

**Comment by qvacua** [comment]
You can change all key shortcuts of menu items in the latest snapshot: https://github.com/qvacua/vimr/releases

That means you can delete for example the `Command-1` for "Toggle File Browser" menu item and use `Command-1` for something else.

**Comment by qvacua** [comment]
@slmjkdbtl BTW: why would you want to turn off the trackpad scrolling?

**Comment by slmjkdbtl** [comment]
@qvacua I'm trying to override vim's scroll behavior (in my case, just want to override it to move cursor up and down instead of move whole page), I don't mean turn off trackpad scrolling, but to customize (didn't know why I said turn off before, sorry), in iTerm mapping `<ScrollWheelDown>` doesn't work, so I'm wondering if vimr could provide customization on scrolling behavior in some way.
