### ISSUE TITLE
Snapshot 287: corrupt display if ligatures are off with patched font

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#661]
With a patched font from https://github.com/ryanoasis/nerd-fonts (needed to get symbols in https://github.com/vim-airline/vim-airline) and ligatures are turned off, I get the following corrupt display (here with Meslo LG S Regular Nerd Font Complete.otf):

<img width="747" alt="screen shot 2018-07-18 at 08 58 08" src="https://user-images.githubusercontent.com/2361214/42865047-b7454676-8a68-11e8-9e56-d927c3fb7e2a.png">

(Turning ligatures on works for most of the symbols, but the ligatures aren't rendered correctly by the font.)

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F288

**Comment by clason** [comment]
Yes, looks fixed -- thank you!
