### ISSUE TITLE
Snapshot 280 reverted to neovim 0.3.0

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#665]
Snapshot 279 had neovim 0.3.1, which had a few nice fixes. I miss those fixes...

**Comment by qvacua** [comment]
I messed up with git submodules. I'll fix it and build a new snapshot.

**Comment by qvacua** [comment]
Please try the latest snapshot: https://github.com/qvacua/vimr/releases/tag/snapshot%2F291

**Comment by clason** [comment]
All good now, thanks!
