### ISSUE TITLE
[SNAPSHOT-292 (292)] init.vim not being respected in VimR

### ISSUE THREAD

**Issue by synchon** [qvacua/vimr#672]
The latest snapshot breaks the build for NeoVim in VimR. `init.vim` works when `nvim` is executed from terminal. It would be great if someone can help me out. Thanks in advance!

Version info:
- NeoVim: v0.3.1
- Shell: fish, version 2.7.1

**Comment by asimy** [comment]
Still happening in SNAPSHOT-294 (294)

**Comment by johnzim** [comment]
@synchon  @gglanzani  @asimy  FWIW this is fixed if you upgrade your Fish Shell to the 3.x.x releases

**Comment by synchon** [comment]
Thank you for the fix @johnzim, but I don't have a working NeoVim + VimR environment anymore, so I won't be able to test the fix. I think it would be okay to close this issue if @gglanzani and @asimy find the fix working.

**Comment by asimy** [comment]
Verified on both my systems.

**Comment by itszero** [comment]
I have fish 3.0 & vimr 297 and it doesn't source the file. Running `source` on my system gives a few weird errors like not being able to find `git`, sounds like env vars are messed up.

**Comment by arpitchauhan** [comment]
Yes init.nvim isn't being sourced automatically. When I try to source manually, vimr is not able to find git executable. It's not able to locate python3 or ruby either (what checkhealth says).

**Comment by qvacua** [comment]
I cannot reproduce this. `echo $PATH` in both fish and VimR coincide and `init.vim` is read. I used

* fish: 3.0.2
* VimR: build 297 (or 298)

Since I don't use fish, my config may have been too simple. My `config.fish` had just the following line

```
set -gx PATH SOME_PATH_1 SOME_PATH_2 $PATH
```

**Comment by itszero** [comment]
Is there any toggle that we can tweak to output more log for debugging?

**Comment by arpitchauhan** [comment]
It worked me after I started vimr with --cur-env, as advised in https://github.com/qvacua/vimr/issues/656

**Comment by tpict** [comment]
Upgrading from fish 2.7.1 to 3.0.2 fixed this for me on macoS

**Comment by arpitchauhan** [comment]
I'm on fish 3.0.2, release 0.26.0 (303), and still I _have_ to do `vimr --cur-env` in order to load vimr correctly. If I start vimr without any options and do `echo $PATH`, I get an empty string back (not so when I use `--cur-env`)

**Comment by qvacua** [comment]
@arpitchauhan Could you download http://taewon.de/ProcessUtils.app.zip and run it? It does runs the same code VimR uses to

1. find out the `SHELL`
2. to get the value of `PATH`

and display them.

**Comment by arpitchauhan** [comment]
@qvacua Just wanted to inform you that this is no longer an issue for me. Though I have updated VimR to the latest version since my last message (0.26.8), I guess it has to do with me tinkering with the fish shell (for reasons not related to fixing VimR). To be clear, I removed pure fish and some other packages.

**Comment by qvacua** [comment]
Closing; Please feel free to reopen the issue.

**Comment by trekdemo** [comment]
@qvacua Can you point me to the code that is run by VimR and http://taewon.de/ProcessUtils.app.zip  to figure out the `$PATH` and the `$SHELL`? What does the check do?

I'm on fish 3.0.2, but it's still not working for me.
