### ISSUE TITLE
VimR crash after a few seconds

### ISSUE THREAD

**Issue by jaimebuelta** [qvacua/vimr#697]
Since today, after I open VimR, it crashes after loading a file in a few seconds.
Strangely, I updated last week to the newest version `SNAPSHOT-294 (294)` and it was working fine for a couple of days. Previously it was crashing when closing a window.

I am using  MacOS Mojave (10.14.1)

Here's the stack trace. in a [gist](https://gist.github.com/jaimebuelta/327e7533fa8fd563eb5a7ebeddddf41c)

**Comment by ELLIOTTCABLE** [comment]
@jaimebuelta maybe move the stack-trace to a Gist? Makes it easier to track the Issue.

----

Same here; `com.qvacua.NvimView` crash in `NvimView.draw(cursorIn:)`. For me, it occurred several hours after opening.

[Trace](https://gist.github.com/ELLIOTTCABLE/99390f67db28fd8f1ffd84fb057530d2).

**Comment by jaimebuelta** [comment]
(Good point, @ELLIOTTCABLE . I changed it)

**Comment by josephan** [comment]
crashes for me when I press `<ctrl-p>`for fzf.vim

**Comment by bsergean** [comment]
I'm getting the same crash as well and I'm also on macOS Mojave.

**Comment by bsergean** [comment]
:healthcheck reproduce the crash right away for me.

**Comment by ELLIOTTCABLE** [comment]
For those of us trying to get work done — `SNAPSHOT-290` is the latest version I could find that doesn't suffer from this issue, nor #683. Just a little tip, while our beloved maintainer is busy with other things. `(=`

If you're like me, and can't revert to stable (GUI Vim was nigh-useless for OCaml work until the new `--cur-env` flag! Bravo, by the way!), but keep running into these murderous crashes — here's a helpful, slightly abstracted Homebrew Cask so you can switch snapshots quickly:

```
snapshot = 290

cask 'vimr' do
  version "SNAPSHOT-#{snapshot}"
  sha256 '...'

  url "https://github.com/qvacua/vimr/releases/download/snapshot%2F#{snapshot}/VimR-SNAPSHOT-#{snapshot}.tar.bz2"
  # ...
```

**Comment by qvacua** [comment]
Does this still happen with the newest release?

**Comment by jaimebuelta** [comment]
I've downloaded it and it has gone away. Thanks!

**Comment by qvacua** [comment]
Closing... Please feel free to re-open if it occurs again with the newest builds.
