### ISSUE TITLE
Unicode rendering is broken when ligatures are turned off.

### ISSUE THREAD

**Issue by wookayin** [qvacua/vimr#709]
Hi, thanks for your great work all the time!

Since SNAPSHOT-294 (effective in SNAPSHOT-296 too), non-ascii unicode characters are rendered incorrectly -- such as git markers, powerline fonts, etc. Please see the screenshot:

![image](https://user-images.githubusercontent.com/1009873/53219023-74f22d00-362c-11e9-9476-7407a9a69c85.png)

You can see characters like `✗`, `⇡`, `✱`, `❯❯❯` are rendered in wrong positions.

Previously I was using SNAPSHOT-293 and it was fine with this version. As new rendering codes have been introduced since 294, I believe this change would be the suspect.

Might be related to #705.

**Comment by qvacua** [comment]
I'll have a look at it.

**Comment by jangid** [comment]
Thank you for your great work. The only issue I also face is with unicode; especially the Hindi or Devanagari characters (from India). I have a screen recording. Attaching here. I am showing how it works in neovim and in vimr.

![vimr-hindi](https://user-images.githubusercontent.com/46752/54080900-7015c480-4320-11e9-9372-e1002e091004.gif)

**Comment by qvacua** [comment]
Could you attach a simple text file and a screenshot how it should look?

**Comment by jangid** [comment]
This is the text file containing characters from Hindi.
[devanagari.txt](https://github.com/qvacua/vimr/files/2949204/devanagari.txt)

It should look like this
<img width="76" alt="term-hindi" src="https://user-images.githubusercontent.com/46752/54082312-592f9c00-4339-11e9-9fda-e414ebddf441.png">

I have also created a gist for reference for editor makers; screenshot in comment. https://gist.github.com/jangid/0d38bbf4e22fb93a166adab9bbc68b08

**Comment by qvacua** [comment]
This is strange. When I open the file, I get the following rendering:

<img width="1101" alt="Screenshot 2019-03-10 at 19 12 30" src="https://user-images.githubusercontent.com/460034/54089364-79c31a80-4368-11e9-9fb9-14a65511318b.png">

which seems to be correct.

**Comment by wookayin** [comment]
This is what I get (vimr 0.26.3, macOS 1.14 Mojave):

![image](https://user-images.githubusercontent.com/1009873/54089413-0527b600-433f-11e9-8fa0-adfe9aa2af24.png)

**Comment by qvacua** [comment]
I see. I have the "Use Ligatures" in the Appearance Preferences turned on. If I turn it off, the rendering broken. @wookayin, @jangid:  Please turn it on until the bug is fixed.

**Comment by wookayin** [comment]
Great point! That works like a charm --- all the unicode markers including powerline symbols are rendered correctly with "Use Ligatures" turned on.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/v0.26.4-307 (also with ligatures turned off 😀).

**Comment by jangid** [comment]
This build is working👌. Although there are more issue related to Hindi i.e. Devanagari rendering. But I suppose those needs to be fixed in NeoVim. Attached is text file and screenshot.

[sample.txt](https://github.com/qvacua/vimr/files/2951224/sample.txt)
<img width="1101" alt="sample" src="https://user-images.githubusercontent.com/46752/54109085-aa0bc700-4403-11e9-9292-8f4bb81f3988.png">

**Comment by qvacua** [comment]
@jangid : Try to turn on "Use Ligatures" in the Appearance Pref. The rendering looks better (at least for me).

**Comment by jangid** [comment]
Yes. This works reasonably. Thanks. 

11 मार्च 2019 को अ 5:18 पर Tae Won Ha <notifications@github.com> ने लिखा :
