### ISSUE TITLE
Possible to inject current environment to vimr.app, besides using CLI option

### ISSUE THREAD

**Issue by Guzzii** [qvacua/vimr#710]
Hi @qvacua . Really enjoy your work here. I had struggled a bit using the app. The app would just show a raw Neovim window when I click the app icon in `Applications`, not aware of `init.vim`, `python` executable and all the plugins. Manually loading `init.vim` doesn't really help much because the dependencies are not present to the Neovim process without knowing the environment. However, when I found out that there is an option to pass all the environment variables to vimr via, 
```bash
$ vimr --cur-env files
```
it is now all good and really enjoyable.

I am wondering if it is possible to pass all the environment variables to vimr.app by default, so that we are limited to use the cli tools always.

**Comment by qvacua** [comment]
What's your `SHELL`?  Usually VimR should pick up your shell and its environment variables? And yes, for things like `virtualenv`  you have to use the CLI tool.

**Comment by Guzzii** [comment]
Thanks for the reply. I am currently using fish shell. For some reason, after reboot the laptop, VimR.app was able to pick up the shell and env. Do you have any clue what could be the cause in this situation here?
