### ISSUE TITLE
"line spacing" option not working

### ISSUE THREAD

**Issue by ccshao** [qvacua/vimr#711]
I modified the "line spacing" option in the "Appearance" panel, however, nothing changes.
Restart vimr does not solve the problem. 

I am using the later vimr under 10.13.6.

**Comment by qvacua** [comment]
The latest snapshot (302) has got it fixed. So, the next release will have it fixed, too. I'll close this issue once the release is done.

**Comment by qvacua** [comment]
Try <https://github.com/qvacua/vimr/releases/tag/v0.26.0-303>.
