### ISSUE TITLE
different display korean words in powerline with normal vim in terminal

### ISSUE THREAD

**Issue by soomtong** [qvacua/vimr#713]
i saw those previus issues related powerline with termguicolors option.
but it's not same. little difficult for me.

as u see below screenshot. i am using D2Coding (from naver.com)
the first is vimr's top line
![image](https://user-images.githubusercontent.com/906974/54499758-9fe44e00-4958-11e9-8c4e-d05f8625988a.png)
and this is vimr's bottom line
![image](https://user-images.githubusercontent.com/906974/54499774-d326dd00-4958-11e9-876a-419197601523.png)

this is original vim(neovim) screenshots. it works.
![image](https://user-images.githubusercontent.com/906974/54499784-f3ef3280-4958-11e9-8128-6db9e4977c79.png)
![image](https://user-images.githubusercontent.com/906974/54499796-0f5a3d80-4959-11e9-9b18-82c81c8e9e90.png)

thanks!

**Comment by qvacua** [comment]
I'll have a look at it.

**Comment by qvacua** [comment]
This seems to be an issue of Neovim: neovim/neovim#4476. I don't know how the terminal is able to display the names correctly though...
