### ISSUE TITLE
how to support nvim 0.4.0 prerelease?

### ISSUE THREAD

**Issue by epheien** [qvacua/vimr#714]
I think vimr support external nvim is better

**Comment by qvacua** [comment]
@epheien There is the `update-neovim` branch which tracks the `master` branch of Neovim. I'll think about publishing nightlies (or weeklies 😀).

**Comment by josemarluedke** [comment]
Looking forward to use nvim 0.4.0 prerelease as well. Any updates on this?

**Comment by jerrywang1981** [comment]
> @epheien There is the `update-neovim` branch which tracks the `master` branch of Neovim. I'll think about publishing nightlies (or weeklies 😀).

I tried update-neovim branch and it looked like it didn't work, it is still nvim 0.3.4.

**Comment by qvacua** [comment]
Please try <https://github.com/qvacua/vimr/releases/tag/neovim-nightly>.

**Comment by qvacua** [comment]
@jerrywang1981 How did you build the branch?

**Comment by qvacua** [comment]
Ups, the build is broken. I'll re-upload.

**Comment by qvacua** [comment]
Done: https://github.com/qvacua/vimr/releases/tag/neovim-nightly

**Comment by kropper** [comment]
Thank you, thank you, thank you!

**Comment by jerrywang1981** [comment]
thanks a lot.

**Comment by kongluoxing** [comment]
neovim has just released 0.4.2
can you update vimr with it? thanks you!
