### ISSUE TITLE
Unable to run any version since v0.25.0

### ISSUE THREAD

**Issue by sanmiguel** [qvacua/vimr#715]
Hi there, before I go into this I want to say a big "Thanks!" for all your hard work on VimR. I've been using it as my editor daily for a few months now and, aside from a couple of bugs leading to the occasional crash it's been great!

Unfortunately the latest string of releases seem to be completely broken for me :(

I've just tested running every build from v0.25.0 through v0.26.9, and none of them will start. I can provide the full crash report privately if you would like to see it, or provide any specific details you need but the highlights are:
 - MacOs 10.12.6
 - VimR > v0.25.0 (v0.25.0 works fine for me)
 - VimR crashes as soon as I open it and cannot run.

Crash report contains the following:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSControllerTreeProxy representedObject]: unrecognized selector sent to instance 0x60800000abc0'
terminating with uncaught exception of type NSException
abort() called
```

**Comment by qvacua** [comment]
@sanmiguel I am very sorry, but I am not able to test this since both my desktop and laptop are already on macOS 10.14... Yes, please send me the report; maybe one can see something..

**Comment by froatsnook** [comment]
Also experiencing this.  Workaround is to use this version: https://github.com/qvacua/vimr/releases/tag/v0.25.0-297 but will have to upgrade macos sooner or later 😬.

**Comment by qvacua** [comment]
I checked on a fresh installation of 10.13 (on a virtual machine) and VimR works fine. I could not test it on 10.12 though since I could not download the installer. I think I don't have any option other than to raise the requirement to 10.13.... When done, I'll close this issue. Sorry, guys.

**Comment by qvacua** [comment]
From [SNAPSHOT-315](https://github.com/qvacua/vimr/releases/tag/snapshot%2F315) on 10.13 is required.
