### ISSUE TITLE
Doesn't find init.vim

### ISSUE THREAD

**Issue by jorenvanhee** [qvacua/vimr#716]
Vimr doesn't find my init.vim file. I ran a health check and it says "Missing user config file: ~/.config/nvim/init.vim". I also ran `:!cat ~/.config/nvim/init.vim` to make sure it exists. Sourcing the file manually also works.

![Screenshot 2019-04-04 at 11 34 43](https://user-images.githubusercontent.com/231202/55545840-6177be80-56ce-11e9-9460-1e491630d91a.png)

macOS Mojave 10.14.3
VimR 0.26.9

**Comment by saewoonam** [comment]
I have the same problem... I was trying to upgrade from 0.24.0 (282) to 0.26.10.  I find this is a problem for all the 0.26.x versions.

![image](https://user-images.githubusercontent.com/2872116/56850820-e7011f80-68c4-11e9-9a19-4340e457ea75.png)

I also have a problem with the $PATH.   I am not getting anything when I try :echo $PATH
This may be the reason why it can't find python2 or python3.   

In contrast, everything works in version 0.24.0

MacOS 10.14.4

**Comment by qvacua** [comment]
That's really strange. What Shell do you use? Could you please run http://taewon.de/ProcessUtils.app.zip and tell me whether the output looks reasonable? (It will try to find out the $PATH and $SHELL with the same code as in VimR)

**Comment by saewoonam** [comment]
The output is not good.... I've attached a picture below.  
I use fish
I could switch back to bash.   It is strange that the earlier release (0.24) works fine.... 

![image](https://user-images.githubusercontent.com/2872116/57016750-166f9f00-6bd9-11e9-9c02-46794689ca85.png)

**Comment by qvacua** [comment]
Have you had a look at https://github.com/qvacua/vimr/issues/672? There people had similar issues with `fish`.

**Comment by saewoonam** [comment]
Great... This is relevant.   The problem seems to have been with fish.   I upgraded from 2.7.1 to 3.0.2 and it now works... I did not investigate the issue with the older versions of fish.

Thank you for helping me resolve this issue...

**Comment by qvacua** [comment]
OK, glad it worked out. I'll close this issue.

**Comment by realtica** [comment]
Same here but on Linux:

```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

Debian GNU/Linux 11 (bullseye)

❯ echo $MYVIMRC
~/.config/nvim/init.vim

❯ echo $XDG_CONFIG_HOME
/home/realtica/.config

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

nvim: health#nvim#check
========================================================================
## Configuration
  - WARNING: Missing user config file: ~/.config/nvim/init.vim
    - ADVICE:
      - :help |init.vim|

```

Something rare happens when I set:
export VIMINIT="$XDG_CONFIG_HOME/nvim/init.vim"

```
Error detected while processing VIMINIT:
E486: Pattern not found: home
Press ENTER or type command to continue
```
