### ISSUE TITLE
latest update put these ugly tab things at top of page, please advise.

### ISSUE THREAD

**Issue by kswope** [qvacua/vimr#734]
I think they are called tabpages?  Might be a neovim creation.  But somehow the latest vimr is telling neovim to put them in now.  I don't want them there.  I can't be the only one with this issue.

**Comment by qvacua** [comment]
Could you post a screenshot?

**Comment by kswope** [comment]
I found how to reproduce.  Run the vimr command line script for each file and they are added to the main window as tabs.  MacVim seems to not have this feature - probably because it doesn't use neovim.

The below situation was created by
```
$ /usr/local/bin/vimr vpc.yml
$ /usr/local/bin/vimr fargate.yml
$ /usr/local/bin/vimr README.md
```

![image](https://user-images.githubusercontent.com/321586/61655768-34efae80-ac8d-11e9-9ec0-be1c22c7a719.png)

**Comment by kswope** [comment]
Found more info, but pertaining to MacVim

https://stackoverflow.com/questions/13661997/strange-bar-at-top-of-my-macvim

**Comment by kswope** [comment]
For anybody interested something about the command line script forces new tabs.

You can probably disable this with in your config file.
```
set showtabline=0
```
