### ISSUE TITLE
High CPU usage in v0.27.4-326

### ISSUE THREAD

**Issue by tombruijn** [qvacua/vimr#735]
On start I get a CPU usage in the VimR process that spikes quite regularly (multiple times in a minute), 100% and 200% spikes are not uncommon. It's not a consistent CPU usage of 100% and higher, but it spikes and drops back down on its own.

VimR 0.27.4 (326)
macOS 10.14.5

Let me know if you need more information to help reproduce this.

## Steps to reproduce

```
vimr --nvim -u NONE
```

- It occurs when I start VimR without any config or any file.
  - Just opening a `[No name]` buffer causes this behavior.
- It occurs when VimR has focus and when it does not.

I've completely uninstalled VimR and reinstalled it to see if that would fix it, but unfortunately it did not.

## Resulting behavior

- VimR is reported with high CPU usage in Activity Monitor.

![Activity Monitor (All Processes) 2019-07-18 15-18-13](https://user-images.githubusercontent.com/282402/61460621-5c820680-a96f-11e9-83ec-9204be75a7ab.png)

**Comment by qvacua** [comment]
I'll look into it.

**Comment by tombruijn** [comment]
Great! Thanks :)
Let me know if you need any more information, logs or anything else

**Comment by mzgnr** [comment]
@qvacua also having this issue with SNAPSHOT-330

**Comment by stepancheg** [comment]
I have it too in version 343.

Just in case, this is sample output: https://gist.github.com/stepancheg/ec78579e003d023f18e644ff694d3d6b

**Comment by tombruijn** [comment]
I am no longer seeing this in the latest release and snapshot. I haven't used in VimR in a while so I don't know since which version this is no longer an issue.

Current VimR version, tried on both:

- 0.34.0 (355)
- SNAPSHOT-20210220.153052 (20210220.153052)
