### ISSUE TITLE
Search highlight displays incorrectly for gui=reverse

### ISSUE THREAD

**Issue by bronzehedwick** [qvacua/vimr#750]
I've been testing this issue a bit and I think I've narrowed it down: Vimr does not render the `gui=reverse` theme command correctly.

The gruvbox theme uses the `reverse` command in it's Search group theming. This looks fine until you move your cursor over search highlighted text. 

![gruvbox-highlight-1](https://user-images.githubusercontent.com/637174/64963598-840a2800-d867-11e9-8bbf-3f1375fa3c2b.png)

This only happens in Vimr, not terminal neovim, or neovim-qt, the other GUI I tested.

![gruvbox-terminal-highlight](https://user-images.githubusercontent.com/637174/64963653-9edc9c80-d867-11e9-9146-be0b5c26fb03.png)
_Terminal_

![gruvbox-nvim-qt-highlight](https://user-images.githubusercontent.com/637174/64963666-a603aa80-d867-11e9-9b59-50c954526512.png)
_neovim-qt_

This doesn't happen in themes that do not use reverse, such as OceanicNext:

![oceanic-next-highlight](https://user-images.githubusercontent.com/637174/64963810-db0ffd00-d867-11e9-820d-eef9f556c8a9.png)

Here's a screenshot of gruvbox and OceanicNext's Search group highlight for reference:

![Screen Shot 2019-09-16 at 9 43 46 AM](https://user-images.githubusercontent.com/637174/64963890-fa0e8f00-d867-11e9-81fb-e26fca0ece85.png)
_gruvbox_

![Screen Shot 2019-09-16 at 9 44 49 AM](https://user-images.githubusercontent.com/637174/64963900-fd097f80-d867-11e9-9ffc-7dffd252dad2.png)
_OceanicNext_

Thanks!

Note: I had originally opened a ticket in gruvbox, before I had investigated the issue more fully. Here's that for reference: https://github.com/gruvbox-community/gruvbox/issues/121

**Comment by edgarcosta** [comment]
I also noticed the same, and I assumed I was going crazy.
The change is somewhere between snapshot 293 and 294: https://github.com/qvacua/vimr/compare/snapshot/293...snapshot/294

**Comment by rluba** [comment]
I finally got annoyed enough by this to fork the project and figure out what’s wrong. Took me forever to be able to build this project, but the fix itself was less than 10 minutes of work. See #849

**Comment by qvacua** [comment]
@rluba Thanks for the PR. I'll have a look this weekend. Yes, I'm afraid the build system is currently a mess, I planned to consolidate once I get an MBP 14(?)....
