### ISSUE TITLE
Update neovim to 0.4.2

### ISSUE THREAD

**Issue by numbcoder** [qvacua/vimr#751]
Neovim 0.4.2 has been released https://github.com/neovim/neovim/releases/tag/v0.4.2

**Comment by josemarluedke** [comment]
I'm really looking forward to a new release of vimr with neovim 0.4.2. 👍

**Comment by DemonCloud** [comment]
please support neovim 0.4.2

**Comment by numbcoder** [comment]
New release: https://github.com/qvacua/vimr/releases/tag/v0.28.0-328
