### ISSUE TITLE
Unable to load parinfer-rust dylib because of code signing

### ISSUE THREAD

**Issue by eraserhd** [qvacua/vimr#762]
From @adamneilson:

> It finds it now but I'm getting an error about code signature not valid for use in process using Library Validation: `mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.`

> This is only when I use VimR but when running nvim directly within a terminal it works without any issue.

See eraserhd/parinfer-rust#42 .  I'm not running VimR personally, but from that issue, it looks like this is affecting several users.   My DLL is distributed in source only, so they build it themselves with normal Rust tooling.

EDIT: More info, parinfer-rust is a Vim plugin with a shared library part which is invoked using Vim's `libcall()`.

**Comment by eraserhd** [comment]
I did some write-up about this, collected some evidence, and I believe adding the "Disable Library Validation" is the right solution.

https://github.com/eraserhd/parinfer-rust/blob/master/extra-docs/MacOS-Code-Signing.adoc

**Comment by adamneilson** [comment]
Hopefully this new prerequisite should solve this issue?
https://developer.apple.com/news/?id=12232019a

**Comment by eraserhd** [comment]
I read it as a temporary reprieve, and that the same prerequisites that are causing problems will be in effect Feb 3, though I'm not sure I'm reading it correctly.

**Comment by vlaw** [comment]
I've got the same problem when I use the [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch#about) and [airline-xkblayout](https://github.com/vim-airline/vim-airline/blob/48064e24d5d1fd715b2366444a09475bcbe03879/doc/airline.txt#L1435).

```
let g:XkbSwitchLib = '/usr/local/lib/libInputSourceSwitcher.dylib'
```

**Comment by lispyclouds** [comment]
Hello @qvacua !
Can this issue be addressed if possible? Im a huge huge fan of vimr and trying to use it for clojure development and i got hit by this and its blocking it now.
I am more than happy to contribute this if possible, but im not at all experienced with Swift on XCode. Searching I found https://github.com/opencv/opencv/issues/15645#issuecomment-554495051 and if I could get some help in where to set this I can definitely raise a PR! 😄

**Comment by qvacua** [comment]
I'll try to fix this, but when codesigning and entitlements are involved, it could take a while.

**Comment by lispyclouds** [comment]
Thanks a lot and kudos for the amazing vimr! 👍

**Comment by qvacua** [comment]
Could you try http://taewon.de/VimR-SNAPSHOT-351.tar.bz2 ? I turned on "Disable Library Validation" for the background Neovim binary.

**Comment by lispyclouds** [comment]
This WORKS!!
Before
<img width="2032" alt="Screenshot 2020-06-23 at 20 01 52" src="https://user-images.githubusercontent.com/5615588/85438632-7323db00-b58c-11ea-9295-2fa24c2b9b46.png">
After:
<img width="2032" alt="Screenshot 2020-06-23 at 20 01 27" src="https://user-images.githubusercontent.com/5615588/85438664-7cad4300-b58c-11ea-825f-8baa57a8f0c1.png">
Thanks a ton! can't wait for the release!! 😄

**Comment by qvacua** [comment]
I‘ve built a snapshot: https://github.com/qvacua/vimr/releases/tag/snapshot%2F352
