### ISSUE TITLE
 v0.29.0-329 crash when opening vimR from terminal

### ISSUE THREAD

**Issue by numbcoder** [qvacua/vimr#765]
The vimR application crashed when execute the `vimr` command from terminal after updated vimR to 0.29.0

**Comment by pechorin** [comment]
The same problem :/

**Comment by josemarluedke** [comment]
Same here.

**Comment by numbcoder** [comment]
After upgraded to SNAPSHOT-330, it don't crash but CPU 100%

**Comment by qvacua** [comment]
I'll look into it.

**Comment by numbcoder** [comment]
SNAPSHOT-330
1. Open VimR from LaunchPad, it works well
2. Execute the `vimr` command from terminal, the VimR application hangs and CPU 100%

VimR is my most favourite editor. Thank you for your work!

**Comment by numbcoder** [comment]
SNAPSHOT-331 still has the same issue，and I found it was caused by coc.vim, relate issue: https://github.com/qvacua/vimr/issues/768

Vimr works well after removed the coc.nvim plugin, but coc.nvim has no issue in nvim and macvim

**Comment by jk-gan** [comment]
I tested with [v0.30.0-335](https://github.com/qvacua/vimr/releases/tag/v0.30.0-335), the issue is fixed

**Comment by josemarluedke** [comment]
I can also confirm that the latest version has this issue fixed.
