### ISSUE TITLE
Wrong position of input method

### ISSUE THREAD

**Issue by syllr** [qvacua/vimr#766]
hello this is my first time to use vimr，i found when i type chinese the input method is at wrong position.
* os: macos 10.15.1
* version: 0.27.5
![WechatIMG6.png](https://i.loli.net/2019/11/29/ZwdmYQh7l4ktUDg.png)

**Comment by qvacua** [comment]
The position problem seems to be fixed (try https://github.com/qvacua/vimr/releases/tag/snapshot%2F356), but VimR seems to have a general problem with Chinese input methods. Since I don't know Chinese, it could take some time to fix this...

**Comment by syllr** [comment]
Thank you
