### ISSUE TITLE
Calling :Man crashes Vimr

### ISSUE THREAD

**Issue by bronzehedwick** [qvacua/vimr#767]
## Steps to reproduce

1. Open Vimr
2. Call `:Man` on any command
3. Notice Vimr stops responding

**Comment by DemonCloud** [comment]
Crash same

**Comment by qvacua** [comment]
I cannot reproduce it with https://github.com/qvacua/vimr/releases/tag/v0.32.0-344

**Comment by bronzehedwick** [comment]
Thanks @qvacua , I'm no longer seeing this issue on the latest version.
