### ISSUE TITLE
Feature request: Dark mode for markdown and html viewer.

### ISSUE THREAD

**Issue by ripley** [qvacua/vimr#775]
It's a nice application which supports both VIM and Markdown, but could you add dark theme for markdown and html viewer? When working in dark theme under Mac it's very distracting to used two difference styles at the same time.

**Comment by qvacua** [comment]
Please try the latest snapshot: https://github.com/qvacua/vimr/releases

**Comment by wookayin** [comment]
Can we instead use different colorscheme for vim and markdown/html (Related #732 regarding configuraiton point)?
