### ISSUE TITLE
Unknown option: guifont

### ISSUE THREAD

**Issue by Mishail** [qvacua/vimr#779]
For some reason, vimr recently started to complain about `guifont` option, and that doesn't happen if I use plain neovim:

```
Error detected while processing <path>/vim/vimfiles/init.vim:
line   69:
E518: Unknown option: guifont=Hasklig:h12
```

VimR version:
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -mmacosx-version-min=10.13 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/config -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/src -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/.deps/usr/include -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/third-party/libintl/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/src/nvim/auto -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/include
Compiled by hat@iota.local

Features: +acl +iconv -tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by kuntau** [comment]
You set vimr font on it's preference panel and not in init file unlike gvim

**Comment by GreyTeardrop** [comment]
I'm running into this issue with VimR 0.32.0 as well, had to go back to 0.31.0 for now.

As far as I understand, here's what's going on: I'm using SpaceVim distribution, and it has some [generic code](https://github.com/SpaceVim/SpaceVim/blob/331139505ad257bb2e1df6f44557aeda8b247a24/ginit.vim) in there that checks for `gui_running` flag and sets `guifont` to something (some of those checks were added specifically [for VimR](https://github.com/SpaceVim/SpaceVim/pull/1651). This used to work fine in VimR up to 0.31.0 cause it did not have `gui_running` set so no issues with `guifont` either, but 0.32.0 completely breaks that. The sad part is it's not just `guifont` can't be set that way; the complete configuration fails to be loaded now.

**Comment by hsheikhali** [comment]
@kuntau not all fonts are available in the preferences panel.. figure out how to get other fonts in preferences?

**Comment by AllenDang** [comment]
Any update on this issue? I'm using SpaceVim too and VimR becomes unusable now.

**Comment by ncihnegn** [comment]
You can use my fork https://github.com/ncihnegn/vimr for such compatibility.

**Comment by hsheikhali** [comment]
@ncihnegn does this allow us to select the font from the settings menu as well?

**Comment by ncihnegn** [comment]
> @ncihnegn does this allow us to select the font from the settings menu as well?

Yes.

**Comment by hsheikhali** [comment]
not sure why but every time I run `code_sign=false use_carthage_cache=false ./bin/build_vimr.sh` i get this error: `### Building VimR target
./bin/build_vimr.sh: line 11: carthage_update: true or false`

**Comment by hsheikhali** [comment]
well its not really an error more so does nothing..

**Comment by hsheikhali** [comment]
nvm fixed it.

**Comment by GreyTeardrop** [comment]
SpaceVim 1.5.0 has merged a [workaround](https://github.com/SpaceVim/SpaceVim/pull/3547) for this VimR issue. I'm able to start SpaceVim 1.5.0 on the latest as-of-now VimR 0.33.1.

**Comment by Shirk** [comment]
If I can get vimR to compile on my Mac I'm going to have a look into this.
Neovim provides the `guifont` option even if run in a terminal simply because it's a default option that plugins can check for. IMO breaking plugins because "You set vimr font on it's preference panel and not in init file unlike gvim" is a giant no-go. MacVim also allows you to set the font on it's preference panel yet provides a working `guifont` option.

And just to be clear - I'm not talking about not being able to set `guifont` but about the fact that a default vim / nvim global is not available and there is no way for plugins to test for it or work around without specifically considering vimR.
