### ISSUE TITLE
font selector in v0.32.0 doesn't find all monospace fonts

### ISSUE THREAD

**Issue by hakamadare** [qvacua/vimr#781]
i have a couple of different Inconsolata fonts installed (Inconsolata Nerd Font from https://www.nerdfonts.com/, Inconsolata for Powerline from https://github.com/powerline/fonts/tree/master/Inconsolata), and the selector in v0.32.0's preferences dialog doesn't detect any of them.
![Screen Shot 2020-03-05 at 11 58 28 AM](https://user-images.githubusercontent.com/154395/76005672-5b3f2300-5ed9-11ea-91f6-3afff180fea1.png)
is there additional information i can provide that would be helpful in debugging?

**Comment by JayceCao** [comment]
Encounter the same problem. I can only find these:
![image](https://user-images.githubusercontent.com/17915615/76773473-7b29ed00-67dd-11ea-9808-725c1015eb58.png)
![image](https://user-images.githubusercontent.com/17915615/76773554-9c8ad900-67dd-11ea-8ff3-475a765a948f.png)

**Comment by pechorin** [comment]
Where are also no way to select font variant like with `Isevka` font: `Iosevka regular`, `Iosevka Retina`, `Iosveka Light`, `Iosevka regular`. Please provide this ability (it was possible in previous releases)

**Comment by wookayin** [comment]
+1 for font weights -- it is gone and we look forward to having it again!

**Comment by hsheikhali** [comment]
I'm also encountering this issue -- is there anyway to access the other fonts ?
