### ISSUE TITLE
Store preferences in a plain text format

### ISSUE THREAD

**Issue by cweagans** [qvacua/vimr#795]
I would like to commit my VimR config to my dotfiles repo. Right now, I can do it, but the file isn't that useful since it's a binary plist. It would be much better if this were a yaml file or something.

**Comment by cweagans** [comment]
Also, this file changes every time I move the window in vimr. This is extremely annoying :/

**Comment by kuntau** [comment]
What kind of config did you need to save? You can set anything in `init.vim`

**Comment by cweagans** [comment]
I want to turn off the tools, set the font and font size, and remove a couple shortcuts -- all information that's already in the vimr config that's written to ~/Library. I just want to version what's already there.

**Comment by kuntau** [comment]
you can set all that in `~/.config/nvim/ginit.vim`

You can use the following commands to control some of GUI elements

- `VimRMaximizeWindow`
- `VimRToggleFullscreen`
- `VimRHideTools`, `VimRToggleTools`, `VimRShowTools`
- `VimRHideToolButtons`, `VimRToggleToolButtons`, `VimRShowToolButtons`
- `VimRMakeSessionTemporary`: VimR does not store GUI settings, e.g. window size, visibility of tools and tool buttons.
- `VimRSetFontAndSize "Some Font Name", 13`: Set the font and the size to *Some Font Name and 13*, respectively. The size must be an integer.
- `VimRSetLinespacing 1.0`: Set the linespacing to 1.0. The value must be a float.

**Comment by cweagans** [comment]
oh! well that's just awesome then :) thanks for the info!
