### ISSUE TITLE
Support for running a command on startup

### ISSUE THREAD

**Issue by nwaywood** [qvacua/vimr#796]
Neovim has the following command line flag:

`+<cmd>, -c <cmd>      Execute <cmd> after config and first file`

which lets you run a command on startup.

It would be awesome to be able to do this with `vimr` as well :)

**Comment by kuntau** [comment]
Of course you can.. just put `--nvim` flag before your `<cmd`

eg: `vimr --nvim -c "colo gruvbox" <filename>`

**Comment by nwaywood** [comment]
@kuntau Yes that works! Thank you :)
