### ISSUE TITLE
High CPU Usage on Mac OS Catalina 10.15

### ISSUE THREAD

**Issue by rupeshk** [qvacua/vimr#799]
VimR consistently shows high CPU usage on Mac OS Catalina 10.15

Version- 0.32.0 Snapshot 347

**Comment by qvacua** [comment]
Yes, I'm experiencing it as well. I'll try to fix it timely.

**Comment by qvacua** [comment]
@rupeshk Could you please try http://taewon.de/VimR-SNAPSHOT-349.tar.bz2 and see whether the high CPU usage occurs? I suspect that the handling of file system changes in the file browser is the culprit. I just deactivated the handling in the linked version. Thus, the file browser will not work as intended.

**Comment by qvacua** [comment]
I think I found the issue: Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F350

**Comment by rupeshk** [comment]
@qvacua Apologies for the delayed response. It seems fixed now. I will keep an eye on any regressions.
