### ISSUE TITLE
Environment (locale) not set up correctly

### ISSUE THREAD

**Issue by clason** [qvacua/vimr#807]
It seems that VimR does not set up the environment (and in particular the locale) correctly; for some reason, this seems to particularly affect software installed via homebrew (see #806) -- especially python3.

Here's the output of VimR (snapshot 356, macOS 10.15.6beta) when starting from the Finder and calling `:checkhealth`:
```
## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          Checking /usr/local/bin/python3 caused an unknown error. (1, output: Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
          Python runtime state: preinitialized
          
          ) Report this at https://github.com/neovim/neovim
          python3.9 not found in search path or not executable.
          Checking /usr/local/bin/python3.8 caused an unknown error. (1, output: Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
          Python runtime state: preinitialized
          
          ) Report this at https://github.com/neovim/neovim
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          /usr/bin/python is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found
```
The same error (`config_get_locale_encoding`) occurs when starting `python3` inside neovim's terminal. 
Needless to say, everything works fine when neovim is started from the terminal; I also don't get an error if VimR is started via the `vimr` CLI tool from the terminal.

Here is the relevant locale information from `env`:

Inside VimR terminal:
```
LANG=en_US
LANGUAGE=
LC_ALL=
LC_MESSAGES=en_US
```
In Terminal/iTerm:
```
LC_CTYPE=en_US.UTF-8
```
Starting `env LC_CTYPE=en.US.UTF-8 python3` (I'm using `fish`) from inside VimR terminal works as well.

**Comment by qvacua** [comment]
Could you run http://taewon.de/EnvTest.app.zip whether all your env vars are printed? This test app uses the code from VimR that extracts env vars using your `$SHELL`. The code can be seen in <https://github.com/qvacua/vimr/blob/develop/NvimView/EnvTest/AppDelegate.swift>.

**Comment by clason** [comment]
The output is 
```
EDITOR: nvim
LOGNAME: clason
LC_ALL: en_US.UTF-8
HOME: /Users/clason
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.WOu7hIBoZR/Listeners
XPC_SERVICE_NAME: 0
SHELL: /bin/bash
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
TMPDIR: /var/folders/02/1c5nlx115gj3hh6ft8zddfkm0000gn/T/
PWD: /Users/clason
PATH: /Users/clason/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
COMMAND_MODE: unix2003
SHLVL: 1
VISUAL: nvim
_: /usr/bin/env
XPC_FLAGS: 0x0
TEXEDIT: nvim +%d '%s'
USER: clason
```
compared to terminal
```
EDITOR=nvim
HOME=/Users/clason
HOMEBREW_GITHUB_API_TOKEN=24899ba5fd8fb2a67f34c4ed8699bc7b24605059
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8
LOGNAME=clason
PATH=/usr/local/texlive/2020/bin/x86_64-darwin:/usr/local/bin:/usr/local/sbin:/usr/local/opt/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin
PWD=/Users/clason
SHELL=/bin/bash
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.WOu7hIBoZR/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=433
TERM_SESSION_ID=06A0E33D-2702-4072-B3FE-A4BA6591B558
TEXEDIT=nvim +%d %s
TMPDIR=/var/folders/02/1c5nlx115gj3hh6ft8zddfkm0000gn/T/
USER=clason
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
```

**Comment by clason** [comment]
Oh, and this may also be (more?) relevant: `:checkhealth` also reports
```
## terminal
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
```

**Comment by qvacua** [comment]
VimR uses the `SHELL` variable to extract the env vars. In both cases your `SHELL` is `/bin/bash`. Is your login shell (set in System Preferences) different to the shell you're using in the Terminal/iTerm app?

(FYI: I've deleted the GITHUB_API_TOKEN from your comment)

**Comment by clason** [comment]
> (FYI: I've deleted the GITHUB_API_TOKEN from your comment)

Thank you, I just noticed that! 🤦 Should probably reset that now...

> VimR uses the SHELL variable to extract the env vars. In both cases your SHELL is /bin/bash. Is your login shell (set in System Preferences) different to the shell you're using in the Terminal/iTerm app?

Login shell is (still) set to /bin/bash; I'm using fish as a terminal shell (also for nvim). Setting the login shell to zsh and starting Terminal with the default shell gives the following `env`:

```
TMPDIR=/var/folders/02/1c5nlx115gj3hh6ft8zddfkm0000gn/T/
XPC_FLAGS=0x0
TERM_PROGRAM_VERSION=433
TERM_PROGRAM=Apple_Terminal
XPC_SERVICE_NAME=0
TERM_SESSION_ID=BE11D721-79F5-4095-B215-7E744040F7EC
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.WOu7hIBoZR/Listeners
SHELL=/bin/zsh
HOME=/Users/clason
LOGNAME=clason
USER=clason
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/opt/fzf/bin
SHLVL=1
PWD=/Users/clason
OLDPWD=/Users/clason
LC_ALL=en_US.UTF-8
LC_CTYPE=UTF-8
_=/usr/bin/env
```

**Comment by SolaWing** [comment]
I have similar problem, In my .bash_profile, I set
`export LANG='zh_CN.UTF-8'`

it's work in terminal nvim
but in vimr, !env output `LANG=en_US.UTF-8`

**Comment by qvacua** [comment]
@SolaWing : that's my fault. VimR explicitly sets `LANG` to `en_US.UTF-8. I did that at some point due to a paste problem. Probably I can revert that and let the env var set by the user. Will do

**Comment by qvacua** [comment]
@clason The report about `TERM` should have no effect on the functionality of VimR/Neovim.
@SolaWing Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F357

**Comment by clason** [comment]
@qvacua I am sorry, but snapshot 357 did not solve the original issue with python (even if the `TERM` health check is irrelevant).

**Comment by qvacua** [comment]
@clason : What happens when you set your login shell to fish, which you are using in Terminal?

**Comment by clason** [comment]
`fish` as well, but I have also tested with `zsh` (default), so I don't think it's fish-related.

**Comment by qvacua** [comment]
@clason : Is the "Use interactive mode for zsh" under Preferences -> Advanced turned on? If not, can you please try it?

**Comment by clason** [comment]
I tried both; unfortunately, it doesn't make a difference.

**Comment by clason** [comment]
Turns out the issue was between keyboard and chair: I have `lang en_US` set in my `init.vim`; turns out that if `LC_CTYPE` isn't set in `.zshenv` and vimR is started via Finder, _this_ is what vimR takes as `LC_CTYPE`, which no longer seems legal in Python 3.8. (If vimR is started via Terminal, the -- correctly set -- options from there are used instead.)

Changing the option to `lang en_US.UTF-8` fixed the issues.
