### ISSUE TITLE
Choosing certain fonts has no effect on VimR's appearence

### ISSUE THREAD

**Issue by ravicious** [qvacua/vimr#812]
Version 0.34.0 (355), macOS 10.15

I just bought [Comic Code Ligatures](https://www.myfonts.com/fonts/tabular-type-foundry/comic-code-ligatures) and wanted to use it in VimR.

However, if I choose it from the font selector, nothing changes in the actual editor windows, even though the preview renders properly.

![vimr-appearence](https://user-images.githubusercontent.com/27113/90928266-da2c0780-e3f6-11ea-8859-1610b4f34d07.png)

Same thing happens if I choose a bunch of other fonts like Arial or Georgia. Choosing fonts like Monaco or Fira Code updates the editor though.

I tried restarting VimR, but that didn't help.

**Comment by muxcmux** [comment]
Has anyone found a solution to this? I'm trying to use a patched version of SF Mono (with powerline symbols), but I can't seem to make it work. I've also noticed that the font doesn't appear under "Fixed Width" collection. Maybe a problem with the font itself not reporting as being fixed width? Any pointers or suggestions welcome!

**Comment by ravicious** [comment]
I switched to [neovim-qt](https://github.com/equalsraf/neovim-qt). It has its own share of rendering problems, but it doesn’t have this particular problem.

**Comment by numbcoder** [comment]
I found that it only works if the font you selected is in the **Fixed Width** collection.

**Comment by numbcoder** [comment]
ping @qvacua

**Comment by muxcmux** [comment]
I think this is related to https://github.com/qvacua/vimr/issues/819 and https://github.com/qvacua/vimr/issues/526 and I think I've seen a few other issues related to this

**Comment by qvacua** [comment]
Sorry for the late reply. I tried to focus on the universal binary front. Yes, we check whether the font has the fixed width property, as reported by macOS. The problem is, as you mention
1. Some fixed width fonts are not reported as fixed width.
1. The macOS font panel does not allow to filter fonts, i.e. I don't know how to show only fixed width font.

I'll probably just allow all fonts and think about how to approach this issue... I'll build a snapshot in this weekend.

**Comment by numbcoder** [comment]
> Sorry for the late reply. I tried to focus on the universal binary front. Yes, we check whether the font has the fixed width property, as reported by macOS. The problem is, as you mention
> 
> 1. Some fixed width fonts are not reported as fixed width.
> 2. The macOS font panel does not allow to filter fonts, i.e. I don't know how to show only fixed width font.
> 
> I'll probably just allow all fonts and think about how to approach this issue... I'll build a snapshot in this weekend.

Thank you!

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20201121.103800

**Comment by numbcoder** [comment]
> Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20201121.103800

It works well for me! 
Thanks.

**Comment by ravicious** [comment]
Works great, thanks! The notification message is a bit clipped and I don't know how I can read it in full, but otherwise it works just fine. ;)

![2020-11-21 at 15 15](https://user-images.githubusercontent.com/27113/99879324-940c5d00-2c0c-11eb-9928-dd4fd398ea93.png)

**Comment by qvacua** [comment]
If you open the notification center, the whole text will be there.
