### ISSUE TITLE
Font setting not working on SNAPSHOT-20201117.194226

### ISSUE THREAD

**Issue by Keating950** [qvacua/vimr#825]
Font settings seem not to be applied in the latest snapshot, as seen in the image below. (I picked a variable-width font just for illustrative purposes, but the issue occurs with monospace fonts as well.)

OS: macOS Big Sur 11.0.1
VimR version: SNAPSHOT-20201117.194509 (20201117.194226)
<img width="960" alt="vimr_font_bug" src="https://user-images.githubusercontent.com/43932454/99684667-b4db8380-2a4f-11eb-9c0a-e1a941e5b540.png">

**Comment by qvacua** [comment]
Please try: https://github.com/qvacua/vimr/releases/tag/snapshot%2F20201121.103800 and re-open the issue when the issue persists.
