### ISSUE TITLE
Environment variables are not passed correctly to nvim

### ISSUE THREAD

**Issue by blochberger** [qvacua/vimr#832]
As already mentioned in [my comment](https://github.com/qvacua/vimr/issues/625#issuecomment-763441205) on #625, there is a regression in *SNAPSHOT-20201224.200216*: When starting VimR with `vimr --cur-env` the environment is not correctly passed. Invoking `:!env` inside VimR does not show the same environment as from which it was launched. Simply starting `nvim` works fine.

The problem does not occur in *SNAPSHOT-20201210.181940*. Hence, I assume that it might be related to reverting to the old launching logic.

**Comment by bwells** [comment]
Seconded. This is a significant bug for me as it throws off any ability to use the correct virtual environment with python setups.

**Comment by ELLIOTTCABLE** [comment]
Ahhh, this explains so much. I was *wondering* what was going wrong with my `opam env`! ;_;

**Comment by qvacua** [comment]
Sorry for that. I'll re-revert the launching logic... -.-

**Comment by qvacua** [comment]
I reverted the recent changes; please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20210220.153052

**Comment by blochberger** [comment]
Thanks! Works like a charm.
