### ISSUE TITLE
Vimr won't load project .nvimrc 

### ISSUE THREAD

**Issue by mnavjeev** [qvacua/vimr#840]
Hi, first of all thanks for creating VimR. It's very clean and great to use. I'm having an issue where vimr won't read local .nvimrc files when opening a document. 

For example, I am managing a larger .bib file and have the following code in a local .nvimrc to fold the references automatically.

" Function for BibTexFolding
function! BibTeXFold()
	if getline(v:lnum) =~ '^@.*$'
		return ">1"
	endif
	return "="
endfunction
au BufEnter *.bib setlocal foldexpr=BibTeXFold()
au BufEnter *.bib setlocal foldmethod=expr

In terminal neovim, if I navigate to the directory an run "nvim test.bib" it will fold the code, but not if I open the code up in vimr. This is an issue I found in other projects when trying to set some local settings with project specific .nvimrc files.

**Comment by bronzehedwick** [comment]
Neovim dropped support for `.nvimrc` a while ago, in favor of `~/.config/nvim/init.vim`. See https://github.com/neovim/neovim/issues/3530

**Comment by mnavjeev** [comment]
I don't know if that's what's going on. I am running the lates neovim (0.50) and the project specifc .nvimrc file is still working  (i.e importing the specific settings in the .nvimrc file) if I run neovim from terminal.  It's only when using vimr where the file isn't loading. 

I have a separate, global ~/.config/nvim/init.vim file set up. Is there a better way to set up project specific settings in neovim than a local .nvimrc file?

**Comment by bronzehedwick** [comment]
Perhaps you have something in your `~/.config/nvim/init.vim` that sources `~/.nvimrc`?

As a sanity check, I tested this by creating `~/.nvimrc` with `set number` inside, then running `nvim`, and there are no line numbers (I don't have line numbers enabled in my `init.vim`.

The files that neovim sources are described in `:help initialization`.

**Comment by clason** [comment]
from `:h init.vim`:

>     c. If the 'exrc' option is on (which is NOT the default), the current
>       directory is searched for two files.  The first that exists is used,
>       the others are ignored.
>        -  The file ".nvimrc"
>        -  The file ".exrc"

**Comment by bronzehedwick** [comment]
Wow, you learn something every day (one of which is "read the whole thing :X) Thanks for pointing that out!

Anyway, carry on.

**Comment by mnavjeev** [comment]
Right yea. I have set excr in my ~/.config/nvim/init.vim file and then in ~/path/to/project I have a .nvimrc file specifying some specific settings for that project. If I cd ~/path/to/project and run nvim in terminal the project specific settings are displayed but not if I launch vimr.

**Comment by mnavjeev** [comment]
Issue is resolved, just had to install the vimr cli  (copy to /usr/local/bin) and start vimr from terminal in the correct directory.
