### ISSUE TITLE
can not work with telescope.nvim

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#846]
version : SNAPSHOT-20210220.153052
My cli neovim version is NVIM v0.5.0-dev+nightly, the telescope.nvim works fine there.
In vimr, the telescope.nvim main window could show up, but can not filter result and navigate result.

**Comment by clason** [comment]
vimR bundles a static snapshot of neovim, which is too old to support telescope (which, as its README clearly states, targets HEAD).

The only thing to do is for @qvacua to update the bundled neovim and release a new snapshot. This would be worth it anyway since neovim just updated a massive amount of runtime files to be in sync with vim again. 

(But maybe I'd hold off for a few days since https://github.com/neovim/neovim/pull/13664 introduced some breaking changes that still need to trickle through the ecosystem.)

**Comment by shaunsingh** [comment]
Is there any reason vimR couldn't just include a setting that lets you use your own version of neovim? VimR is a very nice gui but not being able to run quite a few of my plugins is a major turnoff

**Comment by clason** [comment]
Because vimR doesn't use a separate binary but links against a "libnvim". (That's how you get tight integration with Apple frameworks.) Using a system neovim would be a major change of architecture.

**Comment by bmulholland** [comment]
I'm thinking of just building vimr from source to get the nightly, but I suspect there's probably a magic incantation to tell vimr to use nightly neovim. Does anyone know if just updating the nvimserver submodule would be enough?

**Comment by clason** [comment]
Well, I think you need to fork it and rebase it on top of master (fixing any merge conflicts that may occur) -- the nvimserver submodule is _not_ just a clone of neovim/neovim.

**Comment by qvacua** [comment]
I'm sorry for inactivity for so long. Many things to attend to. I'll try to build a snapshot with the newest master of Nvim this weekend, however only for x86 since I'm waiting for new MacBooks to be released...

**Comment by clason** [comment]
Can't you build universal on x86? Otherwise we'll have to wait until fall for a version of VimR we can use ;)

(I'd be happy to help test it, if that's the only issue.)

**Comment by shaunsingh** [comment]
I tried building the master branch on the m1 a while back and it failed (don't exactly remember how). At the moment the x86 one feel just as snappy so its fine, but if you would like me to build an apple silicon binary in the future I would be happy to.

**Comment by domi91c** [comment]
Any update? Trying to get Telescope working as well.

**Comment by bmulholland** [comment]
[neovim 0.5 comes out tomorrow](https://neovim.discourse.group/t/neovim-0-5-release-stream-7-2-21-at-16-00-utc-12-00-pm-est/654), so the normal build process can be used then :)

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20210703.151310

**Comment by clason** [comment]
Works nicely, thank you!
