### ISSUE TITLE
When new release?

### ISSUE THREAD

**Issue by kmescharikov** [qvacua/vimr#850]

**Comment by nielsk** [comment]
Yes, a version with neovim 0.5x would be great. I use some plugins that require it and each time I open VimR they complain :(

**Comment by qvacua** [comment]
The issue is that I cannot build universal binary since I die not manage to compile ARM binary on an Intel machine and I had to return the DTK. I'm still waiting for new MBPs with Apple Silicon to be released soon... However, I could build an Intel-only snapshot it that helps.

**Comment by kmescharikov** [comment]
> The issue is that I cannot build universal binary since I die not manage to compile ARM binary on an Intel machine and I had to return the DTK. I'm still waiting for new MBPs with Apple Silicon to be released soon... However, I could build an Intel-only snapshot it that helps.

Can I help you with compiling? I have Air with m1

**Comment by clason** [comment]
It doesn't help at all with these issues, but if you _can_ manage to get a new release out this weekend, that'd be great timing: https://neovim.discourse.group/t/neovim-0-5-release-stream-7-2-21-at-16-00-utc-12-00-pm-est/654

(Neovim development has moved so much in the last months that the last snapshot has become completely unusable for people keeping up with "modern" Lua config and plugins, I am sorry to say.)

**Comment by mrinterweb** [comment]
@qvacua you probably are aware of this, but it seems like building universal binaries targeting x86 and arm64 is possible through Xcode. https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
It would be great to get a new release out for 0.5, which should release tomorrow.

**Comment by qvacua** [comment]
@mrinterweb : The Swift code–most of VimR–is not the problem. The issue is that I did not manage to cross-compile, i.e. to compile ARM64 on X86 or vice versa, the Neovim backend. I tried few compile options, but it did not work out. So, unfortunately, I need actual hardware to compile the corresponding target...

**Comment by nielsk** [comment]
So, could you do an Intel-only release then? Because M1s run Intel-apps still pretty fast as far as my understanding is.

**Comment by clason** [comment]
Yeah, that would certainly be a much better state than the current one.
(0.5 is out, by the way -- and this is a good opportunity for a shoutout to @qvacua for providing the original patch to get neovim to compile on M1; thanks to him, `brew install neovim` now just works on M1 without any additional patches!)

**Comment by qvacua** [comment]
Will do this weekend. :)

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20210703.151310
