### ISSUE TITLE
VimR can't remember window frame size and position

### ISSUE THREAD

**Issue by fannheyward** [qvacua/vimr#87]
Thanks for your work, there is a little problem.

I resize VimR's window size, then quit and restart app, the frame size and position is restored. MacVim cam remember the size and position. How to make VimR remember the size and position?

Thanks.

**Comment by IgorFobia** [comment]
I have vimr: 0.27.5-327 installed on MacOS Mojave and still have this issue. Since a while it always start with the same window size that is too long for my monitor. Maybe it began to happens after I moved a VimR window to a huge monitor where the window could indeed fit.
