### ISSUE TITLE
How to open nvim in the terminal?

### ISSUE THREAD

**Issue by ukch** [qvacua/vimr#885]
Thanks for this project. I am a long-time vim/neovim user. I have recently switched to using a Mac and am enjoying having a nice GUI for Mac OS. However, one problem I have is that when I want to quickly open a file in nvim in the terminal I am seemingly unable to do so (I can use `vimr /path/to/file` to open in the GUI, but sometimes I just want a quick terminal session)

Are the developers of this project aware of any way to open the embedded nvim in the terminal? I am aware that I could just do `brew install nvim` but that seems like an unnecessary duplication, since I already have a working nvim on my machine.

**Comment by azzsh** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在忙，无法及时回复您的邮件。将尽快给您回复。

**Comment by bronzehedwick** [comment]
@ukch I think what you're looking for is the [neovim-remote](https://github.com/mhinz/neovim-remote) project.

**Comment by kuntau** [comment]
As a long time vim/neovim user I surprised you didn't know `nvim <file>`. Neovim is terminal app.

**Comment by qvacua** [comment]
VimR does not ship with a Neovim binary which can be used on its own. Thus, you have to install `nvim` separately.

**Comment by ukch** [comment]
@qvacua Can I ask why you have decided not to include a useable nvim binary as part of this project? It seems very wasteful to have to compile and install a whole new version of nvim when we already have one built into vimr...

**Comment by bronzehedwick** [comment]
I can think of at least one reason: shipping the neovim binary means that Vimr can focus on supporting only the version shipped, and not any potential neovim version/configuration the user has installed.
