### ISSUE TITLE
How to merge the active development branch of neovim with vimr/NvimServer

### ISSUE THREAD

**Issue by JamesWidman** [qvacua/vimr#905]
Hi all,

I'm not sure if this is supported, but I am interested in working on some changes to neovim, and then testing/using that version of neovim as VimR's NvimServer.

First, I ran [the `git submodule` commands from the VimR README.md](https://github.com/qvacua/vimr#how-to-build), and then I got as far as this:

```bash
cd NvimServer
git checkout -b foo origin/develop
git remote add neovim-upstream git@github.com:neovim/neovim.git
git fetch neovim-upstream
git merge neovim-upstream/master
```

But of course this results in a lot of merge conflicts.

Perhaps one cause of this is: it seems that neovim's commit `5b839ced6` (tagged by them as `v0.6.1`)  has not yet been merged with their 'master' branch.

Is it possible to sidestep that issue?
Is there any recommended way of building VimR with neovim's main development branch? 

I understand that it would be unsupported (in the sense that you don't want new neovim bugs being sent to VimR's issue tracker,  except maybe in the special case where the issue is specifically about the interaction between neovim and gui clients).

Thanks in advance!

**Comment by qvacua** [comment]
If you want to build and test the HEAD of neovim, you should work with the `update-neovim` branch in the `vimr` repository and `NvimServer` submodule. I regularly (at least I try to) merge the upstream master of neovim into that branch. (As of now, the `develop` branch of the `NvimServer` submodule is on `v0.6.1`.)
