### ISSUE TITLE
font rendering issue on the status bar?

### ISSUE THREAD

**Issue by geohuz** [qvacua/vimr#907]
<img width="355" alt="Screen Shot 2022-02-19 at 11 28 31 PM" src="https://user-images.githubusercontent.com/730770/154807392-6a94a17e-1d6f-4079-a95c-6edf4750a2f2.png">

see the ? ? information text on the bottom right, I can't figure out how to make them display the correct text.

**Comment by pusewicz** [comment]
@geohuz What font are you using?
