### ISSUE TITLE
Can't copy VimR cli file

### ISSUE THREAD

**Issue by jehhhh** [qvacua/vimr#916]
Tried copying VimR cli tool into`/usr/local/bin` however it is not working because “vimr” couldn’t be copied because you don’t have permission to access “bin”.
<img width="813" alt="Screenshot 2022-03-16 at 17 48 04" src="https://user-images.githubusercontent.com/54982718/158588179-9cb94c64-cb5f-41dc-942b-c1eb709f3bdc.png">

**Comment by rickyc** [comment]
Assuming that the file is on your desktop, try this command.

```sh
sudo mv ~/Desktop/vimr /usr/local/bin/vimr
```

It should prompt you to type your computer's password when you use `sudo.

**Comment by jehhhh** [comment]
Oh! I ended up doing that on same day just after 20 mins filing issue. Little clear instructions would be better though :)

**Comment by qvacua** [comment]
Thank you for the support @rickyc! However, I would recommend to install `vimr` in a location where you don't need `sudo` for, e.g., `~/.local/bin` and have it in `PATH`.
