### ISSUE TITLE
vimr CLI hangs

### ISSUE THREAD

**Issue by assistcontrol** [qvacua/vimr#918]
Starting with v0.38.0-20220317.192248, the CLI script hangs indefinitely after launching vimr. It requires Ctrl-c to quit. On C-c, I get this in the terminal:

```
~/Downloads: which python3
/usr/bin/python3

~/Downloads: ./vimr
^CTraceback (most recent call last):
  File "./vimr", line 174, in <module>
    main(args)
  File "./vimr", line 132, in main
    wait_for_ui_to_close(pipe_path)
  File "./vimr", line 32, in wait_for_ui_to_close
    with open(pipe_path, 'r') as fifo:
KeyboardInterrupt
```

**Comment by archoversight** [comment]
@assistcontrol take a look at #919 or copy and paste https://github.com/qvacua/vimr/blob/5b24548eb94635013331cd55e1f0f88de0a6b34b/VimR/VimR/vimr into your `vimr` file.

**Comment by qvacua** [comment]
New release containing @archoversight's PR: https://github.com/qvacua/vimr/releases/tag/v0.38.1-20220319.090018
