### ISSUE TITLE
Please add option to turn off font smoothing

### ISSUE THREAD

**Issue by mikl** [qvacua/vimr#922]
As per #312, VimR always turns on font smoothing aka. anti-aliasing. This gives blurry fonts on retina displays.

Previously, one could override this by changing the font smoothing setting in macOS, but in recent releases, this setting is hidden. There is a console command to turn it off, but it would be neat if VimR had it own setting.

For example, VSCode offers these options:

<img width="338" alt="Screenshot 2022-03-20 at 12 38 24@2x" src="https://user-images.githubusercontent.com/10263/159160502-5885fa32-4e6a-4424-a0f8-7f3b0d73718e.png">

**Comment by qvacua** [comment]
Try "No Font Smoothing" option in Preferences -> Appearance -> Font Smoothing in the newest snapshot <https://github.com/qvacua/vimr/releases/tag/snapshot%2F20220323.180713>.

**Comment by mikl** [comment]
<img width="223" alt="Screenshot 2022-04-20 at 20 18 02@2x" src="https://user-images.githubusercontent.com/10263/164296555-7b32bb6f-21e3-463d-ad91-e8701d3c6aad.png">

Beautiful and crisp, thanks for adding this option :)

(Font is Iosevka Slab, if anyone’s wondering)
