### ISSUE TITLE
Vimr does not open files with "#" in path

### ISSUE THREAD

**Issue by mutlusun** [qvacua/vimr#928]
Hello,

Many thanks for all your work on this project!

I use the current vimr version from homebrew and noticed that vimr is not able to open files that have a "#" in their filename or path (e.g. `#overview/readme.md`). I'm not sure how long this issue persists.

I'm aware that this file naming is a bit controversial but beyond my decision. I'm running vimr on Mac OS.

If necessary, I'm happy to provide further information like logs, etc.

**Comment by qvacua** [comment]
I'll look into it, probably an Python escaping issue.

**Comment by qvacua** [comment]
Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F20220330.224200

**Comment by mutlusun** [comment]
Hey,

Many thanks for your response and your help! I tested the latest snapshot and it works indeed as intended.

Thank you :)
