### ISSUE TITLE
Opening VimR from terminal just like Mvim

### ISSUE THREAD

**Issue by alexventuraio** [qvacua/vimr#936]
I'm starting with Neovim coming from Vim and I like to use it on a GUI app instead of running it within the terminal. For vim I was able to instal **MacVim** with Homebrew which brings a binary to start it from the console just by running `mvim .` to open the MacVim application on the current directory.

Is there a way for VimR to do the same like `vimr .` ?

**Comment by kevinm6** [comment]
[Command Line Tool](https://github.com/qvacua/vimr/wiki#command-line-tool)

Follow the guide... after that, you should be able to enter `vimr < args >` in the shell (add the binary to /usr/local/bin usually)

- `vimr --help` for the syntax and commands available
- `vimr --nvim <args>` for Neovim commands

**Comment by alexventuraio** [comment]
Thanks ir worked!
