### ISSUE TITLE
question: is there a way to reveal the current buffer in the file explorer?

### ISSUE THREAD

**Issue by jaanauati** [qvacua/vimr#953]

**Comment by qianweichun** [comment]
There is round little button above the tree pane.

**Comment by qianweichun** [comment]
Is there any automatic way, that's what I want to know. I really like the native file explorer

**Comment by jaanauati** [comment]
https://github.com/qvacua/vimr/pull/960 was merged and the most recent release now has the command:
`VimRRevealCurrentBuffer`, example:
`:VimRRevealCurrentBuffer`
