### ISSUE TITLE
Opening VimR from the command line

### ISSUE THREAD

**Issue by tosbourn** [qvacua/vimr#99]
It would be great if it was documented how to access VimR from the command line and if the application was aware of the current working directory to open that as the default project.
# Use Case

I spend all day in my command line jumping between projects. Being able to type vimr in a directory or vimr /path/to/filename would be huge.
# Attempts

I have tried calling `open /Applications/VimR.app` - this works but doesn't take into account the current working directory.

I have tried running `/Applications/VimR.app/Contents/MacOS/VimR` but this doesn't appear to work.

**Comment by AdamT** [comment]
Incase anyone comes here from Google. Command line tool: https://github.com/qvacua/vimr/wiki#command-line-tool
